### ISSUE TITLE
npm and buffertools install issue

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#10]
When I upgrade to Node.js 0.12, I get an error.  I suspect the NPM package `buffertools` is incompatible.

```
$ grunt nodeunit
Running "nodeunit" task
Running Nodeunit test suite against all tests

module.js:338
    throw err;
          ^
Error: Cannot find module './build/Debug/buffertools.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/matthew/Projects/Ably/clients/ably-js/node_modules/buffertools/buffertools.js:26:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
>> Nodeunit tests failed!
```

**Comment by paddybyers** [comment]
Did you reinstall/rebuild all modules when upgrading?

`nvm reinstall-packages 0.12`

**Comment by mattheworiordan** [comment]
I deleted my entire `node_modules` folder

**Comment by paddybyers** [comment]
Hmm, works for me.

On the face of it, the module hasn't built.

Can you remove `node_modules` and capture the output of `npm install git://github.com/bnoordhuis/node-buffertools.git --verbose`

and see if requiring it standalone succeeds:

````
node
> require('buffertools')
````

**Comment by mattheworiordan** [comment]
Odd, it works now for me, and it also seems to be building in Travis with version `0.12`

**Comment by mattheworiordan** [comment]
Actually, I am wrong, it does not work in Travis, https://travis-ci.org/ably/ably-js/jobs/52284240

**Comment by mattheworiordan** [comment]
Once this issue is resolved, Matt to ensure the browser tests in Travis only run for one version of the build i.e. not every Node.js 0.10 and Node.js 0.12.   We should then add io.js support as well.

**Comment by paddybyers** [comment]
This is an npm bug which revolves around how `peerDependencies` are handled, which causes the install for the module to be re-entered and a race condition means that it sees partially-unpacked modules and it all goes very bad.

The workaround is not to allow the `peerDependencies` handling to kick in, by adding `requirejs` as an explicit dependency.

**Comment by mattheworiordan** [comment]
Have you added a commit then to fix this?

**Comment by paddybyers** [comment]
https://github.com/ably/ably-js/commit/7a81a222595dd59f17d7839416cb68652314c81a

**Comment by jhoffner** [comment]
I also ran into this issue after loading your library. I'm working off of the node:6.0.0 Docker image. I used `(cd /server/node_modules/buffertools ; node-gyp rebuild -d)` to fix it for now.

**Comment by mattheworiordan** [comment]
Thanks @jhoffner. @paddybyers as this was with Node 6, is there anything we should consider in our docs in our code to help resolve this?

**Comment by mattheworiordan** [comment]
This is no longer an issue
