### ISSUE TITLE
Ably.Realtime.Crypto.getDefaultParams() suddenly stopped working!

### ISSUE THREAD

**Issue by alamaral** [ably/ably-js#1000]
We have code that has been deployed and working for a while that **_suddenly_** stopped working today with an exception:

This is the code:

         var hexString = "<a bunch of hex digits>";
         var cipherParams = Ably.Realtime.Crypto.getDefaultParams({ key:hexStringToArrayBuffer(hexString)});

This is the exception we're suddenly seeing:

TypeError: Cannot read properties of undefined (reading 'getDefaultParams')

I see a bunch of changes that happened today, but looking at the git diffs I don't see anything that is specifically
related to Ably.Realtime.Crypto:

commit 6c0a39c4a860521b8659cc7e32b53c266e35cea2 (HEAD -> main, tag: 1.2.23, origin/main, origin/HEAD)
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 17:36:06 2022 +0100
    Revert dev changes to cdn_deploy script
commit 3ccd5a280466e5492c3cc7cefd40ceef73ffab8e
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 17:30:00 2022 +0100
    Fix regex error in cdn_deploy script
commit 4a658c4aeec3e36084f0d079a2468a82da647f42
Merge: 3ce2b429 24df0957
Author: Owen Pearson <48608556+owenpearson@users.noreply.github.com>
Date:   Thu Jun 9 17:11:50 2022 +0100
    Merge pull request #999 from ably/release/1.2.23
    Release 1.2.23
commit 24df095735b30826c92e92340f33fe147a827a69
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 16:56:11 2022 +0100
    Bump version to 1.2.23
commit afd639fd8b35fa84c3600b96aac79309d8071034
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 16:53:54 2022 +0100
    Update CHANGELOG
commit 3ce2b4299a4a6ff8d76675884e81e70b79bf6145
Merge: eeafdc74 c14ff509
Author: Owen Pearson <48608556+owenpearson@users.noreply.github.com>
Date:   Thu Jun 9 16:41:50 2022 +0100
    Merge pull request #998 from ably/remove-sourcemaps
    Revert CDN sourcemaps
commit eeafdc74cb2470943084e872899cceb81282aadb
Merge: cd35d6be 8e9ffac1
Author: Owen Pearson <48608556+owenpearson@users.noreply.github.com>
Date:   Thu Jun 9 16:41:41 2022 +0100
    Merge pull request #993 from ably/salesforce-lightning-compat
    Salesforce lightning compat
commit 8e9ffac1cbfc09d0797d8e0ad9575536bd2ea09d
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 16:20:16 2022 +0100
    Use optional chaining to check for `console.log` existence
commit c14ff5096bb0e6e947f61e529addbdb3b9f75a33
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 15:30:19 2022 +0100
    Revert sourcemap stuff
commit 38d76e7b55c23e7ebaa889960618d121faf8405a
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 14:13:19 2022 +0100
    Remove sourcemaps from cdn_deploy script
commit 43f41bb88a811f4a2665a355d75be8fb488c1d95
Author: Owen Pearson <owen.pearson@ably.com>
Date:   Thu Jun 9 14:11:25 2022 +0100
    Update cdn_deploy default includeDirs

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2037) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @alamaral thanks for reporting this, this is a bug in the 1.2.23 release, I'm sorry for the inconvenience. We'll release a fix shortly, until then you should be able to use this method in v1.2.22. If you're using the CDN you can use this script tag to pin to the working version `<script src="https://cdn.ably.com/lib/ably.min-1.2.22.js"></script>`.

**Comment by alamaral** [comment]
Thanks!
