### ISSUE TITLE
Uncaught Error userAgent

### ISSUE THREAD

**Issue by roblegaspi** [ably/ably-js#1006]
Does anyone encountered this error before? I hope someone can help me with this

I want to use this package on my react native expo app

I received error like this
```
undefined is not an object (evaluating 'globalOrWindow.navigator.userAgent.toString')
```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2044) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @roblegaspi thanks for reporting this, we're looking in to it now. This line was added in 1.2.23 so you should be able to continue using ably with your react-native app by specifying version 1.2.22 in your package.json. I'll let you know in this thread when we have a fix available.
