### ISSUE TITLE
TypeScript types have `Channel#publish(…options?: PublishOptions)` options on Realtime instead of REST

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1034]
As described by [RSL1l](https://docs.ably.com/client-lib-development-guide/features/#RSL1l):

> The publish(Message) and publish(Message[]) forms of the method should take an extra Dict<String, Stringifiable> argument. These parameters should be encoded using normal querystring-encoding and sent as part of the query string of the REST publish. (Stringifiable is defined in RTC1f) 

* i.e. the _REST_ publish methods should accept an additional dictionary parameter. But in `ably.d.ts` it is the _realtime_ ones that accept the parameter.

This is inconsistent with the IDL and is in fact inconsistent with the actual implementation of the `publish` methods:

* The [REST method looks for a `params` passed in](https://github.com/ably/ably-js/blob/b24d112d6a0687294132a5c0690c1ae059506f69/src/common/lib/client/channel.ts#L124-L133)
* The [realtime method does not](https://github.com/ably/ably-js/blob/b24d112d6a0687294132a5c0690c1ae059506f69/src/common/lib/client/realtimechannel.ts#L190-L242).

We need to switch this around in the signatures (might need to coincide with a major release of the SDK as it's technically a breaking change, albeit to a broken behaviour).

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-2493) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Hi @deanna-lad, I was wondering why we closed this one?

**Comment by deanna-lad** [comment]
This issue has been completed so in refinement we closed the issue.

**Comment by lawrence-forooghian** [comment]
Ah, cool, I was confused because I didn't see any linked PRs, but it does look like it's been fixed 👍

**Comment by owenpearson** [comment]
@lawrence-forooghian you fixed it in https://github.com/ably/ably-js/commit/e45d70f2b65811c5435554e8bbd3ce34a59dcf1f 🙂
