### ISSUE TITLE
Token Params are not being sent through to authUrl

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#108]
See https://github.com/ably/demo-mobile-phonegap-cordova/blob/master/www/js/app.js#L100, the authUrl requests do not have the token params appended.

We need a test for this.

**Comment by SimonWoolf** [comment]
@mattheworiordan I'm not clear on what the desired behaviour is here. there's an `authParams` option which says "Query params to be included in any request made by the library to the authURL" (which works correctly) - is the proposal that the contents of that should be merged with tokenparams?

**Comment by SimonWoolf** [comment]
(Eg currently the clientid that the library is instantiated with isn't even passed to the builtin token request, never mind an authCallback or authUrl -- if you do `new Ably.Realtime({key: <key>, clientId: "foo", useTokenAuth: true})`, the resulting token doesn't include the clientId. Should that also be changed?)

**Comment by mattheworiordan** [comment]
@SimonWoolf I was not previously aware that this was the case, but @paddybyers told me that he understood that the authParams are passed through to the authUrl as query params when a GET request is being made, and as part of the body when using POST.  I understood the authParams should also be passed to the authCallback. See the definition in Java https://github.com/ably/ably-java/blob/83b365feb722e24093ee969c5aee85af48e4bd36/src/io/ably/rest/Auth.java#L321-L322

**Comment by SimonWoolf** [comment]
@mattheworiordan 

> the authParams are passed through to the authUrl as query params 

Yeah, and they are. But that phonegap demo you linked doesn't specify an `authParams`. so was wondering if you meant the clientId (that the lib was initialized with) should be passed as a param as well

**Comment by paddybyers** [comment]
> clientId (that the lib was initialized with) should be passed as a param as well

yes, because that's implicitly an `authParam` if not explicitly

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/115/files
