### ISSUE TITLE
React Native crash because connectionSerial type is object instead of number

### ISSUE THREAD

**Issue by sparga** [ably/ably-js#1093]
It appears that [this commit](https://github.com/ably/ably-js/commit/2d3e0ae6c58cee90451e3e213afb21f520952d81#diff-9b7befa5663f39e9deaf9c8500109e233f464e51b87242ec7c74c56ec5820485R1137) introduced a regression because in `transport.ts`, the sync event is emitted like this:
```typescript
this.emit('sync', message.connectionId, message);
```
and in `connectionmanager.ts`, the callback signature is now different:

```typescript
transport.once('sync', function (connectionId: string, syncSerial: number) {
      clearTimeout(timeout);
      callback(null, connectionId, syncSerial);
    });
```

This is actually causing a crash with React Native on Android because the `connectionSerial` parameter is serialized as `&connectionSerial=[object Object]` when transformed into an URL. As a result, `WebSocketModule.java` in React Native is throwing a `java.lang.IllegalArgumentException`.

I believe the fix is to update the emitting code like this:
```typescript
this.emit('sync', message.connectionId, message.connectionSerial);
```

**Comment by owenpearson** [comment]
Hey @sparga thanks a lot for raising this and investigating for yourself! I think your fix to `transport.ts` is correct so we'll get it fixed and I'll let you know in this thread when the patched version is available on NPM.
