### ISSUE TITLE
The 'credentials' field on 'RequestInitializerDict' is not implemented

### ISSUE THREAD

**Issue by Kaperstone** [ably/ably-js#1112]
I am getting the error

```
The 'credentials' field on 'RequestInitializerDict' is not implemented
```

After deploying to Cloudflare-workers with `ably-webworker.min`, basically, if to remove `credentials` then the error disappears and the `worker` is emitting message to Ably.

**Comment by Kaperstone** [comment]
Cloudflare workers don't and won't support `credentials` headers.

So its either choosing Ably or Cloudflare Workers.

**Comment by owenpearson** [comment]
Hey @Kaperstone, thanks for reporting this! I think we should be able to update the library to not send `credentials` in a cloudflare workers context, so I'll reopen this issue for now and hopefully we will have it fixed soon 🙂

**Comment by owenpearson** [comment]
Hey @Kaperstone, we've updated the library in 1.2.37 to not send the credentials field when using the webworker version. I hope this helps and please let us know if you have any further issues :)
