### ISSUE TITLE
Migrate to webpack v5

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#1184]
See the official [migration guide](https://webpack.js.org/migrate/5/) and [previous attempt](https://github.com/ably/ably-js/pull/839).

This work should land in a new integration branch called `integration/v2`

As part of this work we will need to manually test that the lib still works in react-native and web workers, since these aren't covered by automated tests.

**Comment by lawrence-forooghian** [comment]
Closed in #1201.
