### ISSUE TITLE
disconnected with self generated JWT token

### ISSUE THREAD

**Issue by step135** [ably/ably-js#1233]
Never connected using generated JWT token. And there is no error fired to know the reason.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4149) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @step135, thanks for reaching out!

You can [observe connection state](https://ably.com/docs/realtime/connection?lang=javascript#:~:text=Listening%20for%20state%20changes) by using the `client.connection` event emitter interface:

```typescript
// The listener gets called every time the client connection state changes
client.connection.on(stateChange => {
  stateChange.previous // the previous connection state
  stateChange.current // the new connection state
  stateChange.reason // the error which caused the connection state to change, if any
});
```

You should be able to use this to observe which error is preventing the client from establishing a connection and diagnose your JWT problem accordingly. Let us know if this doesn't work or if you have any further issues.

**Comment by VeskeR** [comment]
Closing this issue as it has been inactive for more than a year. If you are still experiencing issues with using JWT tokens in ably-js, please open a new issue.
