### ISSUE TITLE
Unable to set as default origin header

### ISSUE THREAD

**Issue by nikitadubyk** [ably/ably-js#1262]
Hi!

I'm trying to connect ably to react native and encountered the problem that after a successful connection I get an error - Unable to set as default origin header. At the same time, all requests are successful, connection status changes to connected.

Can you please tell me how to fix this?

```
const client = new Realtime({
          clientId: name,
          log: { level: 2 },
          useTokenAuth: true,
          token: ablyToken.data,
          authCallback: async (_params, callback) => {
           ....
          },
        });
```

![Screenshot_1684136306](https://github.com/ably/ably-js/assets/73419198/0b50e8b0-1087-4791-9617-ee0f850aa298)

**Comment by owenpearson** [comment]
Hey @nikitadubyk, thanks for reporting this! Looks like the underlying issue here is [this](https://stackoverflow.com/questions/47486413/passing-parameter-in-websocket-uri-on-react-native-is-not-working. I've opened a PR to fix it and will let you know when that's been released.

**Comment by nikitadubyk** [comment]
@owenpearson okay, thank you! I'll be waiting for

**Comment by owenpearson** [comment]
@nikitadubyk I've tried to reproduce the issue on my end using android and the same set of client options you're using but it all seems to work fine for me. Could you let us know what versions of ably-js, react-native, and the jdk you're using? if it's not too difficult a repro script would be very helpful too

**Comment by owenpearson** [comment]
Some further info: this appears to be a manifestation of https://github.com/facebook/react-native/issues/16041 which was raised a while ago. It certainly doesn't seem to be an issue on recent versions of react-native so I think upgrading to a newer RN version should hopefully fix this

**Comment by nikitadubyk** [comment]
@owenpearson I use `"react-native": "0.71.7"`, `"ably": "^1.2.39"` and jdk 17 version. Now I added transports: ['xhr_streaming'] to the settings and that fixed the error, but I would still like to use sockets

**Comment by nikitadubyk** [comment]
Now I tried to update rn to 0.71.8 and the error is still there

**Comment by nikitadubyk** [comment]
@owenpearson I was able to reproduce the error, please see this repository - https://github.com/nikitadubyk/ably-ws-error

**Comment by nikitadubyk** [comment]
@owenpearson I found another interesting bug related to `transports: ['xhr_streaming']`. This mode for some reason only works successfully when debugger is open (I use react native debugger). As soon as you close the debugger, it fails to connect.
I managed to solve this problem by changing the `transports` to `xhr_polling`

**Comment by owenpearson** [comment]
Hey Nikita, thanks a lot for the example repo - that's super helpful 🙂 

I was able to reproduce the error and was able to determine that the root cause of this issue is that `clientId` is not url encoded in the websocket connection URI. The websocket constructor in web browsers and NodeJS will just encode it automatically but with react-native websocket (for java at least) it crashes the application. I've opened #1263 to fix this, for the time being you should be able to avoid this issue by not using space characters (or other unacceptable url string characters) in your clientId.

Thanks for mentioning the `xhr_streaming` issue btw, I will open a separate issue to investigate that.

**Comment by nikitadubyk** [comment]
Thank you, that helped!

**Comment by owenpearson** [comment]
Hey @nikitadubyk, we just release version 1.2.40 of the library which should fix this, let me know if you have any further issues
