### ISSUE TITLE
ImportError: cannot import name 'AblyRealtime' from 'ably'

### ISSUE THREAD

**Issue by Foenixxx** [ably/ably-js#1282]
ImportError: cannot import name 'AblyRealtime' from 'ably'

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4152) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @Foenixxx, could you give us some more information about what you're doing to get this error message? Based on the error message it looks like you're trying to use the ably-python realtime client but haven't installed the beta version of the package - if this is the case, please check the [installation instructions](https://github.com/ably/ably-python#installing-the-realtime-client).

**Comment by VeskeR** [comment]
Closing this as the issue has been inactive for more than a year.
