### ISSUE TITLE
Release version 2.0.0 of ably-js

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1297]
This issue serves as a place to track additional work we need to do as part of this release.

- [ ] Update documentation website for public API changes (I'll create linked issues in ably/docs once we've made the API changes)
- [ ] Document new platform requirements

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4155) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
Duplicate
