### ISSUE TITLE
Incorrect type for Message['connectionId']

### ISSUE THREAD

**Issue by JCB-K** [ably/ably-js#1301]
type according to typescript:
<img width="515" alt="Screenshot 2023-05-25 at 15 51 30" src="https://github.com/ably/ably-js/assets/636039/b6d99d28-4227-4d5f-bba6-06910b52559c">

Logging a message sent from the REST SDK:

<img width="191" alt="Screenshot 2023-05-25 at 15 52 06" src="https://github.com/ably/ably-js/assets/636039/633caa4f-0686-478f-a066-920314550cd8">

This means that `connectionId` should be typed as `string | undefined`

**Comment by owenpearson** [comment]
@JCB-K Thanks for reporting this, you're right that it should be optional - I've opened a PR to update
