### ISSUE TITLE
is this library supporting react native?

### ISSUE THREAD

**Issue by ManuRodgers** [ably/ably-js#1359]

**Comment by owenpearson** [comment]
Hey @ManuRodgers, yes the library does support react native, see the [supported platforms](https://github.com/ably/ably-js#supported-platforms) section of the README 🙂 Let us know if you have any further questions

**Comment by bryanltobing** [comment]
hi. are there any additional steps to make this work with react native? @owenpearson

**Comment by owenpearson** [comment]
Hey @bryanltobing, no there are no additional steps, just `npm install` it into your react-native project and you're good to go 🙂
