### ISSUE TITLE
"Module not found" warnings when importing "ably/promises" on nextjs server

### ISSUE THREAD

**Issue by JohnGemstone** [ably/ably-js#1371]
I get the following warnings in my console when importing Ably on server (nextjs).

```
warn  - ./node_modules/.pnpm/keyv@4.5.2/node_modules/keyv/src/index.js
Critical dependency: the request of a dependency is an expression

./node_modules/.pnpm/ws@5.2.3/node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in '/Users/x/Sites/_tests/ably/ably-nextjs-fundamentals-kit/node_modules/.pnpm/ws@5.2.3/node_modules/ws/lib'

./node_modules/.pnpm/ws@5.2.3/node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/Users/x/Sites/_tests/ably/ably-nextjs-fundamentals-kit/node_modules/.pnpm/ws@5.2.3/node_modules/ws/lib'
```

These are reproducible by installing the ably-labs next fundamentals example. Navigate to the pub-sub page and publish a message from the server and observe the console.

https://github.com/ably-labs/ably-nextjs-fundamentals-kit/tree/main

This is also reproducible making a nextjs project from scratch using the latest libraries.
I experienced them using:

```
"next": "^13.4.7",
"@ably-labs/react-hooks": "^2.1.1",
"ably": "^1.2.40",
```

I'm also using pnpm on OSX.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4166) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hey @JohnGemstone, thanks for reporting this!

I've reproduced the issue using the ably-nextjs-fundamentals-kit project and it appears to only happen when using pnpm, if it's feasible for you, you should be able to just use npm as a workaround for now. We will investigate this and see what we can do to support pnpm out of the box. FWIW it seems the underlying issue is that pnpm is incorrectly trying to use the nodejs version of the library on the client side.

**Comment by JohnGemstone** [comment]
Nice one thanks, I'll give npm a spin next time. Will leave this open in case you find a workaround 🔎

**Comment by sahilprasad** [comment]
hey @owenpearson @JohnGemstone, any updates on this? These messages are clogging our dev logs significantly and would love to get rid of them without having to swap to npm.

**Comment by evanrooijen** [comment]
Samen happens when using turborepo and bun

**Comment by Elmosh** [comment]
hey @owenpearson , I just migrated to npm just to fix this error, yet the same issue still failing the built.

**Comment by VeskeR** [comment]
Update:

try using `serverComponentsExternalPackages` option in `next.config.js` (read more about the option [here](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages)):

```javascript
const nextConfig = {
  // ...
  experimental: {
    serverComponentsExternalPackages: ['ably'],
  },
};
```

This should also eliminate the need for using `overrides` field in your `package.json` for `cacheable-request`:
```json
"overrides": {
  "cacheable-request": {
    "keyv": "npm:@keyvhq/core@~1.6.6"
  }
}
```

Read more about this issue and suggested solution in this issue's comment: https://github.com/ably/ably-js/issues/1699#issuecomment-2022702584
