### ISSUE TITLE
Restrict JWT to specific channels

### ISSUE THREAD

**Issue by greffgreff** [ably/ably-js#1382]
Hello. I am attempting to create a JWT for a number of users through my authentication server. I would like to restrict users to a specific channel, `this_is_a_channel`, through the JWT claims. I have read the docs regarding [capabilities](https://ably.com/docs/auth/capabilities) and [authentication](https://ably.com/docs/api/realtime-sdk/authentication?lang=javascript) but did not manage to achieve this. 

Currently, the authentication server generates JWT with payloads as folow:
```json
{
  "iat": 1689034999,
  "exp": 1689121399,
  "x-ably-clientId": "this_is_a_client_id",
  "x-ably-capabilities": {
    "this_is_a_channel": [
      "publish",
      "subscribe"
    ]
  }
}
```

What should the JWT payload look like? Thanks in advance!

Here is some starting code from the demo:
```js
async function CreateJWT(
  clientId: string,
  apiKey: string,
  claim: string
): Promise<string> {
  const [appId, signingKey] = apiKey.split(':', 2)
  const enc = new TextEncoder()
  return new SignJWT({
    'x-ably-capabilities': `{"*":["*"]}`, // <- ?
    'x-ably-clientId': clientId,
    'ably.channel.*': claim,
  })
    .setProtectedHeader({ kid: appId, alg: 'HS256' })
    .setIssuedAt()
    .setExpirationTime('24h')
    .sign(enc.encode(signingKey))
}
```

**Comment by sacOO7** [comment]
@greffgreff the jwt token looks good, is server giving any issues for the created token?

**Comment by sacOO7** [comment]
You can check this tutorial for more information https://ably.com/tutorials/jwt-authentication#setup-ably-account

**Comment by owenpearson** [comment]
Hey @greffgreff, I think the problem here is that you need to rename `x-ably-capabilities` to `x-ably-capability`, other than that the token looks fine to me. Let us know if you still have issues after changing it 🙂

**Comment by greffgreff** [comment]
No luck still. 😞 I tried the following payload structures:

With `x-ably-capabilities` and `capability`, all connections are allowed to any channels (as in messages are being published and fetched):
```json
{
  "iat": 1689085874,
  "exp": 1689089474,
  "x-ably-clientId": "this_is_a_client_id",
  "x-ably-capabilities": {
    "this_is_a_channel": [
      "publish",
      "subscribe"
    ]
  }
}
```

With `x-ably-capability`, no connections are allowed to any channel (nothing occurs but no errors thrown):
```json
{
  "iat": 1689086087,
  "exp": 1689089687,
  "x-ably-clientId": "this_is_a_client_id",
  "x-ably-capability": {
    "this_is_a_channel": [
      "publish",
      "subscribe"
    ]
  }
}
```

Here is the small bit of code I am working with:
```js
import { useEffect } from "react";
import { Realtime } from "ably";

export default () => {
  useEffect(() => {
    connectToAbly();
  }, []);

  const connectToAbly = async () => {
    try {
      const authUrl = "https://localhost:44380/ably/token/this_is_a_client_id";
      const ably = new Realtime({ authUrl, authMethod: "POST" });
      const channel = ably.channels.get("this_is_a_channelthwrth");

      channel.subscribe(message => {
        console.log("Received message:", message.data);
      });

      channel.publish("your-event-name", "your-message-data");
    } catch (error) {
      console.error("Failed to connect to Ably:", error);
    }
  };

  return <h1>Ably Connection Example</h1>;
};
```
where `https://localhost:44380/ably/token/this_is_a_client_id` returns a signed and valid JWT in the return body.

I also want to mention that the [demo](https://github.com/ably-labs/realtime-examples/blob/main/src/Layout.tsx#L52) utilizes the `x-ably-capabilities` while the [docs](https://github.com/ably/docs/blob/main/content/auth/capabilities.textile#custom-restrictions-on-channels) mention `x-ably-capability`. 

Thanks for the assistance!

**Comment by sacOO7** [comment]
@greffgreff please try the above solution, I am sure you will find everything needed there. Let us know if you need anything else : )

**Comment by paddybyers** [comment]
If you're still not getting anywhere, can you paste here the encoded JWT text?

**Comment by greffgreff** [comment]
Hello again. I've taken a look at `getSignedToken`. Below are some of the JWTs patterns I've tried:

`x-ably-capability` with desired restrictions on `this_is_a_channel` channel, nothing happens (no errors, no messages):
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6Ik9YSWt1QS5CRnRYaFEifQ.eyJpYXQiOjE2ODkxMTc0MjcsImV4cCI6MTY4OTEyMTAyNywieC1hYmx5LWNsaWVudElkIjoidGhpc19pc19hX2NsaWVudF9pZCIsIngtYWJseS1jYXBhYmlsaXR5Ijp7InRoaXNfaXNfYV9jaGFubmVsIjpbInB1Ymxpc2giLCJzdWJzY3JpYmUiLCJjaGFubmVsLW1ldGFkYXRhIl19fQ.SIGNATURE
```

`x-ably-capability` to accept everything (e.i `{"*":["*"]}`), like before, nothing happens (no errors, no messages):
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6Ik9YSWt1QS5CRnRYaFEifQ.eyJpYXQiOjE2ODkxMTgzNjQsImV4cCI6MTY4OTEyMTk2NCwieC1hYmx5LWNsaWVudElkIjoidGhpc19pc19hX2NsaWVudF9pZCIsIngtYWJseS1jYXBhYmlsaXR5Ijp7IioiOlsiKiJdfX0.SIGNATURE
```

No `x-ably-capability` present, able to connect and receive messages from channel:
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiIsImtpZCI6Ik9YSWt1QS5CRnRYaFEifQ.eyJpYXQiOjE2ODkxMTk0MTMsImV4cCI6MTY4OTEyMzAxMywieC1hYmx5LWNsaWVudElkIjoidGhpc19pc19hX2NsaWVudF9pZCJ9.SIGNATURE
```

After reflection, I don't believe there is an issue with the payload. Is there some sort of way to enable some sort of debug mode with the ably js package for logs?

Thanks again!

**Comment by greffgreff** [comment]
Hello again! After looking at what @sacOO7 has provided, I managed to fix the issue. The encoding of the capabilities in the payload should be encoded like so: 
```
"x-ably-capability": "{\"public:this_is_a_channel\":[\"*\"]}"
```
as opposed to:
```
"x-ably-capability": {
  "public:this_is_a_channel": [
    "*"
  ]
}
```
Thanks for the help!
