### ISSUE TITLE
`Utils#inspectError` doesn’t include error’s `message` on web

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1390]
## Description

On the web, `Utils#inspectError` uses `JSON.stringify` to serialize the error. However, `JSON.stringify` will not include the error’s `message` property, as described and explained [here](https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify).

We should change the serialization such that the result includes the `message` property (there are some suggestions on the above-linked page).

**Comment by SimonWoolf** [comment]
> On the web, Utils#inspectError uses JSON.stringify to serialize the error. 

It shouldn't be. There's specific logic in the sdk that says displaying an error should use toString() on ErrorInfos and Errors, it should only be falling back to stringify on unknown objects

**Comment by lawrence-forooghian** [comment]
Yeah, it seems to be doing [the exact opposite](https://github.com/ably/ably-js/blob/8100e3a718175ceefbb3ac08d7154434cae4a6ba/src/common/lib/util/utils.ts#L410-L418) at the moment.
