### ISSUE TITLE
Create tree-shakable `RealtimeChannels` and `RealtimePresence` modules

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#1393]
- depends on #1374 
- create `RealtimeChannels` and `RealtimePresence` classes
- `RealtimeChannels` class encapsulates creation of `RealtimeChannel` instances with ability to publish and subscribe
- `RealtimePresence`, if provided, gives access to the `RealtimeChannel.presence` interface

**Comment by lawrence-forooghian** [comment]
@owenpearson since in #1417 we now have separate `BaseRest` and `BaseRealtime` classes, I guess we don't need to create a `RealtimeChannels` module any more, do we? i.e. we just need to split out realtime presence.

**Comment by lawrence-forooghian** [comment]
Done in #1428.
