### ISSUE TITLE
Create tree-shakable `MessageInteractions` module

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#1397]
- depends on #1374 and #1393 
- create new `MessageInteractions` class
- if provided to the `BaseClient` constructor, allows user to add filtered subscriptions

**Comment by lawrence-forooghian** [comment]
@owenpearson explained today that there are multiple concepts of "filtered subscription". The one that this issue is talking about is the overload of `RealtimeChannel#subscribe` that accepts a `MessageFilter`.

**Comment by lawrence-forooghian** [comment]
Closed in #1473.
