### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by Gautam25Raj** [ably/ably-js#1437]
**Versions:**
- Node.js: 18.17.1
- ably: 1.2.44,
- next: 13.4.19,
- react: 18.2.0,
- react-dom: 18.2.0,

**Actual behavior**
When using got Ably with Next.js 13 App Router, the Webpack process outputs the following WARNING:
```
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/keyv/src/index.js
./node_modules/cacheable-request/src/index.js
./node_modules/got/dist/source/core/index.js
./node_modules/got/dist/source/create.js
./node_modules/got/dist/source/index.js
./node_modules/ably/build/ably-node.js
./components

./node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in 'Your project link\node_modules\ws\lib'

Import trace for requested module:
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/index.js
./node_modules/ably/build/ably-node.js
./components

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in 'Your project link\node_modules\ws\lib'

Import trace for requested module:
./node_modules/ws/lib/validation.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/index.js
./node_modules/ably/build/ably-node.js
./components
```
**The below 2 module not found error can be solved by using** `npm i bufferutil` and `npm i utf-8-validate`.

**Expected behavior**
The expected behavior is not to see warnings and module not found error on running next app. The error can only be seen when using `import Ably from 'ably';`.

Thanks for looking into this! If there is anything I can do on my side to work around the problem please advise.

**Comment by owenpearson** [comment]
Hey @Gautam25Raj, thank for reaching out!

Annoyingly, this issue actually comes from [`ws`](https://github.com/websockets/ws) which is the WebSocket client we use in NodeJS. `ws` has some conditional logic which imports some of its devDependencies and NextJS will scan for these imports and warn you that the dependencies are missing, however these imports will never actually be loaded when you're using the library yourself. Therefore, it is safe to ignore these warnings.

I do understand that warnings like these are very annoying to live with though, so here's something you can add to your `next.config.js` to suppress them:

```javascript
module.exports = {
  webpack: (config) => {
    config.externals.push({
      'utf-8-validate': 'commonjs utf-8-validate',
      'bufferutil': 'commonjs bufferutil',
    })
    return config
  },
}
```

I hope this helps, let us know if you have any further issues 🙂
