### ISSUE TITLE
How do I subscribe to "present" events with usePresence React hook?

### ISSUE THREAD

**Issue by bookercodes** [ably/ably-js#1448]
I'm building a "who's online?" list, and want to see member's already connected before I joined.

If I understand well, the way to do this with Ably is with the "present" presence event.

In vanilla JavaScript, you might subscribe to "present" like this,

```
channel.presence.subscribe('present', member => {
  console.log('present?', member)
})
```
When using Ably React hooks, is there a more idiomatic way?

I've been toying with `usePresence` - the callback is fired for "enter", "leave", and "update" presence events, but I haven't seen it fire for "present".

```
  const { presenceData, updateStatus } = usePresence('chat', { username }, data => {
    // action could  equal enter / leave / update
    // what about present?

    console.log("presence data", data)
  })
```

In the README, I see the following text:

> Please note that fetching present members is executed as an effect, so it'll load in after your component renders for the first time.

It seems relevant to my problem, but I don't understand. Appreciate any help!

**Comment by owenpearson** [comment]
@bookercodes nice one figuring it out! with the new `1.2.45` version the library will give a more helpful error message in this situation 😄
