### ISSUE TITLE
Cannot find module '../../../../../ably.js'

### ISSUE THREAD

**Issue by melodyclue** [ably/ably-js#1495]
The Types used in ably appear to be imported from ably.js, but this path is said not to exist. 
This causes channel.publish to be `any`

<img width="870" alt="スクリーンショット 2023-11-10 12 00 14" src="https://github.com/ably/ably-js/assets/117662771/a6bfaa6b-e179-4de4-9c7b-11713395b798">

**Comment by melodyclue** [comment]
This works.
`import { Types } from '../../../../ably';`

instead of 
`import { Types } from '../../../../../ably.js';`

**Comment by owenpearson** [comment]
Hey @melodyclue, thanks for reporting this - you're right it is an issue with pnpm and the typings work fine with plain npm. I'll let you know when we've released a fix.

**Comment by owenpearson** [comment]
Hey @melodyclue, we've fixed this issue now, please try version 1.2.48 and let us know if you have any further issues 🙂

**Comment by melodyclue** [comment]
@owenpearson  Thanks! Now Type all works well 😃
