### ISSUE TITLE
Make modular variant of the library available to Web Workers

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1514]
Users running Ably inside a Web Worker will have the same bundle size concerns that v2’s modular variant of the library aims to address. So, we should make the modular variant available for use in Web Workers. I'd suggest that we consider getting rid of the current Web Worker build of the library and instead just use the normal web bundle, detecting whether we're running inside a Web Worker at runtime.

We also need to provide the modular variant of the library for use in Web Workers so that they can use Vcdiff functionality, which was removed from the default web bundle (and hence the Web Worker bundle) in #1512.

**Comment by lawrence-forooghian** [comment]
Do you have any thoughts on this, @owenpearson? Do you think that getting rid of the Web Worker-specific build would be a good way forward?

**Comment by VeskeR** [comment]
Closed in https://github.com/ably/ably-js/pull/1543
