### ISSUE TITLE
Remove code that's supporting older platforms (in v2)

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1538]
In particular, owenpearson said there is a bunch of stuff in `utils.ts` that can be replaced by built-in ES stuff. (Once we've done #1537 we'll know what version of ES we're targeting.)

There may also be other stuff that's supporting older browsers; again, waiting for outcome of #1537 to know what we can remove.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4204) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Based on DR accepted in https://github.com/ably/ably-js/issues/1537, the code to remove would include:
- IE specific code (can be found by searching for words `IE`, `MSIE`, `IE[\d+]`, `IE [\d+]`, `Internet Explorer`)
- functions/class methods polyfills that are natively supported by ES2017 (Array.filter, Array.map etc if we don't use it already. mostly found in [utils.ts](https://github.com/ably/ably-js/blob/integration/v2/src/common/lib/util/utils.ts)
- old browser versions specific code that we don't support anymore (old versions of Chrome, Firefox, Safari etc)

**Comment by VeskeR** [comment]
Done in https://github.com/ably/ably-js/pull/1629
