### ISSUE TITLE
Exceed peak connection limit immediately.

### ISSUE THREAD

**Issue by valentins666** [ably/ably-js#1545]
I wrapped react app with AblyProvider of `ably/react` library, and used `useChannel` hook in specific components.
But 2 connections were created every time when visited new pages even though it had not `useChannel` hook.
I couldn't find the solution how to use only one connection for each client.

**Comment by owenpearson** [comment]
Hey @valentins666, you should get one connection for each time you call the `Ably.Realtime.Promise` constructor. For this reason we recommend calling it outside of any react components, in the top level of whichever module you're using the `AblyProvider` component. If you're still stuck, would you mind sharing some more context about where you're calling the constructor and I'll take a look

**Comment by StanislavHT** [comment]
Thank you, @owenpearson 

That was the root cause and most direct.
We could solve the problem by creating `AblyClient` within `useEffect`.

**Comment by owenpearson** [comment]
Nice, I'm glad you solved it 🙂

**Comment by valentins666** [comment]
Thank you very much for your help, It works for me.
