### ISSUE TITLE
Unique logHandler

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#156]
Passing a custom log handler to the REST or Realtime libraries configures the Logger handler to use the provided callback, see https://github.com/ably/ably-js/blob/master/common/lib/util/logger.js#L44. However, if you have two separate instances of the library with unique custom log handlers (perhaps so that each logger can output the connection ID of that client), then instancing the second library overrides the first libraries configuration as Logger is global.

I find this is quite problematic when trying to debug lots of concurrent clients.  Example:

```javascript
var client1 = new Ably.Realtime({ log: { handler: function() { console.log('client1', args) } } });
var client2 = new Ably.Realtime({ log: { handler: function() { console.log('client2', args) } } });
```

All output from both libraries will be prefixed with `client2`

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/ECO-4207) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
My expectation would be that client options should only influence client instances (whether REST or Realtime) created with those specific options. Therefore this sounds like a `bug` to me, not an `enhancement`. WDYT, @owenpearson @Peter-Maguire @mikelee638 ?

**Comment by Peter-Maguire** [comment]
@QuintinWillison I would agree that this is a bug, although I can see how it could be an enhancement as the log handler wasn't designed to work with multiple clients and therefore is working as intended.

**Comment by lawrence-forooghian** [comment]
I opened https://github.com/ably/ably-js/issues/1763 yesterday and just found out that it’s a duplicate of this 9-year-old issue! Yeah, it's definitely a bug. Fixing it.
