### ISSUE TITLE
`realtime/auth.authbase0` test case can fail due to race condition

### ISSUE THREAD

**Issue by VeskeR** [ably/ably-js#1578]
`authbase0` test case in `realtime/auth` can fail with the next error:

```
  1) realtime/auth
       authbase0:
     AssertionError: Verify token issued: expected false to be truthy
      at /mnt/c/Users/Andrey/dev/ably/ably-js/test/realtime/auth.test.js:76:105
      at /mnt/c/Users/Andrey/dev/ably/ably-js/test/common/modules/shared_helper.js:70:9
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The error is caused by comparing `tokenDetails.issued` generated in `authbase0` using AblyRealtime with queryTime undefined (defaults to false) with `currentTime` from setup function generated via calling `AblyRest.time()` with `queryTime: true`.

Due to different `queryTime` setting used, if the local offset from server is large enough (set in `BaseClient.serverTimeOffset`) or the test case runs fast enough, we can retrieve a new token in `authbase0` before time offset ends, thus causing `tokenDetails.issued` to be less than saved `currentTime` and failing the test.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4128) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
I'm not sure I understand the issue that you're describing here. Both of the time values compared by the failing assertion have come from a clock on an Ably server, haven't they? `currentTime` comes from the `time()` function, which makes a REST API call to Ably, and `tokenDetails` is the token generated by Ably, which populates `issuedAt` using the clock on the server. Please could let me know what I've misunderstood?

It's also possible that the issue you're seeing is related to clock skew between realtime servers (see Simon's explanation [here](https://ably-real-time.slack.com/archives/C030C5YLY/p1690316313229949?thread_ts=1690315022.372729&cid=C030C5YLY) (internal Slack thread)).

**Comment by VeskeR** [comment]
> currentTime comes from the time() function, which makes a REST API call to Ably

Correct

> tokenDetails is the token generated by Ably

Correct

> which populates issuedAt using the clock on the server

Not correct. Based on my observation, `issued` field in received token details will match `timestamp` field we passed in TokenRequest. This behavior is not described [in the spec](https://sdk.ably.com/builds/ably/specification/main/features/#TD4) for the `issued` field though, so I wonder it that's intentional.
And the `timestamp` field we pass in TokenRequest is set based on `Auth.getTimestamp()` call, which returns local time or server time if `queryTime` was passed.

This way, if the offset is big enough, this issue occurs and test fails.

**Comment by lawrence-forooghian** [comment]
Copying Slack conversation here:

Andrii: 

> it seems like we're not getting an additional clarification on https://github.com/ably/ably-js/issues/1578. given that the issue is reproducible on our end, I believe that tests like in the issue should use the same queryTime option value.
I suggest we merge the associated PR and open an explicit issue with realtime about requestToken request uses timestamp in when populating issued field for its token details response. this should be easily reproducible with a curl to show that [previously described behavior ](https://ably-real-time.slack.com/archives/CURL4U2FP/p1699383746195609?thread_ts=1699380474.969789&cid=CURL4U2FP)(from your convo with Paddy) is no longer true.

Me:

> Yeah, if it’s going to reduce the failures of that test in CI then I guess we should merge it. I’d suggest adding a comment alongside it in the code to explain why we’re doing `queryTime: true` and link to whatever Realtime issue you open.

**Comment by VeskeR** [comment]
Update on the issue (copied from commit message https://github.com/ably/ably-js/pull/1579/commits/7e71eac6878a864142fda4712e43a1ad4e49028d):

> There was an intentional change in realtime code regarding populating
`TokenDetails.issued` field based on `timestamp` field provided by the
request [1]. Starting from this change, provided `timestamp` field
can now used to set the `TokenDetails.issued` field. It is done to
"Make it easier to construct reliable tests for eg token expiry and
revocation, by controlling the timestamp we pass in."
> This does, however, mean that in order for time-sensitive tests to work
properly and avoid race conditions, we need to always either set
`queryTime: true` or set `queryTime: false`. We need to ensure that we
use the same value everywhere, so that the realtime code returns
`TokenDetails.issued` based on consistent data when we need to check it.
[1] https://github.com/ably/realtime/commit/359930d97f19d8b1f0604c1d6c1827b187759f67
