### ISSUE TITLE
clientId should be derived from Connected ProtocolMessage, TokenDetails or TokenRequest clientId

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#158]
I believe the following specs are not met by the client library.  As such, it leads to some (ugly) duplication, see https://github.com/ably/demo-mobile-phonegap-cordova/commit/29832c9a2cc9abc73cb84e7d0723a14bcd38f5af#diff-bca463ed8ccf5e2058dfe307a95e8501R108 for an example.

* http://docs.ably.io/client-lib-development-guide/features/#RSC17
* http://docs.ably.io/client-lib-development-guide/features/#RSA15
* http://docs.ably.io/client-lib-development-guide/features/#RSA7b
* http://docs.ably.io/client-lib-development-guide/features/#RSA8f
* http://docs.ably.io/client-lib-development-guide/features/#RTC4a
* http://docs.ably.io/client-lib-development-guide/features/#RTP8c

**Comment by SimonWoolf** [comment]
As of latest additions to https://github.com/ably/ably-js/pull/145, ably-js should now conform to these.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/145
