### ISSUE TITLE
Publicly document v2 platform compatibility and update CI accordingly

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1605]
Now that we've decided on our platform compatibility guarantees for v2 (in https://github.com/ably/ably-js/issues/1537), update:

* the claims we make about platform support in the README
* the `engines` field in `package.json`
* CI to run on the Node versions we claim to support
* the version of ES that we target when bundling / compiling TypeScript

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4121) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Done in https://github.com/ably/ably-js/pull/1633
