### ISSUE TITLE
Document our continued support for v1

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1606]
See @SimonWoolf’s comment [here](https://ably.atlassian.net/wiki/spaces/SDK/pages/2814017537?focusedCommentId=2865659973):

> we’ll still be supporting v1 (at least with security updates and critical bugfixes, not new features) for customers who do still want old browser support. (and should clearly document that in the readme with cdn urls etc. for v1)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4120) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Done in https://github.com/ably/ably-js/pull/1634
