### ISSUE TITLE
Can't import from 'ably/react' on v2 branch

### ISSUE THREAD

**Issue by VeskeR** [ably/ably-js#1622]
`package.json` `exports` field does not define export for 'ably/react', so we get an error when trying to import from this path in real application:
![](https://github.com/ably/ably-js/assets/9639405/e8089af6-c027-4b2e-8615-bc3ef5762c32)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4114) by [Unito](https://www.unito.io)

**Comment by danielrhodes** [comment]
This is because they haven't properly implemented or exported their types correctly.

**Comment by VeskeR** [comment]
Fixed in https://github.com/ably/ably-js/pull/1625
