### ISSUE TITLE
Lack of the close method in REST API

### ISSUE THREAD

**Issue by EmilBuszylo** [ably/ably-js#1626]
I was going to use your REST API following the instructions from this repo, but my client doesn't have a close method.
I created the ably client in the standard way:

`const client = new Ably.Rest.Promise({
  key: process.env.ABLY_API_KEY,
});`

and then I got the information `Property  close  does not exist on type  RestPromise` 
I checked TypeScript types and It was right, the close method doesn't exist in RestPromise and RestBase types. I see it in RealtimeBase only. 
If the close method invoking is not necessary in RES API case it would be great to update the documentation.

![Screenshot from 2024-02-16 15-54-33](https://github.com/ably/ably-js/assets/20420991/4b6a3f06-6c2f-4268-be8f-5c9c70021ce9)

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4112) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Hello @EmilBuszylo ! You are correct that calling `close()` method on Ably Rest API client is not necessary (and indeed not possible) and the documentation had an incorrect piece of code.
Incorrect example has been removed from README in our ably-js v2 release. Thank you for reporting this!
