### ISSUE TITLE
Request method does not support empty response bodies

### ISSUE THREAD

**Issue by AndyTWF** [ably/ably-js#1628]
The `request` method on the Rest client can't handle empty response bodies (e.g. 204 No Content) - it tries to decode them and results in a JSON error because there's nothing to decode.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4630) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
duplicate: https://github.com/ably/ably-js/issues/676
