### ISSUE TITLE
ably-js-browsers failing in mobile safari

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#164]
eg latest run https://ci.ably.io/job/ably-js-browsers-min/326/consoleText:
```
IE 11.0.0 (Windows 10 0.0.0): Executed 202 of 202 SUCCESS
Chrome 42.0.2311 (Windows 8.1 0.0.0): Executed 207 of 207 SUCCESS 
Mobile Safari 8.0.0 (iOS 8.4.0): Executed 12 of 207 (9 FAILED) ERROR
```
@mattheworiordan was looking into this (since he has a mac & iphone so can debug locally) -- just making an issue so it doesn't drop off our radar.

**Comment by mattheworiordan** [comment]
Thanks @SimonWoolf. I will look at the issues once the XHR streaming issue in iOS is fixed by @paddybyers

**Comment by mattheworiordan** [comment]
Reminder that we must add Safari to browsers min, not just Mobile Safari, see https://github.com/ably/ably-js/blob/master/test/bin/ci-saucelabs-min.sh

**Comment by SimonWoolf** [comment]
`publishVariations` still consistently failing on mobile safari only (both 8.0 and 9.0) - https://ci.ably.io/job/ably-js-browsers-all/147/consoleText

**Comment by mattheworiordan** [comment]
@SimonWoolf did we add normal Safari to the browser mix for min, and do you know if that passes?

**Comment by SimonWoolf** [comment]
Normal safari isn't there, no.

**Comment by SimonWoolf** [comment]
Have now added desktop safari to browsers-all.

Annoyingly, testing just publishVariations on saucelabs on mobile safari result in [it passing successfully](https://ci.ably.io/job/ably-js-browsers-min/432/console), though it still fails when run as part of browsers-min. Have added some logging as well.

@mattheworiordan any progress with trying it on an actual iphone?

**Comment by SimonWoolf** [comment]
Closed by https://github.com/ably/ably-js/pull/215
