### ISSUE TITLE
HTTP requests ignore `tls: false` attribute

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#166]
Initialising a Realtime library with `tls: false` connects to a realtime end point correctly not using TLS, however when performing the following I found the client library attempted to connect over TLS:

* Implicit token request for auth
* History requests on a channel

We need to ensure that `tls: false` is respected for REST operations performed by a Realtime client and add suitable test coverage.

@SimonWoolf mind taking a look?

**Comment by SimonWoolf** [comment]
TBH I'd always assumed that was deliberate - `rest.baseUri` has always ignored the tls option. I've done a PR to change it https://github.com/ably/ably-js/pull/167, but will wait for @paddybyers to weigh in on whether there's a reason it was done that way before merging
