### ISSUE TITLE
add publish to the useChannel hook

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-js#1665]
Using publish method you can send messages to the derived channels (channels with filter qualifier, without attaching to the channel or using other workarounds)

updated docs https://github.com/ably/ably-js/pull/1654

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4666) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Done in https://github.com/ably/ably-js/pull/1658
