### ISSUE TITLE
Do another v1 release before v2 release

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-js#1672]
So that we can add deprecation warnings for the stuff that v2 will remove (see https://github.com/ably/ably-js/issues/1666).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4674) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
https://github.com/ably/ably-js/pull/1708
