### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#171]
* [ ] Check that the README.md is complete with installation instructions
* [ ] Ensure all example code is up to date
* [ ] Ensure version number in README is up to date, and automatically updated in future version bumps
* [ ] Ensure repo is distributed to package manager

**Comment by paddybyers** [comment]
Include a comment re the closure compiler installation.

**Comment by SimonWoolf** [comment]
Most of this I've now done at various points: installation instructions in e3d82ec2, version number autoupdating in a49308ef, grunt:deploy task in 38ea16a0 (with CDN deployment much-improved by Matt in 2d0dbfa0).

Just done a few more tweaks to the readme: https://github.com/ably/ably-js/compare/readme-tweaks. Added a few more methods and explanations, added a note on the closure compiler, updated paginatedResults api, and removed a couple of things for simplicity (eg the list of what attributes a tokenRequest has). It's still far from a complete api documentation, but I guess it's not supposed to be, that's what the API documentation is for. I guess the readme should be the most common methods?

**Comment by mattheworiordan** [comment]
Have reviewed @SimonWoolf, looks very good to me

**Comment by SimonWoolf** [comment]
Closed by https://github.com/ably/ably-js/pull/232 (and previously: e3d82ec, a49308e, 38ea16a, 2d0dbfa)
