### ISSUE TITLE
Filter integration rules by message name

### ISSUE THREAD

**Issue by Dajust** [ably/ably-js#1724]
I think we should have a way to filter what messages in a channel should go through integration. 

E.g

Suppose we have a `MyChannel`channel where I receive `chat-message` messages, and also `new-follower` messages. Now assume we setup Ably Queue or some other integration for `MyChannel` to help save `chat-message` to a db or something, all `new-follower` messages will also arrive in the Queue, which is not ideal. I know we could use the `skipRule` to skip a specific message, but it would be great to specify in the ably rule the specific message-name the integration applies.

Is there a reason ably doesn't support this?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4728) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Hello @Dajust !
I've reached out to the team to get more information on this, and I will get back to you as soon as I have more information about filtering for Integration Rules.

**Comment by VeskeR** [comment]
Hey @Dajust !

Currently, we don't offer anything that would allow Integration Rules to pattern match against anything in the message, such as `name` or `extras.headers`. As you correctly found out, you can use `skipRule` for a message to skip specific Integration Rules or all of them. Additionally, you can also specify a channel filter for a particular rule when setting it up.

As for the technical reasons behind this decision, at the time `skipRule` was added, we didn't explore the possibility of pattern matching within messages for integration rules. It wasn't a consideration or priority at that time.

We'll certainly keep track of the interest in this feature, and if more customers express similar needs, we'll reassess its feasibility and prioritize accordingly.

**Comment by VeskeR** [comment]
Closing this as answered.
