### ISSUE TITLE
Critical dependency: the request of a dependency is an expression - next@14.1.3 app router

### ISSUE THREAD

**Issue by 404nnotfoundddd** [ably/ably-js#1727]
**Versions:**

ably: 2.0.1
next: 14.1.3
react: 18.2.0,
react-dom: 18.2.0

I solved bufferutil and utf-8-validate warnings by adding this config to webpack config:

```
 config.externals.push({
      'utf-8-validate': 'commonjs utf-8-validate',
      bufferutil: 'commonjs bufferutil',
    }); 
```

But i can't solve these warnings:

```
⚠ ./node_modules/ably/build/ably-node.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/ably/build/ably-node.js
./src/app/api/ably/auth/token/route.ts
```

**Expected behavior**

I shouldn't have received this warning

**Comment by VeskeR** [comment]
Hi @404nnotfoundddd , this should be caused by the same Next.js App Router behavior as in https://github.com/ably/ably-js/issues/1699#issuecomment-2022702584:

> The issue is coming from the fact that when using App Router specifically (not Pages, this issue is not reproducible when using Pages) dependencies used inside Server Components and Route Handlers will automatically be bundled by Next.js. This causes issues with some packages, usually the ones that have complex require statements

The suggested solution is to add the next line to your `next.config.js` file:

```javascript
const nextConfig = {
  // ...
  experimental: {
    serverComponentsExternalPackages: ['ably'],
  },
};
```

You can read more in our [README section](https://github.com/ably/ably-js?tab=readme-ov-file#nextjs-with-app-router-and-turbopack).

Please let me know if thix fixes the problem for you!

**Comment by 404nnotfoundddd** [comment]
> Hi @404nnotfoundddd , this should be caused by the same Next.js App Router behavior as in [#1699 (comment)](https://github.com/ably/ably-js/issues/1699#issuecomment-2022702584):
> 
> > The issue is coming from the fact that when using App Router specifically (not Pages, this issue is not reproducible when using Pages) dependencies used inside Server Components and Route Handlers will automatically be bundled by Next.js. This causes issues with some packages, usually the ones that have complex require statements
> 
> The suggested solution is to add the next line to your `next.config.js` file:
> 
> ```js
> const nextConfig = {
>   // ...
>   experimental: {
>     serverComponentsExternalPackages: ['ably'],
>   },
> };
> ```
> 
> You can read more in our [README section](https://github.com/ably/ably-js?tab=readme-ov-file#nextjs-with-app-router-and-turbopack).
> 
> Please let me know if this fixes the problem for you!

I added the code you said to config my problem is solved thanks
