### ISSUE TITLE
Invalid accessToken in request using history in react native

### ISSUE THREAD

**Issue by mclark-ably** [ably/ably-js#1730]
Description:
When using Ably token authentication in ably-js v2 in react native and calling history the request fails with an error
`Invalid accessToken in request`. This is true whether an ably token or tokenRequest is returned to the client

Steps to reproduce:

1. Instantiate an ably client in react native (tested with "react-native": "0.73.6" and expo": "^50.0.15") using authUrl or authCallback client options which returns an Ably token to the client
2. Make a call to history on a channel

Expected behaviour:
No error and history response is returned to the client

Actual behaviour:
The bearer token in the authorization request header is partly corrupt and is refused by the ably REST API
![image](https://github.com/ably/ably-js/assets/104007582/de84a83e-81cc-4cca-a99e-2a8e5825659b)

Workaround: 

1. Downgrade to 1.2.50 where issue is not present
2. Use JWT authentication https://ably.com/docs/auth/token?lang=javascript#standard

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4737) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
Sorry @VeskeR, didn't mean to assign this to me. Have assigned it back to you.

**Comment by VeskeR** [comment]
Hi @mclark-ably !
This issue has been fixed in [2.0.4](https://github.com/ably/ably-js/releases/tag/2.0.4) release of ably-js. Thank you for reporting this problem!
