### ISSUE TITLE
Update docs about using Ably in Chrome Extension 

### ISSUE THREAD

**Issue by ttypic** [ably/ably-js#1739]
We mentioned some unnecessary workarounds to use Ably in Chrome extensions. However, starting from Chrome 116, nothing needs to be done, and Ably works with Chrome extensions out-of-the-box.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4749) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
More context in internal slack thread: https://ably-real-time.slack.com/archives/C030C5YLY/p1702996856568239
