### ISSUE TITLE
Npm module ably-js does not exist

### ISSUE THREAD

**Issue by genediazjr** [ably/ably-js#174]
https://www.npmjs.com/package/ably-js

There exists an ably npm module https://www.npmjs.com/package/ably

Is it the same? I am having problems installing it.

**Comment by SimonWoolf** [comment]
Yes, https://www.npmjs.com/package/ably is the right package. Looks like the readme is wrong, I'll get that changed.

However, looks like the one on npm is pretty out of date -- I'll upload the latest version to see if that fixes your install issues. Will post again when I've done that.

**Comment by SimonWoolf** [comment]
I've uploaded the latest version to npm.

If `npm install ably` still gives you issues, could you please post the error message you get? Thanks.
