### ISSUE TITLE
ErrorInfos that bubble up to the console don't get displayed in a useful way in firefox

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#179]
In chrome:

```
channel.publish("foo", 1)
ably.js:4604 Uncaught ErrorInfo {message: "Data type is unsupported", code: 40013, statusCode: 400}
```

In firefox:

```
channel.publish("foo", 1)
[object Object]
```

Tried making ErrorInfo inherit from Error to see if that fixes it (both the ably-js way and the suggested by [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)), but no difference. Not sure why it isn't just calling `toString`.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-546) by [Unito](https://www.unito.io/learn-more)

**Comment by paddybyers** [comment]
Any suggestions?

**Comment by owenpearson** [comment]
Closing this now - Doesn't happen on the latest Firefox and probably hasn't done for a while now.
