### ISSUE TITLE
Correct Typings for AblyProvider in React

### ISSUE THREAD

**Issue by kyeshmz** [ably/ably-js#1842]
Currently if you write something using react, you always need a client to initiate anything.
Therefore, the client in AblyProvider should be something that is required and not the current typing now

```
interface AblyProviderProps {
    children?: React.ReactNode | React.ReactNode[] | null;
    client?: Ably.RealtimeClient;
    ablyId?: string;
}
```

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4910) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Hi @kyeshmz !
Thank you for bringing this to our attention. It seems to be a leftover from when our reach hooks would automatically create a client. Now, you would get an error if you don't provide a client instance for `AblyProvider`, so the current typings don't really make sense. We will update them accordingly.
