### ISSUE TITLE
`FetchRequest` doesn't work with `checkConnectivity`

### ISSUE THREAD

**Issue by michalzaq12** [ably/ably-js#1843]
Ably ver: 2.3.1

`FetchRequest` doesn't work with `checkConnectivity`.

No random query parameter is added to `connectivityCheckUrl`, so any request to `connectivityCheckUrl` is returned from the browser cache.
`XHRRequest` works properly.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4913) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
@michalzaq12 thanks for raising the issue! 
Currently, we only check for active internet connection when existing connection fails. Can you confirm if this is causing issue for you in some way ?

**Comment by VeskeR** [comment]
Hi @michalzaq12 !
We were able to reproduce the issue locally, and we can see the bug in the code for FetchRequest. We're going to fix this as soon as possible.

**Comment by VeskeR** [comment]
This has been fixed in [ably-js 2.3.2](https://github.com/ably/ably-js/releases/tag/2.3.2) release. Thank you for reporting this issue!
