### ISSUE TITLE
Add `wsConnectivityUrl` client option

### ISSUE THREAD

**Issue by emptyhammond** [ably/ably-js#1850]
It's not currently possible to set a non default value for the `wsConnectivityUrl` in client options.

Clients may need to set `wsConnectivityUrl` to a non-default value for a variety of reasons and this should be available as a client options parameter (as per `connectivityCheckUrl` for example).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4941) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Added in [2.4.0 release](https://github.com/ably/ably-js/releases/tag/2.4.0)
