### ISSUE TITLE
Provide auth token from React prop

### ISSUE THREAD

**Issue by ianb-pomelo** [ably/ably-js#1869]
We manage refreshing our auth tokens manually and have them available in React state/context. However, AFAICT there isn't an easy way to always have the Ably Realtime client use a react state value without re-instantiating the client, creating a new connection. Is there a way or can I request a feature to allow either manually update the token of a client or (more preferable) be able to provide a token as a prop to the `AblyProvider` for the client to use?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4975) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Hi @ianb-pomelo !

I think your desired behavior can be achieved using [`authCallback`](https://ably.com/docs/auth/token?lang=javascript#auth-callback) option of the Realtime client, and storing a ref to a current token value with `useRef`, it might look something like this:
```tsx
export function Component({ token }) {
  const tokenRef = useRef(token);
  useEffect(() => {
    tokenRef.current = token;
  }, [token]);

  // use authCallback in your client options instead of passing a token directly
  const client = new Ably.Realtime({ authCallback: () => tokenRef.current });

  ...
}
```

**Comment by ianb-pomelo** [comment]
That does work! Thank you!
