### ISSUE TITLE
Possible enhancement: Capybara / QT-webkit support 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#19]
Whilst running the website test suite against the home page demo, I continued to use the default capybara-webkit driver which is based on QT Webkit.  The tests failed every time, however when I changed to PhantomJS it worked.  We may want to consider reviewing what the issue is with QT Webkit for other people using this in their CI environments.

**Comment by paddybyers** [comment]
PhantomJS is also based on QT webkit.

Any log/clue as to failure?

**Comment by mattheworiordan** [comment]
No, sorry, there was very little info.  I will need to figure out a better way to get debugging info before I provide more detail.

**Comment by mattheworiordan** [comment]
This is low priority, but it would be good to get this working so that people can use Ably in CI

**Comment by funkyboy** [comment]
@SimonWoolf @mattheworiordan Closing this. I think it's been superseded by SauceLab tests, which will be superseded by BrowserLab tests.
