### ISSUE TITLE
Source maps should be generated and published to our CDN and NPM

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#191]
Source maps can be generated on `npm run build` by setting the webpack [devtool configuration option](https://webpack.js.org/configuration/devtool/).

The source code should be published as well so that users can jump to the source of an error from a stack trace.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-276) by [Unito](https://www.unito.io)

**Comment by alamaral** [comment]
I'm still consistently seeing this issue in my product. Here is the only place the cdn is referenced and it has a version:

<script src="https://cdn.ably.com/lib/ably.min-1.js"></script>
One problem may be that ably.min-1.js still has the reference to //# sourceMappingURL=ably.min.js.map as the last line, and that might be what's failing. I also tried the ably.min-1.2.js file but that reference is still there, and it gives the same error.

I can find the map file for the -1 version: https://cdn.ably.com/lib/ably.min-1.js.map, and the -1.2 version: https://cdn.ably.com/lib/ably.min-1.2.js.map but it looks like the js files are still incorrectly referencing the unversioned map file.
Also, there is a file https://cdn.ably.com/lib/ably.min-1.1.js available, but no https://cdn.ably.com/lib/ably.min-1.1.js.map (or the permissions aren't correct as it returns an access denied error).
