### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#20]
@paddybyers I am a bit confused why http://jsbin.com/vuvozisape/1/edit?js,console,output is not working.

Seemingly it will only connect when using the format `Ably.Realtime({ key: "key" })`, and all other key & token formats fail for different reasons.

I also thought we had changed our libraries to support the use of a a key or token string in place of the constructor options which too doesn't seem to be working.

Can we ensure we add test coverage to this once resolved?

**Comment by paddybyers** [comment]
This is fixed:
https://github.com/ably/ably-js/commit/2ad36b1025e45a85092629791af1b9961a7a232f

we support

    Realtime({key: <key>})
    Realtime({authToken: <token>})
    Realtime(<key>)
    Realtime(<token>)

I've added tests for the string-only cases for realtime and rest

**Comment by mattheworiordan** [comment]
No tests to prevent a regression?

**Comment by mattheworiordan** [comment]
Also, is this deployed so I can retry the JSBin?

**Comment by paddybyers** [comment]
> No tests to prevent a regression?

I added tests, as stated above

**Comment by paddybyers** [comment]
> Also, is this deployed so I can retry the JSBin?

Not  yet

**Comment by mattheworiordan** [comment]
Can't see any tests in the commit you sent? Given 3 out of 4 were failing, should we not add coverage to all?  Can you deploy please so that we can test this + the other auth issue in production and then in CI for the web server?

**Comment by paddybyers** [comment]
> Can't see any tests in the commit you sent?

https://github.com/ably/ably-js/commit/79848f8cdbde364e5c32792b8d91ce2a8469dc63

> Given 3 out of 4 were failing, should we not add coverage to all?

2 were failing (tests above), 1 was being used incorrectly (`token: xx` instead of `authToken: xx`).

**Comment by mattheworiordan** [comment]
Ah, great, shout when this and other fixes are deployed so that we can test.

**Comment by mattheworiordan** [comment]
Unfortunately there is another bug, if you pass in an API key without the form `key: 'key'` then the client tries to connect over HTTP.  See https://jsbin.ably.io/ogizus/3/edit which works, and https://jsbin.ably.io/ogizus/2/edit which fails.

**Comment by paddybyers** [comment]
This should fix it: https://github.com/ably/ably-js/commit/c45853685fb2ec50e9e6dfe4ef0029c570f57157

**Comment by mattheworiordan** [comment]
I see that's tagged 0.7.5, is that deployed?  
Hate to be a stickler, but no test to prevent a regression?

**Comment by paddybyers** [comment]
> I see that's tagged 0.7.5, is that deployed?

Yes

> Hate to be a stickler, but no test to prevent a regression?

https://github.com/ably/ably-js/commit/e1f0e893b41f1e8c7ad571b17069f68d444c27be

**Comment by paddybyers** [comment]
Resolved

**Comment by mattheworiordan** [comment]
Thanks
