### ISSUE TITLE
Possible issue with serverTimeOffset calculation for people in other timezones

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#205]
Reported by alexg, who was having issues with `auth_token_expires`. Have given it to alexg to debug, as the serverTimeOffset mechanism should be fairly self-contained. Slack transcript:

```
...
Ably: Connection.connect(): 
Ably: Auth.requestToken(): Need a new token, but authOptions does not include any way to request one
Ably: ConnectionManager.connectImpl(): Connection attempt failed with error; err = [ErrorInfo: Need a new token, but authOptions does not include any way to request one; statusCode=401; code=40101]
Ably: Connection.close(): connectionKey = undefined
✖ auth_token_expires
Assertion Message: connection to server failed
AssertionError: connection to server failed
    at Object.ok (/home/alexg/workspace/ably/ably-js/node_modules/nodeunit/lib/types.js:83:39)
    at Object.<anonymous> (/home/alexg/workspace/ably/ably-js/spec/common/modules/shared_helper.js:26:11)
    at callListener (/home/alexg/workspace/ably/ably-js/common/lib/util/eventemitter.js:13:18)
    at Connection.EventEmitter.emit (/home/alexg/workspace/ably/ably-js/common/lib/util/eventemitter.js:131:5)
    at /home/alexg/workspace/ably/ably-js/common/lib/client/connection.js:19:10
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
Error: Expected 4 assertions, 1 ran
    at Object.test.done (/home/alexg/workspace/ably/ably-js/node_modules/nodeunit/lib/types.js:121:25)
    at Object.test.done (/home/alexg/workspace/ably/ably-js/spec/common/modules/shared_helper.js:96:22)
    at Object.<anonymous> (/home/alexg/workspace/ably/ably-js/spec/common/modules/shared_helper.js:27:11)
    at callListener (/home/alexg/workspace/ably/ably-js/common/lib/util/eventemitter.js:13:18)
    at Connection.EventEmitter.emit (/home/alexg/workspace/ably/ably-js/common/lib/util/eventemitter.js:131:5)
    at /home/alexg/workspace/ably/ably-js/common/lib/client/connection.js:19:10
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
Ably: Connection.connect(): 
Ably: ConnectionManager.chooseTransport(): 
Ably: ConnectionManager.chooseTransport(): upgrading ... connectionKey = 63b7a!YrmoAXinrSOTHAJb-2dbe63b7a
Ably: Transport.onProtocolMessage(): error; connectionKey = 63b7a!YrmoAXinrSOTHAJb-2dbe63b7a; err = {"message":"Key/token status changed (expire)","code":40140,"statusCode":401}
Ably: ConnectionManager.chooseTransport(): 
Ably: ConnectionManager.chooseTransport(): upgrading ... connectionKey = 63b7a!YrmoAXinrSOTHAJb-2dc163b7a
Ably: Connection.close(): connectionKey = 63b7a!YrmoAXinrSOTHAJb-2dc163b7a
✔ auth_tokenDetails_expiry_with_authcallback
...

simon
11:53
ok, so it seems like the token's expiring before it successfully connects even once.
11:53
which is odd, because it has 5 seconds, which should be more than long enough
11:54
could you change the
ttl on that same line from 5000 to 10000 and see if that helps?
11:54
sorry, on line 391 rather
alexg
11:55 AM ok but Im not on dialup :stuck_out_tongue: I do have a DSL line :simple_smile:
11:55
it fails again but differently
11:55
hang on
11:56
no actually it's the same errors
simon
11:59 AM ok. could you please run this in a console, and paste the output here:
curl rest.ably.io/time && node -e "console.log(Date.now())"
alexg
12:00 PM seems like that's it
alexg
12:00 PM
$ curl rest.ably.io/time && node -e "console.log(Date.now())"
[
    1453377584965
]1453377599888
alexg
12:00 PM timezone diff
12:01
where are you located? seems like 4 hour difference. I'm at gmt+2
alexg
12:01 PM
$ bc
1453377599888-1453377584965
14923
14923/(60*60)
4

simon
12:02 PM there should be a mechanism to offset that (serverTimeOffset), but I guess it isn't working.
12:02
(I'm GMT, as are the servers)
alexg
12:02 PM can you use UTC?
simon
12:03 PM unix time should be UTC by definition
12:07
ok, so this is probs a good issue for you to get familiar with debugging ably-js
- the offset between your machine time and the server time  is set in common/lib/client/rest.js on line 101, as an attribute of the rest client
- in common/lib/client/auth.js at line 155, the client checks the expiry time on the token, using the getTimestamp() helper (in the same file), which should subtract the offset.something in this is going wrong. good luck :simple_smile:
alexg
12:08 PM nice will have a look
```

Note: `auth_token_expires` is the only token expiry test that intialises the lib with a tokenDetails, which means it's the only one where ably-js is does the expiry calculation itself.

Fairly sure unix time should be UTC anyway, so his machine's wrong - but the serverTimeOffset mechanism should mean everything still works even with a 4 hour offset.

**Comment by paddybyers** [comment]
`Date.now()` should always return millis since the epoch irrespective of the TZ on the machine. There shoulld never be an offset due to TZ; only an incorrectly set clock.

**Comment by SimonWoolf** [comment]
Agreed (see last paragraph). But the serverTimeOffset mechanism should mean everything still works, surely.

(If not, then given we can't fix everyone's machines, we should probably remove the in-client expiry check ad just rely on realtime telling you you've expired, now we have that working reliably)

**Comment by paddybyers** [comment]
> But the serverTimeOffset mechanism should mean everything still works, surely.

Yes. I'm just saying that a TZ difference alone should not trigger it.

**Comment by alex-georgiou** [comment]
That's correct, it's not a timezone issue as I initially thought.

The if statement that checks for expiry does not go into the else block, so this is not an issue with the token appearing to be expired:

			if(token.expires === undefined || (token.expires > this.getTimestamp())) {
			...
			} else {
				/* expired, so remove */
			...
			}

Something else is wrong here. Digging...

**Comment by alex-georgiou** [comment]
Taking a break. Will pick this up again a little later.

**Comment by alex-georgiou** [comment]
Looking at it again this morning, this is what I found so far:

In `Rest.prototype.time()`, this line stores an offset correctly on the rest object

`self.serverTimeOffset = (time - Date.now());`

but in `Auth.getTimestamp()` the value of `this.rest.serverTimeOffset` is null.

This causes `getTimestamp()` to be effectively the same as `Date.now()`.

This causes the check for an expired token to fail if the local clock is ahead of the server clock by more than the token's TTL:
`if(token.expires === undefined || (token.expires > this.getTimestamp())) {`

and execution falls through to the next code block which tries to get a new token causing the test to fail.

Need to find out why `this.rest.serverTimeOffset`is null.

**Comment by mattheworiordan** [comment]
Ok, thanks for looking into it @alex-georgiou.  Can we leave it with you to find a fix?

**Comment by alex-georgiou** [comment]
Yes @mattheworiordan I will find a fix, I think I'm close to figuring it out.

The `serverTimeOffset` is set when `rest.time()` is called, so I'm trying to do the same call in the `auth_token_expires` test as is done in the `setupauth` test and continue with the rest of the test in time()'s callback.

But right now I'm getting a 500 error from the server when running the auth tests, on a clean master branch. Could it be that something is broken on your end or maybe I've hit some max connection limit?

**Comment by paddybyers** [comment]
> right now I'm getting a 500 error from the server

There must be some other detail in the error response from the server?

**Comment by alex-georgiou** [comment]
Yes there was:
```
✖ setupauth

Assertion Message: Could not set up Test App: "Invalid HTTP request: {\n\t\"error\": {\n\t\t\"statusCode\": 500,\n\t\t\"code\": -5,\n\t\t\"message\": \"Client channel:0rMZyQ:persisted:presence_fixtures unavailable (timer expired)\",\n\t\t\"serverId\": \"frontend.1782.eu-central-1-A.i-2348859e\"\n\t}\n}; statusCode = 500"
AssertionError: Could not set up Test App: "Invalid HTTP request: {\n\t\"error\": {\n\t\t\"statusCode\": 500,\n\t\t\"code\": -5,\n\t\t\"message\": \"Client channel:0rMZyQ:persisted:presence_fixtures unavailable (timer expired)\",\n\t\t\"serverId\": \"frontend.1782.eu-central-1-A.i-2348859e\"\n\t}\n}; statusCode = 500"
```

Now I get timeouts.

**Comment by paddybyers** [comment]
OK, that's our problem and not your problem. I'll reset things and let you know when you try again.

**Comment by paddybyers** [comment]
I've redeployed sandbox if you want to try again

**Comment by alex-georgiou** [comment]
@paddybyers Thanks! Will do.

**Comment by alex-georgiou** [comment]
Thinking out loud:

If `queryTime` is not set in the auth params, then `rest.time()` is never called and the offset is not calculated and remains `null`.
So, in the `auth_token_expires` test, I change
`rest.auth.requestToken({ ttl: 5000 }, null, function(err, tokenDetails) {`
to
`rest.auth.requestToken({ ttl: 5000 }, { queryTime: true }, function(err, tokenDetails) {`
which forces the REST client to set `offsetServerTime`. 


In the same test, up to the line that defines a callback for the connection
`clientRealtime.connection.once('connected', function() {`
the field `rest.offsetServerTime` is set correctly to our offset in millis.

After this, when we enter `auth.authorise()`, `this.rest.serverTimeOffset` is set to null. _I'm still having trouble debugging this._ Stack trace when entering `auth.authorise()` is:
```
    at Auth.authorise (/home/alexg/workspace/ably/ably-js/common/lib/client/auth.js:143:17)
    at ConnectionManager.connectImpl (/home/alexg/workspace/ably/ably-js/common/lib/transport/connectionmanager.js:798:9)
    at /home/alexg/workspace/ably/ably-js/common/lib/transport/connectionmanager.js:729:37
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```
The effect of `rest.serverTimeOffset==null` is that `auth.getTimestamp() == Date.now()` which is wrong.

**Comment by SimonWoolf** [comment]
> After this, when we enter auth.authorise(), this.rest.serverTimeOffset is set to null.

Look more closely at the test itself: are you sure the client library calling `authorise` the same instance as the one you're passing `{queryTime: true}` to?

> So, in the auth_token_expires test, I change... `{ queryTime: true }`

Consider ways that fix the problem in general, rather than just for that test. For example, perhaps some logic in getTimestamp that would fix the problem, but still not require a time query for *every* token request (which is what `queryTime: true` would do)...?
