### ISSUE TITLE
Token issue potential bug

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#208]
We have identified a situation where a client library could, in theory, end in an endless loop of trying to reissue tokens and reattempt requests.  We've addressed this now in the spec at https://github.com/ably/docs/commit/b628023b83aca480464d55e4260e21ee20690d7a.

This library needs to be updated accordingly.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-277) by [Unito](https://www.unito.io/learn-more)

**Comment by mattheworiordan** [comment]
@SimonWoolf is this resolved now in 0.9?

**Comment by SimonWoolf** [comment]
Unfortunately not yet

**Comment by owenpearson** [comment]
Resolved by https://github.com/ably/ably-js/commit/b28cfd51273a890ae0fb1122f6b46e6d1db6ec99
