### ISSUE TITLE
Multiple host mechanism to work around max-concurrent-connections limits?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#211]
One of the problems I ran into with IE8 support is that: it turns out that when on connections that IE thinks aren't broadband (which I guess must sometimes be triggered running the tests in a vm..? who knows what heuristic they use), IE8 limits you to two max concurrent connections to the same host. Which is enough for one stable comet transport (one connection for recv, one for send and others). As soon as you add a second comet transport to the mix, everything becomes unreliable and flaky -- you can't rely on anything happening in bounded time.

The symptoms of this are annoyingly ambiguous -- the IE network tab seems to show 'not yet sent because of this limit' and 'server not yet replied' in the same way -- as "(pending)" -- so by appearances it seems like realtime just took 15 seconds to respond to a /send request. When actually AFAICT the send request was just waiting for 15s until a recv request gets a heartbeat and finishes, at which point it can jump in and actually execute.

This is a problem (a) for our tests, which on IE8 will be occasionally flaky and unreliable, and (b) for customers who for whatever reason have two ably connections happening at once who have users on narrowband connections on IE8.

The only test that was consistently failing because of this was the resume test, which [I've rewritten to do things more serially and only use one realtime connection](https://github.com/ably/ably-js/commit/0aa13154a78c4d271d08855080b06b76fd8032fb).

Matt suggests:

> Why not put each connection on  unique endpoint?
> So instead of sandbox-rest.ably.io, we can set up [1-9]-sandbox-rest.ably.io, and you have a global index that keeps increasing and then simply % 10
> If we have a helper to create connections, it could handle that automatically
> Setting up the DNS is piece of piss too, maybe just make it 20 unique domains to be safe?
> WDYT?

I thought it was a good idea, but that if we're going to put in that work, we could consider doing a mechanism that works in prod too (for customers who instantiate two realtime connections), rather than just for our tests.

In any case, decided it was outside the scope of https://github.com/ably/ably-js/pull/210 which at least gets one-connection-at-a-time working reliably in ie8, and the tests seem to mostly be okish. So adding this as a low-priority feature request to consider for the future.

**Comment by paddybyers** [comment]
This does increase the risk that 1.rest.ably.io resolves to a different region from 2.rest.ably.io.

Nonetheless, I agree if we were going to do it we've do it for production. I think it would be implemented within the comet transport or the request primitive, rather than something outside that governs the host fed into the library `ClientOptions`.

**Comment by mattheworiordan** [comment]
> This does increase the risk that 1.rest.ably.io resolves to a different region from 2.rest.ably.io.

Yes, marginally, but they would simply be CNAME records to the same rest endpoint.  Also, I think the logic should be that a client library, when instanced, will choose a host name and continue to use that hostname moving forwards so jumping regions due to DNS resolution becomes no more risk than using the default domain.

**Comment by SimonWoolf** [comment]
I don't think we're going to sink lots of engineering effort into improving IE8 any time soon, so closing this. (cc @funkyboy so you're aware of possible issues in IE8 testing)
