### ISSUE TITLE
Sparse stat support 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#22]
Can you confirm if JSON values will default to zero now that we will roll out sparse stat support?

Whilst sparse stats for efficiency between client & server is probably the right option, I am not sure the client libraries should be providing empty objects to stat queries so do prefer either a complete JSON object with zero values for each stat, or a more typed approach like we have done in https://github.com/ably/ably-java/blob/master/src/io/ably/types/Stats.java or https://github.com/ably/ably-ruby/commit/cec03499da3b349bd6dfabb1f01c947e960bc5dd

**Comment by paddybyers** [comment]
> a more typed approach

See: https://github.com/ably/ably-js/commit/16c1515

**Comment by paddybyers** [comment]
Resolved

**Comment by mattheworiordan** [comment]
Nice, this looks great.
