### ISSUE TITLE
Nodeunit tests in the browser

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#23]
I was just about to look into extending our browser & device coverage for this library, and unfortunately hit a few snags.

I could not get the tests to run at all at first, managed to fix it with https://github.com/ably/ably-js/commit/9f1db792def9449b41104209728bac0aec6ba1ef.

Now when run `grunt test:webserver` to spin up a browser that can run the Nodeunit tests, only a small subset of the test are running, namely:

![voila_capture 2015-03-31_12-16-55_am](https://cloud.githubusercontent.com/assets/43789/6909151/417afe2e-d73b-11e4-9353-2cbfad635e4e.png)

`grunt karma` seems to also be effected running only this subset.

Do you know what has caused this issue?  If not, I will have to dive in, but was not expecting to have to do that.

**Comment by paddybyers** [comment]
> Do you know what has caused this issue?

Sorry: https://github.com/ably/ably-js/commit/6cbb0f1da4e7321983ce9721cb08986a2ef81d65

**Comment by paddybyers** [comment]
Resolved.
