### ISSUE TITLE
Improve test coverage for poor connectivity fixes

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#230]
See https://github.com/ably/ably-js/pull/218

There are some suggestions in regards to additional test coverage for the fixes in that PR.

**Comment by SimonWoolf** [comment]
Added a couple tests along those lines in https://github.com/ably/ably-js/pull/292/commits/ba72263f634d02b0e0461d9be711d397db78bf0a , one for a comet timeout of an attach, one for a comet timeout of a publish, both stalling an upgrade.
