### ISSUE TITLE
Use fork of nodeunit that outputs the errors 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#246]
See https://github.com/ably-forks/nodeunit/tree/show-errors.  When using this version, uncaught exceptions are outputted in the results and the test suite behaves as normal i.e. moving onto the next test.

Then we need to make sure the version of `nodeunit` run locally and in CI is that version.  Locally I 
added `alias npm-exec='PATH=$(npm bin):$PATH'` to my `zshrc` file and then use `npm-exec nodeunit ..`

**Comment by mattheworiordan** [comment]
@SimonWoolf is this not done?  I thought we made a change to output errors recently?

**Comment by SimonWoolf** [comment]
haven't switched to the nodeunit fork yet, but it does now do `process.on('uncaughtException', function(err) { console.error(err.stack); });` - https://github.com/ably/ably-js/blob/0-9-spec/spec/common/globals/environment.js#L32-L34

**Comment by mattheworiordan** [comment]
Ok, so good enough to close?
