### ISSUE TITLE
Runtime error when publishing an invalid payload

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#248]
When publishing an integer payload, my Node.js script exited completely as opposed to simply emitting an error in the callback.

Here is some sample code:

```
publishChannel.publish('count', 123);
```

Which resulted in:

```
readline.js:924
            throw err;
            ^
[ErrorInfo: Data type is unsupported; statusCode=400; code=40013]

$
```

**Comment by SimonWoolf** [comment]
Is this a bug? I thought we'd decided a while ago that for coding errors (inc calling methods invalidly, including with invalid types) we wanted to throw an exception (to give the dev immediate feedback) - as opposed to unpredictable errors (eg a failed channel) which would be passed to the callback. Eg see discussion [here](https://github.com/ably/ably-js/commit/1b151df5558339d8b2fd80bbadd2375d9a138b4a#commitcomment-14908097)

**Comment by mattheworiordan** [comment]
I assumed, perhaps incorrectly, that that error was coming from the server given the `statusCode`.  Is that coming direct from the library?  If so, then you can close this ticket as I mistook it for a server-side error.

**Comment by SimonWoolf** [comment]
Yep, error's coming from the library - [here](https://github.com/ably/ably-js/blob/557964c32da02e7d6d46d8fdec1d27e84c1a3f48/common/lib/types/message.js#L97). (realtime has no problem with numbers as data, type validation is purely client-enforced atm)

**Comment by mattheworiordan** [comment]
Thanks, sorry for the noise

**Comment by mattheworiordan** [comment]
Actually, out of interest, what is your view on a `statusCode` being set for errors generated from the client library itself?  Given a status code is typically assumed to be an HTTP status code, do you think it would be more appropriate to not set this in the case of client-side generated errors and only use the Ably error code? @paddybyers WDYT?  Not suggesting we change it now, but interested for future reference.

**Comment by SimonWoolf** [comment]
In favour of client-set statusCodes, they allow us to abstract what errors are generated by the client and what by realtime. Eg there's been a couple times where we've added a check to the lib to make it give the same error in some situation that realtime would've given, to avoid an unnecessary round-trip. If we make client-generated different from server ones, that sort of change might break people's code

**Comment by paddybyers** [comment]
> what is your view on a statusCode being set for errors generated from the client library itself?

It also allows a certain level of generic error handling by the client - eg handing of 4xx vs 5xx - without having to know the details of specific error codes.

**Comment by mattheworiordan** [comment]
Ok all fair points, ignore me then :)
