### ISSUE TITLE
Setting default environment

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#25]
We have an issue in our staging environment that resulted in https://github.com/ably/ably-js/issues/24.  The problem is that our docs repo uses environment production by default which makes sense, see https://github.com/ably/docs/commit/74d21d1ee6a475af6fab9822ba366c4589fd0542#diff-5628feb5438d9fac128ae3d1a9a92298R114 for an example.  Whilst we could add a `environment: '{{ENVIRONMENT}}'` option to the documentation, it would make the documentation unnecessarily verbose and environment is not really something we want people to know / think about.

So what I propose is perhaps in staging to run a command such as:
```javascript
Ably.Realtime.setGlobalOption({ environment: 'sandbox' });
Ably.Rest.setGlobalOption({ environment: 'sandbox' });
```

How difficult is this to achieve?  Do you have a better solution?

**Comment by paddybyers** [comment]
See: https://github.com/ably/ably-js/commit/8b0fc28

Set a new default environment with:

    Ably.Realtime.Defaults.ENVIRONMENT = 'sandbox';

**Comment by mattheworiordan** [comment]
Could you perhaps bump the version and release so that Rafael can use this change?

**Comment by paddybyers** [comment]
It's deployed now as 0.7.6 but depends on realtime changes which are being rolled out now ....

**Comment by paddybyers** [comment]
Resolved
