### ISSUE TITLE
Should not reject presence enter if clientId is unknown

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#252]
If the client library does not know if a clientId may be determined following auth, then it should not raise an exception when performing presence actions as it has to assume that it's possible following auth a clientId will be configured, and thus, let the server handle the request if in valid.

See https://jsbin.ably.io/ivezaj/2/edit

Error:
```
ably.js:8818 Uncaught [ErrorInfo: clientId must be specified to enter a presence channel; statusCode=400; code=40012]**
```

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/issues/256
