### ISSUE TITLE
Allow >1 pending presence event

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#253]
Currently, `realtimePresence` assumes at most one presence event is pending (ie awaiting channel attach). For most usecases this is fine as clients will only enter themselves into presence, but technically the assumption is invalid since one client can enter many clientIds if using basic auth or a wildcard identity. So should probably be an array, ala `realtimeChannel#pendingEvents`

**Comment by paddybyers** [comment]
Yes, well spotted.

**Comment by SimonWoolf** [comment]
This is fixed in 0.9.
