### ISSUE TITLE
Protocol error not moving client to failed state

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#254]
I have seen an intermittent error appear from the Ably service as follows:

```
1541Ably: Transport.onProtocolMessage(): error; connectionKey = bb89b!NOTPMXgeONkHD6OS-a0fbb89b; err = {"message":"Unexpected error decoding message; err = TypeError: Cannot read property '0' of null\n    at Decoder.parse (/app/node_modules/msgpack-js/msgpack.js:89:25)\n    at Object.decode (/app/node_modules/msgpack-js/msgpack.js:285:23)\n    at Function.ProtocolMessage.ProtocolMessage.unpack (/app/common/lib/types/protocolmessage.js:247:46)\n    at /app/common/lib/channel/channelsubscriber.js:363:38\n    at Command.callback (/app/common/lib/redis/redisclient.js:447:5)\n    at RedisClient.return_reply (/app/node_modules/redis/index.js:664:25)\n    at JavascriptReplyParser.reply_parser.send_reply (/app/node_modules/redis/index.js:332:14)\n    at JavascriptReplyParser.run (/app/node_modules/redis/lib/parsers/javascript.js:132:18)\n    at JavascriptReplyParser.execute (/app/node_modules/redis/lib/parsers/javascript.js:107:10)\n    at Socket.<anonymous> (/app/node_modules/redis/index.js:131:27)","code":50000,"statusCode":500}
```

However, no Connection failed event is fired, so the connection is now unusable, yet the client is unable to respond.  @SimonWoolf would you mind having a quick look at this as this is quite a blocker for people./

**Comment by SimonWoolf** [comment]
@mattheworiordan bit more context would help? Eg the full message you get from realtime (need log level: 4, printed after `Transport.onProtocolMessage(): received; `) - in particular, then would see whether that message has a `channel` key (can't tell from the `Transport.onProtocolMessage(): error;` message as that only prints the value of the `error` key). If it does, that would explain why the connection doesn't go to `failed`

**Comment by SimonWoolf** [comment]
> no Connection failed event is fired

(also -- 500/50000 ERRORs aren't supposed to make the connection go into failed, but instead disconnected with immediate reconnect, which afaict works correctly)

**Comment by SimonWoolf** [comment]
OK, I reproduced this the brute-force way (making realtime manually throw the same kind of error in the same method as was being thrown), and can confirm that it's a channel error, not a connection error.

`Ably: Transport.onProtocolMessage(): received; [ProtocolMessage; action=ERROR; channel=channel; connectionSerial=0; timestamp=1459777407555; error=[ErrorInfo: OMGWTFBBQ; statusCode=500; code=50000]]`

So it's correct that no connection events were thrown. The channel should go into a failed state, and seems to do so correctly. Future operations fail with `{"message":"Channel operation failed (invalid channel state)","code":90001,"statusCode":400}`. AFAICT everything's working as it should.

@mattheworiordan Could you clarify what you mean by 'the connection is now unusable'? Connection should be fine, it's only the channel that should be affected

**Comment by mattheworiordan** [comment]
> Could you clarify what you mean by 'the connection is now unusable'

In the Lob app nothing was happening, but this was because no messages were sent/received on the channel.  So it may very well have been isolated to the channel

**Comment by SimonWoolf** [comment]
In that case, tentatively closing this as 'working as designed'
