### ISSUE TITLE
TODO: consider new `onPageRefresh: close | persist | none` connection option

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#259]
in place of `recover: true`

also make docs clearer

**Comment by mattheworiordan** [comment]
@paddybyers @SimonWoolf where did we get to on this?  I am just building a little demo for someone and I have encountered this challenge again

**Comment by SimonWoolf** [comment]
I'm not sure we reached a conclusion, IIRC Paddy was a bit ambivalent. I've gone ahead and implemented it anyway so we have a more solid basis for discussion. https://github.com/ably/ably-js/pull/264

**Comment by mattheworiordan** [comment]
Closing this in favour of our issue relating to onUnload and recover
