### ISSUE TITLE
TypeError on presence.subscribe()

### ISSUE THREAD

**Issue by remcoplasmeyer** [ably/ably-js#26]
In the following snippet:

```
self.channel = self.Ably.channels.get(_channelname);
self.subscription = type;
self.channel.attach();
self.channel.on('attached', function() {
	console.log("ATTACHED TO CHANNEL");
	self.channel.subscribe(self.subscription, function(msg) {
		console.log("received ably msg?");
		console.log(msg);
	});
	
	self.channel.presence.enter({}, function(dat) {
		console.log("ENTERED");
		//self.channel.presence.get();
		self.channel.presence.get(null, function(dat, dat2) {
			console.log("subscribed");
			resolve(dat2);
		});	
		
		self.channel.presence.subscribe(function(presenceMessage) {
			console.log(presenceMessage);
		});
	});
});
```

Including the `self.channel.presence.subscribe` function returns me the following 2 errors:

`Ably: EventEmitter.emit(): Unexpected listener exception: TypeError: undefined is not a function; stack = TypeError: undefined is not a function`

`Ably: WebSocketTransport.onWsData(): Unexpected exception handing channel message: TypeError: undefined is not a function`

Note that I have tried replacing the parameters with `self.channel.presence.subscribe("enter", function(presenceMessage)`, but this results in the same errors. Am I doing something wrong here?

**Comment by paddybyers** [comment]
The error message:

    Ably: EventEmitter.emit():  ...

is logging the fact that an exception was thrown in your callback code.

The problem is that there is no such thing as `channel.presence.subscribe`. The `presence` object is an `EventEmitter` and so you subscribe to events on that with `on()`.

**Comment by remcoplasmeyer** [comment]
Gotcha, working perfectly now. Thanks.
