### ISSUE TITLE
Reduce verbosity of library 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#268]
See https://app.intercom.io/a/apps/ua39m1ld/inbox/conversation/4688239839

I have had a few conversations with users about hiding the logs from the console.  I think it's unnecessary, by default, to show this information to users.  We should only be showing warnings or errors.

@paddybyers @SimonWoolf do you agree?

**Comment by paddybyers** [comment]
The ably-js logger doesn't have a `LOG_WARN` level, so that would make the default `LOG_ERROR`, which is fine IMO.

**Comment by mattheworiordan** [comment]
Ok, great, @SimonWoolf can you make the change and I will update the docs?

**Comment by SimonWoolf** [comment]
Fixed by c122a1f
