### ISSUE TITLE
Renewing a token as a matter of course is not an error

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#273]
In the console, when a token expires and is renewed, we show the following:

```
Ably: Transport.onProtocolMessage(): error; connectionKey = 468ce!frreiqZF31aRIKr7-2cb7468ce; err = {"message":"Key/token status changed (expire)","code":40142,"statusCode":401} 
```

This is just wrong, it's not an error, it's expected behaviour and so long as the token is renewed successfully and the connection is resumed, then I do not believe we should even a warning in the console by default.

@paddybyers do you agree we should downgrade this message to just info?

**Comment by paddybyers** [comment]
> do you agree we should downgrade this message to just info?

I accept that this particular message will happen routinely but I'm against going in the direction of having a dictionary of different error codes which we use to lookup the level of any given log message. 

I would prefer that generically we have the `LOG_ERROR` level for fatal errors that result in `failed` connections or channels; and some other level (ideally `LOG_WARN`, but we don't have that atm) for non-fatal errors such as disconnections. Ideally we would find a way to log this condition generically as a non-fatal condition.

**Comment by mattheworiordan** [comment]
> I accept that this particular message will happen routinely but I'm against going in the direction of having a dictionary of different error codes which we use to lookup the level of any given log message.

I'm not quite sure what you mean here.  All I am saying is that if we show developers error messages in their console, then it's perfectly normal for them to assume they are errors. In this case, it's not.

> I would prefer that generically we have the LOG_ERROR level for fatal errors that result in failed connections or channels; and some other level (ideally LOG_WARN, but we don't have that atm) for non-fatal errors such as disconnections.

Well a disconnection is a warning, yet arguably a token upgrade should not be. It is only because we don't yet offer upgrades on the existing connection.

Is the answer not to bring in a warn level some how?

**Comment by paddybyers** [comment]
> Is the answer not to bring in a warn level some how?

I think that would be useful.

**Comment by SimonWoolf** [comment]
If we're doing this, s'probably worth doing a quick review of existing log levels. Eg seems to me that the LOG_MAJOR level isn't particularly useful at the moment (there's only six uses, half of which are different sections of `chooseTransport`).

How about: we make LOG_MAJOR log in an easily-readable way all connection or channel state changes (which currently need LOG_MINOR) and the reason for them; unless that state change is to `failed`, in which case it's logged as LOG_ERROR. And make the `onProtocolMessage()`one just a MINOR; so someone at MAJOR or ERROR will never see raw protocol messages. The message and error code in an ERROR action will end up being logged as a LOG_ERROR if it leads to a failed connection/channel, else as MAJOR if it only leads to a disconnect (ie if it's [nonfatal](https://github.com/ably/ably-js/blob/master/common/lib/transport/connectionmanager.js#L10-L20), eg a token error).

If I do that, I don't think there's much value in a WARN level in addition to the revamped MAJOR: someone who wants to see all disconnections (even routine, expected ones) can use the revamped MAJOR, someone who doesn't can use ERROR.

**Comment by mattheworiordan** [comment]
Sounds good to me 👍

**Comment by mattheworiordan** [comment]
Should we close this now, I assume #275 fixes this?

**Comment by SimonWoolf** [comment]
yep
