### ISSUE TITLE
Non-string clientId should be rejected

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#278]
A customer has been using Integers as `clientId`, yet our spec dictates that `clientId` must be a string.  The client library should reject non-compatible clientId types immediately.  See http://docs.ably.io/client-lib-development-guide/features/#RSA7c, http://docs.ably.io/client-lib-development-guide/features/#TO3a and http://docs.ably.io/client-lib-development-guide/features/#TE2

**Comment by SimonWoolf** [comment]
This was fixed back in 2015: 0fdd191
