### ISSUE TITLE
React-native

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#280]
Can we support React Native using our ably-js lib, or do we need to use the native libraries under the hood.

Given `async` HTTP requests and `WebSockets` are supported https://facebook.github.io/react-native/docs/network.html, it should, in theory, be quite straightforward to add react native support.

One to review.

**Comment by tcard** [comment]
Just confirmed it works if I remove some JSONPTransport object, which has a hard dependency on `document` and isn't even referenced anywhere else in the library.

Can it be removed? Or should I instead define it iff `document` is defined?

**Comment by paddybyers** [comment]
> isn't even referenced anywhere else in the library

It is referenced here: https://github.com/ably/ably-js/blob/master/browser/lib/transport/jsonptransport.js#L21

and therefore elsewhere obtained either by name (`jsonp`), or by enumeration of all transports.

> should I instead define it iff document is defined?

I think at the top we should have something like

```
var isSupported = (typeof(document) !== 'undefined');
var head = isSupported && ....
```

then

```
JSONPTransport.isAvailable = function() { return isSupported; };
```

**Comment by tcard** [comment]
Oh right, didn't notice the function was manipulating a global from within. Done that at #283.

**Comment by mattheworiordan** [comment]
@tcard can we close this now?

**Comment by tcard** [comment]
Yes, working again.
