### ISSUE TITLE
Presence subscribe with multiple events does not work

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#289]
See https://www.ably.io/documentation/realtime/presence#subscribe-event-array

Docs state it supports an array.

**Comment by SimonWoolf** [comment]
Not sure why the docs say it supports an array, the spec specifies "a single action argument" http://docs.ably.io/client-lib-development-guide/features/#RTP6. If we want to support an array argument for subscribes, we should add it to the spec (for both presence and normal subscribes for consistency).

**Comment by SimonWoolf** [comment]
This is fixed in 0.9
