### ISSUE TITLE
Safari can throw an exception when you use localstorage, even if it looks enabled

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#297]
https://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st

https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/5196809049

wtf safari

**Comment by SimonWoolf** [comment]
Fixed by 88fe5ab

**Comment by mattheworiordan** [comment]
```
I still see the same error on safari I’m afraid. Opening [customer site] in a safari private window results in this error:

Ably: EventEmitter.emit(): Unexpected listener exception: Error: QuotaExceededError: DOM Exception 22; stack = setItem@[native code]
```

**Comment by SimonWoolf** [comment]
Been wrestling with saucelabs' bloody slow interactive VMs connection to try this in a couple versions of safari before the 10 minute hard limit on manual sessions expires, but haven't been ably to reproduce it. All seems to work for me. Could you give some more details? Safari version, OS X version, line number from a nonminified lib, anything..?

**Comment by mattheworiordan** [comment]
FYI, @SimonWoolf looks like the CDN had 0.8.22 on it, so that was prob the problem.  Waiting to hear from the customer as I could not replicate it.

**Comment by wichert** [comment]
I can confirm this is fixed now!

**Comment by SimonWoolf** [comment]
>  looks like the CDN had 0.8.22 on it

Ah bugger, I thought I'd deployed it on Friday, guess I didn't!

> I can confirm this is fixed now!

Glad to hear :)
