### ISSUE TITLE
Need to rethink how channels get suspended on nonfatal conection errors

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#305]
Logic setting channels to suspended on nonfatal connection errors has always been in transport.onConnect, [here](https://github.com/ably/ably-js/blob/0b35c462347cabbc8e1776db0fa84abcce38078b/common/lib/transport/transport.js#L116-L129). This has probably been not quite correct for a while now, due to upgrading. Should probably be on activateTransport.

TODO: rethink, esp in light of the new reattach spec and its continuity-loss `ATTACHED` flags

**Comment by mattheworiordan** [comment]
Should this not be closed now that it's mostly covered off in 0.9 @SimonWoolf?

**Comment by SimonWoolf** [comment]
:+1: This is fixed in 0.9
