### ISSUE TITLE
Quick reconnect after token TTL expires gets stuck in connecting

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#311]
See https://jsbin.ably.io/icapud/2/edit

It connects fine, gets a `message: "Key/token status changed (expire)", code: 40142, statusCode: 401}` as expected, but then when it returns to the connecting state there does not appear to be a connection attempt made and it just stays in that state for a short period of time?

**Comment by SimonWoolf** [comment]
@mattheworiordan did you link the wrong jsbin? That one seems to just be demonstrating that if you change the clientId and resume, realtime'll reject it with a `Mismatched clientId for existing connection` error; the connection seems to be made fine.

```
Created token request: {"keyName":"xVLyHw.V4EYrw","ttl":5000,"clientId":"client1","log":{"level":3},"capability":"","timestamp":1468410087097,"nonce":"4015014724873799","mac":"1gPpP3Bu0SCMGG6UcobJ5FwLPQNVizrk5LEAk21r9fA="}
Connecting
Connected
Created token request: {"keyName":"xVLyHw.V4EYrw","ttl":5000,"clientId":"client2","log":{"level":3},"capability":"","timestamp":1468410093006,"nonce":"3928446953677815","mac":"UMXfqBlDjZYbjRhHMBpXqWmZml5bi7lNdGb4k/xlRlw="}
Connecting
Connection failed: {"previous":"connecting","current":"failed","reason":{"message":"Mismatched clientId for existing connection","code":40102,"statusCode":401}}
Current client ID: null
Removed clientId and reconnecting
Connecting
Connected
Created token request: {"keyName":"xVLyHw.V4EYrw","ttl":5000,"clientId":"client3","log":{"level":3},"capability":"","timestamp":1468410098498,"nonce":"6700454427210315","mac":"IgSb9TRoo834hc3KF47EhfJyZjFgkVSVfz3o5VCsAuA="}
Connecting
Connection failed: {"previous":"connecting","current":"failed","reason":{"message":"Mismatched clientId for existing connection","code":40102,"statusCode":401}}
Current client ID: null
Removed clientId and reconnecting
Connecting
Connected
Created token request: {"keyName":"xVLyHw.V4EYrw","ttl":5000,"clientId":"client4","log":{"level":3},"capability":"","timestamp":1468410104402,"nonce":"2753727702408557","mac":"ulirMn97PHY8+oRTCaYaW8X2nnS0SEE0owLckNZeXok="}
Connecting
Connection failed: {"previous":"connecting","current":"failed","reason":{"message":"Mismatched clientId for existing connection","code":40102,"statusCode":401}}
Current client ID: null
Removed clientId and reconnecting
Connecting
Connected
...
````

**Comment by mattheworiordan** [comment]
Yes, seems to have updated the JSBIn with later changes.

Try https://jsbin.ably.io/icapud/5/edit.  Note the time it takes to from Connecting to Connected the second time.

![voila_capture 2016-07-13_03-23-59_pm](https://cloud.githubusercontent.com/assets/43789/16806782/e4ac2d12-490d-11e6-8a8e-642305e40c47.png)

**Comment by SimonWoolf** [comment]
@mattheworiordan good spot - the auth param getter was returning an error due to the mismatched clientId, which was aborting the transport (which finishes it with `failed`), but the preconnect code was only listening for `error` but not `failed`. Fixed with https://github.com/ably/ably-js/pull/314
