### ISSUE TITLE
DETACHED with error still means detached, not failed

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-js#312]
I’m running the deploy-cores-with-lots-of-active-channels test, and under load we get some channels being detached, which results in a `DETACHED` message with `error` sent to the client.

However, in ably-js we then transition to `failed` instead of `detached`:

 ```
Ably: Transport.onProtocolMessage(): received on web_socket: [ProtocolMessage; action=DETACHED; channel=testchannel923; error=[ErrorInfo: Master retired/disabled; statusCode=400; code=40000]]
Ably: Channel state for channel "testchannel923": failed; reason: Master retired/disabled, code: 40000
```

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/313
