### ISSUE TITLE
Nativescript Plugin

### ISSUE THREAD

**Issue by giovannicandido** [ably/ably-js#323]
Hi,
I'm writing a Nativescript Plugin wrapper for Android and IOS, that delegates to the native libraries ably provides. It will be used in my next application

My Goal is to opensource for the community

Advantages:
1. Common API and 100% share code between Android and IOS
2. Open the possibility of shared code between Web too

Is a work in progress, and have just I little percentage of API coverage only in android

I will keep the API as close as possible, but I change  a little bit, to use Observables instead of callbacks

I would like feedback, by example in the topics
- The API
- License
- How to test

Contributions would be nice

Links

https://github.com/atende/nativescript-ably
https://github.com/atende/nativescript-ably-demo
http://nativescript.org
https://github.com/Reactive-Extensions/RxJS

Cheers,
Giovanni

**Comment by mattheworiordan** [comment]
Wow @giovannicandido, this looks great.  We are talking about this internally and will get back to you with our collective feedback very soon.

**Comment by giovannicandido** [comment]
@mattheworiordan Thanks

**Comment by mattheworiordan** [comment]
@giovannicandido can you email me your email address and we'll add you to our client library Slack channel.  Hopefully tomorrow we can all have a chat with you to see how we can help you along with this as it looks great.  My email is matt AT ably dot IO

**Comment by mattheworiordan** [comment]
Hey @giovannicandido we're really keen to help you along with this work you're doing, but think it would really help if we have a quick chat to see how best to move forwards.  Any chance we can grab some time on Slack / Skype / our live chat at www.ably.io?

**Comment by mattheworiordan** [comment]
@giovannicandido see https://github.com/ably/ably-js/issues/320.  One of our other users sent me their TypeScript definition they are using.  Would be great to move forwards with your work when you have the time.

**Comment by giovannicandido** [comment]
@mattheworiordan Yes, sorry for late response. I'm looking for a spare time :-). I send to you an email

**Comment by giovannicandido** [comment]
@mattheworiordan There is some overlap between what I'm writing and the typescript definitions on #320. I think with a little of intervention the generated definitions from my code could be adapted to the nodejs runtime and client, but they are not identical, and I'm using observables.

I will reserve a time to think on how to maintain the definitions for the three platforms. In my guess is doable. For nativescript is automatic generated.

**Comment by mattheworiordan** [comment]
@giovannicandido out of interest, did you make any progress with this?

**Comment by giovannicandido** [comment]
Hi, thank you for asking!

I had to take a pause to complete some other things. I Will probably  get on that again by October 15th. 

Meanwhile, I did some progress, the demo is working with a simple chat: https://github.com/atende/nativescript-ably-demo <https://github.com/atende/nativescript-ably-demo>

**Comment by SimonWoolf** [comment]
Closing this as superseded by https://github.com/ably/ably-js-nativescript
