### ISSUE TITLE
Update `ws` version

### ISSUE THREAD

**Issue by zenekron** [ably/ably-js#326]
Apparently `ws@0.8.x` breaks on node 6.3+ ([issue 778](https://github.com/websockets/ws/issues/778)).

This bug has been fixed in the newer versions (1.1.1+) so I think it should be worth upgrading the used ws version.

**Comment by mattheworiordan** [comment]
Thanks @zenekron, we'll take a look.

**Comment by zenekron** [comment]
If `ws`'s docs thruthfully reflect the changes made to the API, from `0.8.0` to `1.1.1` the only change that has been made is that now `ws#close` takes an optional callback with an error as the first argument.

[Here](http://pastebin.com/GsfugMgF) is an extract of the diff on `docs/ws.md` and [here](https://github.com/websockets/ws/compare/0.8.0...1.1.1) is the full diff on github.

**Comment by SimonWoolf** [comment]
Hi @zenekron. I've added the upgrade to 1.1.1 to the v0.9 release, which we're planning for next week - see https://github.com/ably/ably-js/pull/324/commits/a2602239489b43fbe6afa5f4568d707656a5b7b0. (We can backport that fix to 0.8 if we have to, but I'd prefer to be a bit more conservative with 0.8; hopefully anyone running a cutting edge version of node will also be happy to use 0.9). Thanks for the bug report :)

**Comment by mattheworiordan** [comment]
@SimonWoolf please can you backport if easy.  Another user has reported a problem trying to use the Node.js lib with 6.x, and given we've not released 0.9, we need to ensure 0.8 supports 6.x

**Comment by SimonWoolf** [comment]
Released ably-js 0.8.33 with ws 1.1.1
