### ISSUE TITLE
Unable to install ably through NPM

### ISSUE THREAD

**Issue by Raullg98** [ably/ably-js#328]
OS: Windows 10 -  x64
![ably1](https://cloud.githubusercontent.com/assets/7134950/18075613/302a60dc-6e2b-11e6-86cc-821010aa7015.png)
![ably2](https://cloud.githubusercontent.com/assets/7134950/18075614/302dec66-6e2b-11e6-8fd3-1e067051b31a.png)
![ably3](https://cloud.githubusercontent.com/assets/7134950/18075615/30317368-6e2b-11e6-9a99-40dad0845f2b.png)

**Comment by mattheworiordan** [comment]
Thanks for reporting the problem @Raullg98. We don't use Windows ourselves so have not come across this, but will try and recreate this environment so that we can reproduce and fix the issue.  Unfortunately this looks like a dependency issue on Windows 10.

**Comment by SimonWoolf** [comment]
Hi @Raullg98 . I believe this is a known bug with npm prior to 3.10.5 / 2.15.9, see https://github.com/nodejs/node-gyp/issues/972. Could you upgrade to the latest version of npm2/3 (`npm -g install npm@2` / `npm -g install npm@3`), remove your `node_modules` folder and reinstall, and reopen this issue if the error still occurs. Thanks
