### ISSUE TITLE
Node build without crypto or buffertools

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#332]
https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/5952016749 has made me wonder if we should offer a node package without cryptojs and buffertools (like ably.noencryption.js for the browser), for usecases like using on AWS Lambda, where large package sizes (npm package is > 10MB at the moment, mostly cryptojs)) and having natively compiled modules [are a pain](https://stackoverflow.com/questions/30340443/cross-compile-node-module-with-native-bindings-with-node-gyp).

**Comment by mattheworiordan** [comment]
You could take a similar approach to `ably-ruby-rest` where it simply references ably-js as a sub-module thus allowing it to skip all dependencies but use most of the code

**Comment by leozc** [comment]
@mattheworiordan  possible be more explicit ?
I have a node app that runs in AWS, and what exactly should be go into package.json and the import line?
Thanks!

**Comment by mattheworiordan** [comment]
@leozc that note was for Simon to look at, probably not something we could easily explain how you can do it.  Can you wait till early next week as we may be able to make a release that does not depend on buffertools?

**Comment by mattheworiordan** [comment]
@SimonWoolf we need to look at this on Monday as @paddybyers has confirmed Buffertools is not needed (Node.js 4.3.2 on Lambda has Buffer support, it was introduced in 0.11!).

Also, it seems crypto is part of Node.js core so shouldn't be an issue.

We need to remove BufferTools and check that it works in Lambda, then bump a release and add a note that we no longer support Node < 0.11

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/340, released as part of ably-js 0.8.38.
