### ISSUE TITLE
useBinaryProtocol defaults

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#333]
Currently (since https://github.com/ably/ably-js/commit/b94bdaf) ably-js defaults to json rather than msgpack unless you explicitly set useBinaryProtocol to true. Paddy made the change as msgpack was slow in browsers. http://docs.ably.io/client-lib-development-guide/features/#TO3f wants the default to be binary. Options are:
1. default to binary everywhere it's supported
2. default to binary for node and json for browsers
3. leave as-is (default to json for everyone)

**Comment by paddybyers** [comment]
I vote 2

**Comment by SimonWoolf** [comment]
then we'll do option 2, docs pr: https://github.com/ably/docs/pull/161

**Comment by SimonWoolf** [comment]
(reopening until actually implemented)

**Comment by SimonWoolf** [comment]
This was fixed by 12e1f2f
