### ISSUE TITLE
Odd behaviour with firefox

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#334]
with [redacted] in firefox -- first ws connection seems to fail with `Firefox can't establish a connection to the server at wss://[redacted]-realtime.ably.io/?access_token=....`, and first upgrade one gets disconnected immediately, so connections sticks with comet for a while. Third websocket upgrade attempt works fine. Only firefox, doesn't happen in chrome. Not sure if this is new behaviour

**Comment by paddybyers** [comment]
> first upgrade one gets disconnected immediately

by realtime, or it never gets that far?

**Comment by SimonWoolf** [comment]
If by realtime, it's not with an error, just an abrupt cutoff (1006)

**Comment by SimonWoolf** [comment]
More info: I can basically only reproduce this in the nightblue3 room (the biggest one), and then only sometimes. (And now can't reproduce the first upgrade failing at all, just the initial connection failing and then the upgrade succeeding). I think it's just doing so much work on initial page load that the 4s preference-connect timeout is expiring before it actually gets around to actually connect, so the ws connection is getting cut off before it gets started (and it doesn't happen on chrome because chrome's faster at js). Not sure if there's anything we can/should really do about that...
