### ISSUE TITLE
Share test app set up & encoding fixture data

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#34]
See https://github.com/ably/ably-ruby/commit/a0b908113d7a8fadc43e3cacb235edb8a7d126cd and https://github.com/ably/ably-ruby/commit/bce255f6f36a99b2f4a735e3d80808f99036102e.  

We should share the test app set up and encoding / decoding fixture JSON between all client libraries to encourage consistency.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/119
