### ISSUE TITLE
Platform object

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#346]
As we are starting to extend out ably-js to support lots more platforms (NativeScript, Titanium, etc), I think our logic that is scattered around (where necessary) that evaluates statements like `if (isBrowser) { ... }` should be feature driven instead.

So I propose that prior to the NativeScript work being done, we consider introducing a new Platform abstract / default object, that is then extended based on the detected platform.  So instead of `isBrowser` we could do something like `if (Platform.supportsXHR())`, `if (Platform.supportWebsocketPings())`, if `Platform.supportsPushNotifications())` etc.

WDYT?

BTW. We could even make this object exposed (pseudo-privately) so that we could use it to more easily enable / disable functionality in tests.

**Comment by paddybyers** [comment]
We already have abstracted at lot of this with APIs such as `BufferUtils.supportsBinary()` and eg `WebSocketTransport.isAvailable()` for each of the transports but there's no harm in collocating them.

**Comment by mattheworiordan** [comment]
> We already have abstracted at lot of this with APIs such...

Yup, but unfortunately still [a lot of `isBrowser` checks](https://github.com/ably/ably-js/search?utf8=%E2%9C%93&q=isBrowser), and I expect other similar feature checks scattered throughout.

**Comment by SimonWoolf** [comment]
Sure, I've no objection to this

**Comment by mattheworiordan** [comment]
We now have a Platform object, see https://github.com/ably/ably-js/pull/349
