### ISSUE TITLE
Webpack fails when requiring commonjs browser module

### ISSUE THREAD

**Issue by JaapRood** [ably/ably-js#352]
In the WebSocket transport module there's a line of code that should select the right implementation depending on whether the environment is Node or a browser (https://github.com/ably/ably-js/blob/master/common/lib/transport/websockettransport.js#L3):

```js
var WebSocket = isBrowser ? (window.WebSocket || window.MozWebSocket) : require('ws');
```

However, tools like Webpack and Browserify using *static analysis* to build the dependency tree and create bundles, **causing `ws` module to be required**. However, `ws` isn't browser compatible, which causes errors. Below the output of Webpack as it tries to include node internals as well as optional packages that can't be used in the browser:

```
WARNING in ./~/ws/lib/BufferUtil.js
Module not found: Error: Cannot resolve module 'bufferutil' in /Users/jaaprood/Sites/edisoncode/webcore-react/node_modules/ws/lib
 @ ./~/ws/lib/BufferUtil.js 10:19-40

WARNING in ./~/ws/lib/Validation.js
Module not found: Error: Cannot resolve module 'utf-8-validate' in /Users/jaaprood/Sites/edisoncode/webcore-react/node_modules/ws/lib
 @ ./~/ws/lib/Validation.js 10:19-44

ERROR in ./~/ws/lib/WebSocketServer.js
Module not found: Error: Cannot resolve module 'tls' in /Users/jaaprood/Sites/edisoncode/webcore-react/node_modules/ws/lib
 @ ./~/ws/lib/WebSocketServer.js 15:10-24

ERROR in ./~/options/lib/options.js
Module not found: Error: Cannot resolve module 'fs' in /Users/jaaprood/Sites/edisoncode/webcore-react/node_modules/options/lib
 @ ./~/options/lib/options.js 6:9-22
```

## Solution

The `require('ws')` line should never make it into any of the browser packages. I'm not that familiar with the codebase, but something along these lines should probably work fine:

- Dependency inject the websocket implementation by accepting it as an argument with the common websocket transport. Something like:
- Create separate websockets transports for both node and browser, using the common implementation and injecting the implementation.

## Workaround 

Webpack: add `ws` as an external in your `webpack.config.js` so it won't try to bundle it. 

```
{ 
   //...
   externals: ['ws']
}
```

Browserify: I haven't touched that in a while, but the principle should be the same. If anyone gets something to work, let me know and I'll update this.

**Comment by SimonWoolf** [comment]
Hi @JaapRood,

Thanks for the bug report. Happily, this is something we have already fixed in ably-js 0.9 (which uses a [Platform object](https://github.com/ably/ably-js/blob/0-9-spec/browser/fragments/platform-browser.js) pulled in by the Grunt task when compiling platform-specific packages like ably-commonjs.js, which is the one that webpack should use).

Would you mind trying ably-js 0.9 (tag `0.9.0-beta.3` on npm) and confirming whether that fixes your issue? It is technically still in beta, but it's very near release (we plan to release it this week). Thanks!

**Comment by JaapRood** [comment]
@SimonWoolf I'll try that tomorrow if I get the chance to, thanks.

**Comment by JaapRood** [comment]
@SimonWoolf that did the trick, no more errors thrown by Webpack and a functional module.
