### ISSUE TITLE
0.9 presence spec amendments

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#368]
Please see recently merged in https://github.com/ably/docs/commit/cf5c4783f884d98a1a4d86bdddfa6bb22c7c2da2 into the 0.9 spec.

Please ensure that if these spec items are implemented that they are updated to reflect the changes, and any new spec items are adhered to.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/370
