### ISSUE TITLE
Tests for requesting tokens with format=msgpack

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#369]
The tests passed with [this bug existing](https://github.com/ably/ably-js/commit/fdf09a3b717fe445da1ccf2cc16ad99e43fbfa36), which means we don't have any ably-js tests that request a token with `format=msgpack`; we should add one

**Comment by funkyboy** [comment]
@SimonWoolf Addendum: thanks to this https://github.com/ably/ably-js/blob/master/spec/realtime/channel.test.js#L202 also some browser tests are run using the msgpack.

**Comment by SimonWoolf** [comment]
No, those aren't relevant. The issue was for "**requesting tokens with** format=msgpack", not connecting to Ably with format=msgpack. We have plenty of tests for the latter.

However, this issue is obsolete because I later removed the ability to request a token with msgpack entirely, in [this commit](https://github.com/ably/ably-js/pull/406/commits/1d4e2a83a90ec1c86a43ec7088e7dee5d3fef3f3) (part of https://github.com/ably/ably-js/pull/406 )
