### ISSUE TITLE
Keep track of last-known activity time, use it to discard connection state

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#388]
to avoid issues where computer goes to sleep or something and ends up 2 hours later trying to resume without the connection state having transitioned to `suspended`. See https://github.com/ably/realtime/issues/940#issuecomment-286985784

(NB can address https://github.com/ably/ably-js/issues/358 at the same time, find a way to use one mechanism for this and for transport idle timeout for efficiency)

**Comment by mattheworiordan** [comment]
Sounds good, but expect this is a broader docs / spec issue and not just a JS issue as devices have similar problem no?

**Comment by SimonWoolf** [comment]
:+1: https://github.com/ably/docs/issues/287
