### ISSUE TITLE
Cannot keep distinct connections under Chrome / Chrome Incognito in Javascript Realtime Library

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#393]
Creating this issue on behalf of a customer, support ticket 1738.

---

We've observed quite a peculiar situation with attaching to channels using the Javascript Ably library. A bug report is included below:

Bug Component: Ably Javascript Realtime Library (v0.8.42)
Bug Description: Cannot keep distinct connections on Chrome & Chrome Incognito mode - attaching to a channel on one disconnects the other.
Chrome Version Tested: Version 57.0.2987.133 (64-bit)

Steps to replicate:
- Create a test page that includes Ably and some basic testing functions to receive messages on Chrome (non-incognito) & an Incognito tab in the same browser.
Assign different channels to them (channel A & B, as example)

- Open said page with Chrome non-incognito. Channel A is attached. Send message to channel A -- Chrome receives message (expected behavior)

- Open said page with Incognito Chrome. Channel B is attached. Ably debug console reports Channel Closed, Connection Closed and then two Connection/Transport Opened, Channel Opened messages on Channel B. 

- Send message to channel B -- both Chrome and Incognito Chrome receive message (wrong behavior)

We've been unable to replicate this issue on a Chrome-derivative browser (e.g. Opera) but the issue is readily observable on Chrome.
Javascript call codes to Ably are very simple:

```
window.ably = new Ably.Realtime({ key: 'ABLY_OP_KEY', fallbackHostsUseDefault: true });
window.channel = ably.channels.get("(generate random channel here)");
window.channel.subscribe("testEvent", function(message) { console.log(message.data); });
```

**Comment by SimonWoolf** [comment]
I'm afraid I can't reproduce this at all on my computer. I can maintain distinct connections and channel attachments with normal and incognito (and normal/normal, and incognito/incognito, with both 1.0 and 0.8.42) just fine.

Nor can I think of any mechanism that could cause this -- even normally browser-wide mechanisms (eg localstorage) are isolated between incognito and normal tabs.

My testing was on chromium-browser 56.0.2924.76-0ubuntu0.16.04.1268, 64-bit. @mattheworiordan do you want to give this a quick try on macOS+chrome, see if that makes a difference from with linux+chromium?

**Comment by mattheworiordan** [comment]
> do you want to give this a quick try on macOS+chrome, see if that makes a difference from with linux+chromium?

Sure, you got something I can use to test?

**Comment by SimonWoolf** [comment]
I was just using my normal browser sandbox page, I'll send it to you if you like

**Comment by mattheworiordan** [comment]
Alex, please see https://jsbin.ably.io/ayotiy/3/edit for an example we've tested in Linux and on Mac.

We cannot reproduce this issue. In fact we cannot see how it's possible to break out of the security sandbox that Chrome uses, this would be a major security flaw if we were able to do this in fact.

**Comment by SimonWoolf** [comment]
Closing this as unable to reproduce, and failure as reported should not be possible. Customer also reported unable to reproduce.
