### ISSUE TITLE
Internet Up URL & use of HTTPS

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#4]
@paddybyers, for the Java & Ably-js libraries, please can you use the correct URL for the Internet Up CDN test which is https://internet-up.ably-realtime.com/is-the-internet-up.txt, see this change in https://github.com/ably/ably-ruby/commit/007e3b474ae56859faf62c9f8c8f669ea2386fc9.

Also, in the ably-js library, if the library is loaded over HTTPS and it then needs to do an internet up check it currently fails because it tries to do the request over HTTP, see https://github.com/ably/ably-js/blob/add26a07f8987567a6b74270dd3da812fc8eebfb/browser/lib/transport/jsonptransport.js#L27 and https://github.com/ably/ably-js/blob/5bb90e8de461f363734979055754b907bcef9e2d/browser/lib/transport/xhrtransport.js#L12.

@kouno this is the issue we saw FYI.

**Comment by kouno** [comment]
Your commit doesn't fix `http` to `https` for some reason.

**Comment by mattheworiordan** [comment]
@kouno it's not necessary unless you are in a browser.

**Comment by paddybyers** [comment]
So you're saying use HTTPS unconditionally?

**Comment by kouno** [comment]
@mattheworiordan Not necessary but it's more secure. :)

**Comment by mattheworiordan** [comment]
And slower. The request causes a delay before subsequent reconnect attempts are made and SSL handshakes typically add up to second to the request. Security in this case is not really relevant as far as I can see..

Regards,
Matthew

**Comment by kouno** [comment]
> SSL handshakes typically add up to second to the request.

What!? Where did you get that fact? SSL handshakes are more expensive yes, but a full second is a lot of time. Cloudflare speaks about 1/3 of a second which is already more likely.

> That inherently means an additional third of a second gets added to your page load time for any visitor connecting to your site if you're using Verisign's SSL

And it's only on slow certificate authority (aka Verisign) and I thought that Cloudflare was speeding up these things as much as possible. (https://blog.cloudflare.com/how-cloudflare-is-making-ssl-fast/)

> The request causes a delay before subsequent reconnect attempts are made

Hu, sorry. I have no idea what you are speaking about :(. Maybe you could clarify that when I ask you on Monday.

I do not think it's going to be critically slower TBH (as in, we absolutely need this to be super fast). Also this is only if we have a connection drop... And again, everywhere else we use SSL anyway, so I'm not sure why you would worry about this one in particular? And finally, it's hosted by Amazon on S3 so if that's slow, I don't know if I can believe in the internet anymore :).

But honestly, the change itself is inconsequential. So you can safely ignore my comment.

**Comment by mattheworiordan** [comment]
Damon you @kouno, OK, see https://github.com/ably/ably-ruby/commit/12b8e8a41b91301850924c20cd582999d7d8b14f.  Happy?

**Comment by kouno** [comment]
Yes. Damon me. ahahah :smile:
