### ISSUE TITLE
Add callback on auth failure (authError?)

### ISSUE THREAD

**Issue by neil-morrison44** [ably/ably-js#402]
Hi,
I'm running into an issue when my user's session expires and they're sat on a page which only communicates with the back end via ably.

I'm using the authUrl param and generating a token on the back end.
When a session expires the back end will start returning 401s to the ably Auth method, which gets retried every 10 seconds indefinitely.

I'd like some sort of optional callback method which gets called when there's a non-200 response from the auth endpoint, preferably without having to dig into authCallback since authUrl works great with this one exception.

**Comment by mattheworiordan** [comment]
> I'd like some sort of optional callback method which gets called when there's a non-200 response from the auth endpoint, preferably without having to dig into authCallback since authUrl works great with this one exception.

Unfortunately I don't think we are going to support that as this sounds like a feature request specifically for your use case.  Given how trivial it is to do an XHR request within a browser, what is the issue with simply using authCallback, doing the XHR request yourself, if success pass the body to authCallback fn, and if not, handle the situation as you want?

**Comment by neil-morrison44** [comment]
Yeah, that would work. I re-read the documentation about authCallback - I'd missed the part about the TokenDetails object.
