### ISSUE TITLE
Finish: log tweaks to failPendingMessages log

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#408]
Work started at https://github.com/ably/ably-js/tree/log-tweak a few months ago, not finished, can't remember why

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-564) by [Unito](https://www.unito.io/learn-more)

**Comment by Peter-Maguire** [comment]
Closing as branch no longer exists
