### ISSUE TITLE
Change closeOnUnload to default to true

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#409]
We have lots of customers get confused as to why their connection counts are going high as they refresh browsers. As we anecdotally expect most people are not using resume anyway between refreshes, to avoid this common issue, should we enable close on unload by default?

See support tickets 2120 for a recent occurrence of this.

@paddybyers WDYT?

**Comment by paddybyers** [comment]
> using resume

it would be recover

but yes, I agree ... pretty much all apps will reinitialise in a way that makes recovery not sensible or useful. If they go out of their way to support that, then we can show them how.

**Comment by mattheworiordan** [comment]
>> using resume

> it would be recover

Yes, sorry, wrong terminology.

Glad you agree though. @SimonWoolf perhaps we could change when you're back and notify our customers in a newsletter.

**Comment by mattheworiordan** [comment]
Or hold off until 1.1 so that we'd expect customers to read the release notes?

**Comment by SimonWoolf** [comment]
> Or hold off until 1.1 so that we'd expect customers to read the release notes?

Agreed, flipping a default probably isn't something we should do in a patch release (it is technically a breaking change, if only for people who are extracting the recoveryKey manually and passing that in as a string)

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/439
