### ISSUE TITLE
No keyName specified

### ISSUE THREAD

**Issue by remcoplasmeyer** [ably/ably-js#41]
After getting back to development after approx 2 weeks, my previously working application now receives the following error when trying to connect with the realtime library: ``{"statusCode":401,"code":40101,"message":"No keyName specified"}``

This presumably happens on the following line: ``new Ably.Realtime({ key: Settings.ABLY_KEY, log: { level: 1 }, clientId: "clientid", transports: ['web_socket']});``

Where ``Settings.ABLY_KEY`` is ofcourse my valid API key.

Were there same API changes I am now aware of?

**Comment by mattheworiordan** [comment]
Sorry, we have made API changes but it seems perhaps the version you are using is outdated. If you are using the CDN it's possible we've not published the changes to the CDN mistakenly: can you confirm and I will fix shortly when I am back in the office?

**Comment by remcoplasmeyer** [comment]
Yep, using the CDN version. Thanks for the quick reply.

**Comment by paddybyers** [comment]
0.8.0 is now on the CDN; sorry for that.

**Comment by remcoplasmeyer** [comment]
Thanks!
