### ISSUE TITLE
Support for receiver-side browser push notifications.

### ISSUE THREAD

**Issue by tcard** [ably/ably-js#429]
We currently have server-side support for receiving push notifications in the browser [as implemented in Firefox](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API). We'd like to integrate this into the client-side API, following [the push receiver spec](https://docs.ably.io/client-lib-development-guide/features/#RSH2) as closely as possible.

We'd also need to make sure it works for Chrome, Safari and others. As of today, I've been using [this little Go program](https://gist.github.com/tcard/04e4371326d5a9108444b515db02ce19) to test device registration, channel subscription and receiving notifications, but it only works in Firefox. The current server-side implementation expects a `targetUrl` and an `encryptionKey`, both unique per device (browser), but this might need to be adapted too. (I hope not, since that's supposed to be [a W3C standard](https://w3c.github.io/push-api).)

**Comment by tcard** [comment]
Missing:

* Ably's application server key is currently hardcoded. Probably needs to be served. https://github.com/ably/ably-js/blob/183a62dd7cb381262ad884677d126a966c8cb64e/browser/fragments/platform-browser.js#L77
* Safari support. See https://github.com/ably/wiki/issues/242 https://github.com/ably/ably-js/blob/183a62dd7cb381262ad884677d126a966c8cb64e/browser/fragments/platform-browser.js#L123
* Form factor needs to be detected. https://github.com/ably/ably-js/blob/183a62dd7cb381262ad884677d126a966c8cb64e/browser/fragments/platform-browser.js#L30
* Documentation for `ClientOptions.pushServiceWorkerUrl`, the argument passed to [`navigator.serviceWorker.register`](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register). For W3C push only.
* Push activation documentation for JS.
* Tests. See [ably-java tests](https://github.com/ably/ably-java/blob/push/android/src/androidTest/java/io/ably/lib/test/android/AndroidPushTest.java) for inspiration.

**Comment by tcard** [comment]
Also, PushChannel is not implemented at all.

**Comment by Peter-Maguire** [comment]
Got it - this is blocked due to the backend web push API support not being complete. The backend requires a public/private ECDSA keypair to be generated, but browsers do not support exporting the keys in a format that the backend can understand. The general consensus seems to be that work on JS push would be better directed towards react-native, as there is more of a demand and already proven backend support for FCM/APN

**Comment by jamienewcomb** [comment]
@Peter-Maguire thank you 
> backend web push API support not being complete
Is this something we need the realtime team to fix and if so, has it been raised with them?

**Comment by paddybyers** [comment]
Web push needs to find its way into the relevant pod backlog, get scoped, prioritised, etc. There's multiple parts needed.

**Comment by jamienewcomb** [comment]
Yeah exactly. Peter was doing some initial work to see how complete the web push implementation was and if it actually works. The outcome is we are quite far off so if peter can elaborate on 'web push API support not being complete' in a ticket, then at least this will help the next team/pod who do pick this up

**Comment by jamienewcomb** [comment]
Hey everyone - pleased to say that **'Push notification support for web browser in ably-js lib'** and **'React Native support for Push Notifications'** are in development and should be released over the next 6-8 weeks. These are duplicate issues so I will close them.

cc @owenpearson
