### ISSUE TITLE
ToJson bug

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#44]
See https://github.com/ably/ably-js/blob/master/common/lib/types/presencemessage.js#L28, shouldn't this be action?

**Comment by mattheworiordan** [comment]
In fact, it looks like a number of supported fields are missing from the toJson and toString functions

**Comment by paddybyers** [comment]
You'll see that `action` is already there, so the bug is that `name` is included.

Other fields are intentionally omitted because `toJSON()` is only used when sending messages, and this is the subset of fields that are sent by the client.

**Comment by paddybyers** [comment]
https://github.com/ably/ably-js/commit/b1632c3

**Comment by mattheworiordan** [comment]
Thanks, but I think `id` is missing too and `connectionId` from the string representation

**Comment by paddybyers** [comment]
`toString()` is intended to provide a useful human-readable summary containing the most relevant fields.

**Comment by mattheworiordan** [comment]
Seems a bit arbitrary that an `action` enum integer  value and `time` in milliseconds is considered useful human-readable value, but `connectionId` is not IMHO.

**Comment by mattheworiordan** [comment]
Matt to remove unneeded fields such as timestamp, connectionId

**Comment by SimonWoolf** [comment]
Is the action here to remove the timestamp & connectionId fields from the presencemessage object entirely?

**Comment by mattheworiordan** [comment]
> Is the action here to remove the timestamp & connectionId fields from the presencemessage object entirely?

Yes, plus if `clientId` matches the authenticated `clientId`, or if `clientId` is empty, then we don't need to send that field.

**Comment by SimonWoolf** [comment]
I don't see how that can be right. The lib uses the timestamp and connectionId in the presence message to decide whether new presence messages should supersede items with the same clientId + connectionId in the presenceMap: https://github.com/ably/ably-js/blob/master/common/lib/client/realtimepresence.js#L256:L261. If we're removing those two from the object entirely (not just from the fromJSON() and toString() calls), then that problem'll be unsolved

**Comment by SimonWoolf** [comment]
PR that only changes the json/string rep: https://github.com/ably/ably-js/pull/117

**Comment by paddybyers** [comment]
`timestamp` is server-assigned, not client-assigned, so doesn't need to be sent by the client.

`connectionId`is implicit on a realtime connection, so also doesn't need to be sent by the client. Since the client never sends `PresenceMessage`s via REST, then there is no need to include it. `Message`s are of course different in that respect.

**Comment by mattheworiordan** [comment]
@paddybyers and you agree that `clientId` is not needed unless the client is not authenticated yes?

**Comment by paddybyers** [comment]
> you agree that clientId is not needed unless the client is not authenticated yes?

It's correct that if a `clientId` is set on the library then it doesn't need to be populated in each `Message`. That's a different matter however from whether or not it needs to be supported in `toJSON()`.

**Comment by mattheworiordan** [comment]
@paddybyers well perhaps, but then the client library somewhere needs to move `clientId` if the user explicitly sets it.  Also, from what I can see, I think we'll by default always be sending `clientId` with a null value which also is unnecessary?

**Comment by paddybyers** [comment]
> the client library somewhere needs to move clientId if the user explicitly sets it.

it doesn't do that yet. But that's not in `toJSON()`.

> I think we'll by default always be sending clientId with a null value which also is unnecessary?

If unset it will be `undefined`, and therefore will not be in the encoded result.

This `toJSON()` would not be here if it wasn't for the need to base64-encode binary data. If an `undefined` member is present to begin with, it's fine for that same member to be present with `undefined` value in the result.

**Comment by mattheworiordan** [comment]
Ok, makes sense.
