### ISSUE TITLE
Multiple tokens can be fetched simultaneously

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#440]
If several events (e.g. a rest request and a realtime connection, or two rest requests) are triggered concurrently with a library using token auth, then both trigger `_ensureValidAuthCredentials`, both see that `auth.token` is unset, and so both fetch a new token in parallel. E.g. https://jsbin.ably.io/ewelul/16/edit .

**Comment by funkyboy** [comment]
@SimonWoolf @paddybyers what would be the intended result of this? Only one fires? And the other uses auth data from the first?

**Comment by SimonWoolf** [comment]
yup, e.g. an attempt to get auth creds while another is ongoing could instead add an event listener to fire when the first has completed, something like that

**Comment by funkyboy** [comment]
@SimonWoolf So there should be some global object (e.g. `window.ongoingauthobject` in the case of browsers) that tells you if there's an ongoing attempt to fetch an auth token.

**Comment by SimonWoolf** [comment]
why would it need to be a global? it's library state

**Comment by funkyboy** [comment]
@SimonWoolf you are right. Let's call it "global with respect to the library" tho. 
I mean with respect to the `Ably` object.

**Comment by SimonWoolf** [comment]
it should be a property on `Auth`, which is a library singleton, yes

**Comment by SimonWoolf** [comment]
This was fixed by https://github.com/ably/ably-js/pull/567
