### ISSUE TITLE
PresenceMessage action

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#45]
As an Enum is not natively supported in Javascript, I'm trying to figure out what the value for `action` will be.  I am pretty sure it will be the numeric value from the zero-indexed set `{ ABSENT, PRESENT, ENTER, LEAVE, UPDATE }`, however I think this is not a great API for users.

For example, if you a developer called get on all members, there would be no way for the developer to easily work out if they user had an action of leave or enter.  In Ruby this is easy because it's an Enum-like object, and in Java it's an Enum, but in Javascript the `PresenceMessage.Action` object is not public os the user cannot use that to work out what the numeric value means.  I feel the user should be shielded from this personally.

I therefore propose that in the Javascript API the `PresenceMessage#action` field is in fact a string with a value from the set above and it is the responsibility of the library to convert that when sending & receiving messages from Ably.  WDYT?

@paddybyers

**Comment by mattheworiordan** [comment]
Add `this.name` to the docs as it provides the event name

**Comment by paddybyers** [comment]
I think we agreed to close this because a client can look at `this.event` to get the action name.
