### ISSUE TITLE
LOG_ERROR undefined

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#455]
Reported by customer [Tamil in Intercom](https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/conversation/14337392335)

When setting recover callback value to `true`, the following error occurs:

```
chatRealTimeObj = new Ably.Realtime({ tokenDetails : token2, authUrl : url, closeOnUnload : true, log : {level : 4},
recover: function(lastConnectionDetails, cb) {
cb(true);
}
});

angular.js:13424 ReferenceError: LOG_ERROR is not defined
at Object.r.normaliseOptions (ably.min-1.js:80)
at e (ably.min-1.js:238)
at new e (ably.min-1.js:243)
at async.waterfall.chatRealTimeObj (chatServices.js:260)
at nextTask (async.js:5310)
at next (async.js:5317)
at async.js:958
at chatServices.js:247
at getChatToken (chatServices.js:108)
at chatServices.js:246
```

> I think it is trying to execute c.logAction(LOG_ERROR,"Defaults.normaliseOptions","closeOnUnload was true and a session recovery function was set - these are mutually exclusive, so unsetting the latter"),e.recover=null);

**Comment by SimonWoolf** [comment]
Thanks, fixed by f60aae1

**Comment by SimonWoolf** [comment]
This had already been fixed by https://github.com/ably/ably-js/pull/439/files , but I hadn't merged that PR yet ¬_¬

**Comment by mattheworiordan** [comment]
@SimonWoolf is this released?

**Comment by SimonWoolf** [comment]
not yet, will do a release later today after merging the timeserial stuff and anything else outstanding (was in the middle of that when got distracted by Julian asking for help with the livemap/webhook issue)

**Comment by mattheworiordan** [comment]
Ok, please notify the customer https://app.intercom.io/a/apps/ua39m1ld/conversations/14345163998 when released.
