### ISSUE TITLE
memberKey attribute / function on a presence message

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#46]
We provide a [memberKey](https://github.com/ably/ably-js/blob/f84bc976b6fb1e7b68685690fb7f9e5b9febd6f9/common/lib/client/presence.js#L5-L7) method on the presence object where you pass in a `PresenceMessage`, why not instead provide a `memberKey` method on the `PresenceMessage` itself to simplify the API?  

Also, if we provide a `memberKey` that uniquely identifies a member in a presence set, should we not also add a `memberKey` attribute to the Realtime object so that a developer can easily work out what their `memberKey` is?  If we don't provide this, then they will need to understand how to construct this memberKey themselves negating any usefulness of providing this method elsewhere.

WDYT?

**Comment by paddybyers** [comment]
> We provide a `memberKey` method on the presence object

That's a function which is used privately within that class.

We document that a member of a presence set is uniquely identified by the combination of `connectionId` and `clientId`. The `memberKey` string itself used in PresenceMap has no particular significance, other than being a combination of the two. Why expose it to the developer?

**Comment by mattheworiordan** [comment]
Fair enough, I (incorrectly) recalled adding `memberKey` when we made all the presence changes, but you are right that this does not need to be a public member at all which simplifies things.
