### ISSUE TITLE
Update to official closure compiler plugin

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-js#462]
This: https://www.npmjs.com/package/google-closure-compiler

Otherwise the build on CI fails, because the [current one](https://www.npmjs.com/package/grunt-closure-compiler) looks for the jar file in [the wrong path](https://github.com/gmarty/grunt-closure-compiler/issues/55)

**Comment by funkyboy** [comment]
This is blocking for the parallelization in https://github.com/ably/ably-js/pull/452

**Comment by SimonWoolf** [comment]
why does the ci build need the closure compiler at all? The only thing we use the closure compiler for is minification, and iirc the tests use the non-minified lib so that we get understandable stacktraces if the lib crashes

**Comment by paddybyers** [comment]
I assume it's because all grunt tasks (including running tests) have a dependency on the build task, which in turn needs the closure compiler.

**Comment by funkyboy** [comment]
If you don’t run nodeunit before karma tests you end up here
https://travis-ci.org/ably/ably-js/jobs/338615662

**Comment by funkyboy** [comment]
@SimonWoolf @paddybyers speaking of which. Any arguments against committing the .jar directly to the repo? That would allow consistency builds both locally and on the CI.

**Comment by paddybyers** [comment]
> Any arguments against committing the .jar directly to the repo?

It's now available via npm: https://www.npmjs.com/package/google-closure-compiler

Shouldn't we update to that (ie add it to `devDependencies`) and remove the `curl`, `unzip` tasks?

**Comment by funkyboy** [comment]
Yep, that’s what I linked above, my first proposal.

**Comment by paddybyers** [comment]
> Yep, that’s what I linked above, my first proposal.

ah, ok ;) I think we should do this.

**Comment by funkyboy** [comment]
I just hope it’s a matter of swapping a package with another. _said the dreamer_

**Comment by paddybyers** [comment]
Try this: https://github.com/ably/ably-js/pull/463

**Comment by funkyboy** [comment]
@SimonWoolf @paddybyers I removed the compiler altogether. We have this: https://travis-ci.org/ably/ably-js/jobs/338925797#L721 but tests work with no problem :)

**Comment by paddybyers** [comment]
> I removed the compiler altogether. We have this: https://travis-ci.org/ably/ably-js/jobs/338925797#L721 but tests work with no problem :)

Yes, but that's not really the point of my PR. We will continue to need the closure compiler for the minified versions of the library. My PR updates that. Then are you going to run tests on that version of the library (ie that `package.json`) or a different one?

**Comment by funkyboy** [comment]
@paddybyers Sorry, should have been more explicit :) I propose to remove the compiler. After all it's needed only to make the official release. WDYT?

**Comment by paddybyers** [comment]
> I propose to remove the compiler. After all it's needed only to make the official release. WDYT?

I don't know whether or not it is used as-is, bundled as part of the static assets of the library. Creating the minified libs could just be part of the deploy pipeline. But then what if we want to run tests using those minified versions? What if a 3rd party wants to modify/fix the library and wants the resulting minified version? I don't really see what we gain by removing it but I'm open to discussion.

@SimonWoolf ?

**Comment by funkyboy** [comment]
@paddybyers @SimonWoolf I just discovered that we [can't run too many BrowserStack in parallel](https://github.com/ably/ably-js/pull/452/commits/4e490b41ad7ec31ccab47c3a0949c5b43d7c1df7). 
So this is not a blocker anymore. 
I'd leave this open. Let's talk about when/how to update dependencies in the tech catchup.

**Comment by paddybyers** [comment]
> I just discovered that we can't run too many BrowserStack in parallel.
> So this is not a blocker anymore.

I don't understand the relationship between the two issues

**Comment by funkyboy** [comment]
@paddybyers when I ran BS and nodeunit tests in parallel that meant they were all run on different _machines_. Running BS tests on a "machine" _without_ running nodeunit first led to the "missing closure compiler".

**Comment by paddybyers** [comment]
OK. Well the fact remains that we should either remove, or update, the support for the closure compiler in this library. I think it's valid to have a discussion about whether it really belongs as part of the deploy pipeline, but what we have today seems to be broken, and we should do something about that.

**Comment by funkyboy** [comment]
I agree that we should update it.
I'd first run tests on minified JS before updating the compiler. Feels safer. WDYT?

**Comment by paddybyers** [comment]
> Feels safer. WDYT?

Yes, definitely. So far all I did is verify that it installs and generates a minified script.

**Comment by funkyboy** [comment]
Fixed in https://github.com/ably/ably-js/pull/463
