### ISSUE TITLE
Presence#enterClient errors if not supplied with a data param

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#47]
`channel.presence.enterClient('bob', 'foobar');` works fine, but `channel.presence.enterClient('bob');` fails with `"Ably: ConnectionManager.sendQueuedMessages(): Unexpected exception in transport.send(): TypeError: ob is undefined"`

(Docs say data parameter is optional, but might just be that the docs are out of date. Ruby client works without it.)

**Comment by paddybyers** [comment]
It's supposed to work without any data.
