### ISSUE TITLE
Websocket and realtime.ably.io request pending forever with status 101

### ISSUE THREAD

**Issue by foyzulkarim** [ably/ably-js#476]
![image](https://user-images.githubusercontent.com/497812/36516421-0ba12764-17a8-11e8-8a57-889eaea844a7.png)

**Comment by funkyboy** [comment]
@foyzulkarim Thanks for reporting this. Some questions:

- which version of ably-js are you using?
- on which browser it this happening?

**Comment by funkyboy** [comment]
Hi @foyzulkarim 

any news on this?

**Comment by foyzulkarim** [comment]
@funkyboy  didn't try after that. i will knock here when i restart working on that. thanks for keeping in touch.

**Comment by funkyboy** [comment]
@foyzulkarim Thanks for the update. Closing this. Feel free to reopen if needed.

**Comment by SimonWoolf** [comment]
Hi @foyzulkarim . If you manage to reproduce this, it'd be helpful to have a complete level-4 debug log, which you can get by instantiating ably-js with `log: { level: 4}` in the clientOptions (e.g. `new Ably.Realtime({log: {level: 4}})`), and then copy and paste the complete output of the console from this happening. (Additionally, if you're using any unusual clientOptions, e.g. specifying a `transport` or `realtimeHost` or something, do let us know). Thanks!
