### ISSUE TITLE
Convert library to ES6 modules; use webpack for creating bundles

### ISSUE THREAD

**Issue by cainlevy** [ably/ably-js#477]
`import * as Ably from 'ably'` (I'm using TypeScript) yields the follow stats in my Webpack build:

> Size: 369.66kb
> Parsed size: 151.46kb
> Gzipped size: 40.88kb

This makes Ably the single largest dependency in our application. For comparison, the alternative I'm evaluating is roughly 35% of all those numbers.

If Ably exported an ES2015 modules target using the `module` field in package.json, then modern tooling like Webpack could try to only bundle the minimum my application requires. I'm not sure how effective this might be, but those size stats could use some help.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-296) by [Unito](https://www.unito.io/learn-more)

**Comment by funkyboy** [comment]
@cainlevy thanks for reporting this. I can quickly test this in a separate branch. Do you already have some Webpack configuration that I can try on?

**Comment by cainlevy** [comment]
There's so much cruft in my Webpack config that I've copy+pasted from around the Internet that I'm not sure it's a great starting place. I'd probably spin up a barebones `create-react-app` with a super minimal Ably.Realtime integration.

I used https://www.npmjs.com/package/webpack-bundle-analyzer to visualize the stats though. It's pretty nice.

**Comment by waynebrantley** [comment]
Any progress on this.  Creating ES2015 targets would help a bunch.  Having to take everything is very painful.  Need ES6 modules.  

@funkyboy any thoughts?

**Comment by mattheworiordan** [comment]
@funkyboy can you estimate how much work this is?

**Comment by waynebrantley** [comment]
Bottom line is the way the library is organized and distributed, if you take one line of code from it, you end up with 
> Size: 371kb 
> Parsed Size: 152kb 
> Gzipped Size: 41kb 

```
var ably = new Realtime({ authUrl: "/api/ablyauth" })
var channel = ably.RealTime().channels.get("someChannel")
channel.subscribe("someMessage", someCallBack)
```

I think this is a bit unreasonable.  I like the library and the service, but this is a big pain point.  @cainlevy did you end up going with someone else?

Could someone from Ably please advise?

**Comment by cainlevy** [comment]
@waynebrantley yep.

**Comment by cainlevy** [comment]
Misclick! Apologies.

**Comment by mbrevda** [comment]
Another use case: IoT. In a recent project, I added Ably for real time communications. Being a limited board, this project includes a bundler which automatically minifies the code before putting it in the board. Obviously, this breaks Ably due to its custom module loader. Instead, I need to add the entire contents of the npm module to the project, inflating it from < 1k to ~10mb.

**Comment by SimonWoolf** [comment]
@mbrevda fair enough. FWIW we do also offer an MQTT endpoint, which can be good for many IoT applications since MQTT (libraries and the protocol itself) is designed for use in resource-constrained environments. See https://ably.freshdesk.com/support/solutions/articles/3000060409-why-would-i-use-mqtt-over-ably-s-realtime-protocol- and https://www.ably.io/documentation/mqtt

**Comment by eigilsagafos** [comment]
Any news on this? I'm trying to use Ably and bundle with Rollup to use in a lambda function.

**Comment by SimonWoolf** [comment]
@eigilsagafos This is not likely to happen particularly soon I'm afraid, which just means you need to specify `ably` as an `external` dependency when using a bundler like rollup or webpack.

**Comment by cristiammercado** [comment]
Hi,

Any progress on this? I am using this library with Angular v11 and according to `webpack-bundle-analyzer` it's the biggest dependency after core (and it's huge)!

Thanks a lot!

**Comment by SimonWoolf** [comment]
@cristiammercado Yup, it's coming soon, see progress in https://github.com/ably/ably-js/pull/704

**Comment by athammer** [comment]
Just to come back to the original concern but did that PR fix the issues for anyone? I figured with ES6 modules we'd get savings just through tree shaking but that doesn't seem to be the case. The final parsed size is still around 225kbs and the final gzipped size being around 60kbs which makes it look almost comically large compared to our other deps. 

[You can see an example here](https://bundlejs.com/?q=ably&treeshake=%5B%7B+Realtime+%7D%5D&text=%22var+ably+%3D+new+Realtime%28%7B+authUrl%3A+%5C%22%2Fapi%2Fablyauth%5C%22+%7D%29%5Cnvar+channel+%3D+ably.RealTime%28%29.channels.get%28%5C%22someChannel%5C%22%29%5Cnchannel.subscribe%28%5C%22someMessage%5C%22%2C+someCallBack%29%22) - this does seem to add another 30kbs to the final size for some reason?


![image](https://user-images.githubusercontent.com/16027039/190961260-331b7aa8-ac11-4dd1-93e6-7659a35447d7.png)

**Comment by owenpearson** [comment]
Hi @athammer, I appreciate your concern and agree we should be doing better on this. The way the library is currently structured doesn't really give much opportunity for tree shaking imports without breaking changes so we are planning to address this with our v2 release of ably-js. We're juggling other priorities at the moment so I can't give a firm release date yet unfortunately.

**Comment by athammer** [comment]
No worries - I appreciate the work/planning that's going into this. I'll look forward to it thank you!
