### ISSUE TITLE
Add crash reporter

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-js#478]
Like we have in iOS

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-297) by [Unito](https://www.unito.io/learn-more)

**Comment by funkyboy** [comment]
There's one [library for the browser](https://docs.sentry.io/clients/javascript/) and [one for node](https://docs.sentry.io/clients/node/).

**Comment by SimonWoolf** [comment]
another 30k minified for the browser version :/ That's a big step in the wrong direction for https://github.com/ably/ably-js/issues/309. Any chance we could do this very minimally just using Ably.Http with [the raw HTTP api](https://docs.sentry.io/clientdev/overview/) ?

**Comment by funkyboy** [comment]
@SimonWoolf off the top of my head: 

- in a browser context we could hook up with `window.onerror` but a quick search [shows there might be problems](https://mikewest.org/2013/08/debugging-runtime-errors-with-window-onerror)
- for node there's quite a [good error handling guide](https://www.joyent.com/node-js/production/design/errors) 

I'll need to study the guts of raven or other error reporting libs to see how they work.

**Comment by SimonWoolf** [comment]
> in a browser context we could hook up with window.onerror

No, we definitely don't want to do that. Remember, we're just one library that will be running alongside many others and the client's own code. Golden rule: have no side-effects that change the behaviour of the client's other code. (This is the same reason we don't use compability shims that modify builtin prototypes). Adding a global error handler would very much violate that.

We don't need or want a global error handler, we just want to use try/catches around our own code.

**Comment by funkyboy** [comment]
Didn't think of that. You are right. Then I think [Raven's approach](https://github.com/getsentry/raven-js/blob/master/src/raven.js#L297) is pretty interesting. Essentially:

- wrap function calls
- catch exception if any, to send it to the backend
- re-throw

**Comment by paddybyers** [comment]
I'm wary of adding this complexity and bloat to the library systematically.

**Comment by funkyboy** [comment]
Another possibility it to add a crash reporter as an option.
Customers can turn on only if needed to collect just enough reports for identifying and fixing the issue.
Then turn it off again.

**Comment by funkyboy** [comment]
@paddybyers to be clear, what I meant by "I think Raven's approach is pretty interesting" is "I think some custom built solution that adopts an approach similar to Raven should be a good fit for this task".

**Comment by paddybyers** [comment]
@funkyboy ok :) I think that's reasonable. The question is whether that requires us to add 10 try/catch blocks, strategically placed to catch the errors we think are relevant/likely, or we need to add 10,000.

**Comment by funkyboy** [comment]
@paddybyers that's _exactly_ my doubt. But I am still in the research phase for this task. No concrete answers yet :(

**Comment by owenpearson** [comment]
Closing as this is already implemented
