### ISSUE TITLE
Connection state recovery is intermittent

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#48]
If I just refresh my chat client over & over (on a non-persisted client), about a quarter of the time I get the whole message history pushed through on connect, the remaining time I get a clean session.

example timestamp of when I got message history: 1431001293310

example timestamp of when I didn't: 1431001280178

**Comment by paddybyers** [comment]
> on a non-persisted client

what's this?

If this is in the browser, it would be useful to capture please the request that is made in the working and non-working case. The browser library saves a cookie with the `connectionKey` so when you refresh it is supposed to connect with `?recover=<connection key>`. So it would be useful to know whether the failed cases are also submitting that.

Also, in the failed cases, is it returning the original `connectionId`, or a new one? And can you see if there are any errors received in the protocol?

**Comment by SimonWoolf** [comment]
Meant non-persisted *channel*, sorry.

Neither case is submitting a `recover` param -- I'm not instantiating the lib with `recover: true`, so recovery isn't even enabled! So not sure why I'm getting any history at all, let alone way more than I thought a non-persisted channel stores (and way more that a REST request to /messages shows) - a good two hours worth.

ConnectionID is different every time, in both cases.

No errors show up in the console in either case. Afraid I'm not sure what you mean by errors received in the protocol?

**Comment by mattheworiordan** [comment]
Wy was this closed?

**Comment by paddybyers** [comment]
> Why was this closed?

We've created a realtime issue for this; it doesn't appear to be a library issue.
