### ISSUE TITLE
RealTime connected and disconnected events not fired when expected

### ISSUE THREAD

**Issue by tchapeaux** [ably/ably-js#506]
I'm trying to display a "connection lost" notification in my application based on the `connected` and `disconnected` events of the `connection` object described [here](https://www.ably.io/documentation/realtime/connection).

However the events are not fired when I expect them to be. I've tried putting breakpoints in the handlers of the [example jsbin](https://jsbin.ably.io/agusit/1) and simulating a connection lost using the Chrome Developer Tools console and here is what I get:
- On setting my connection offline: a `disconnected` event immediately followed by a `connected` event
- On setting my connection back online: nothing

I was expecting a `disconnected` event when the connection was set offline, then a `connected` event when the connection returned.

I've had a similar behavior when directly removing my Ethernet cable and plugging it back in.

Is this a bug? Or am I not understanding the documentation?

**Comment by SimonWoolf** [comment]
Hi. It is a bug, but it's [a bug in Chrome's offline simulation](https://bugs.chromium.org/p/chromium/issues/detail?id=423246), not in ably-js :slightly_smiling_face: 

Specifically, when you simulate a lost connection with chrome dev tools, that doesn't affect websockets. So ably-js just immediately reconnects (after becoming briefly disconnected triggered by the `offline` event). So when it says you're connected, it's telling the truth -- you can test this by doing a more involved test (e.g. attaching to and sending messages on a channel, and seeing that they're received).

With removing your ethernet cable, that will of course disconnect you, but if your OS doesn't immediately notice the lost connection, then it won't pass it on to Chrome, which won't pass it on (via an [offline event](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/Online_and_offline_events)) to ably-js. In that case, it can take up to 25 seconds for ably-js to notice that you're no longer connected. Once it does, it will go into the `disconnected` state, and then won't be able to reconnect until you plug your network cable back in.
