### ISSUE TITLE
Support running ably-js in a webworker

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#507]
Check if ably-js works as-is within a web worker context; if not, make any necessary changes

**Comment by mattheworiordan** [comment]
@SimonWoolf is there not another way of approaching this which is to multiplex a single connection across multiple tabs via a single webworker?  I've not though it through much, but in the SaaS space, I would say it's not uncommon for users to have lots of tabs open, and this option could save resources & costs for customers. WDYT?

**Comment by SimonWoolf** [comment]
> is there not another way of approaching this which is to multiplex a single connection across multiple tabs via a single webworker?

Sure. But I'd wary of that being something we bake into the library and try to abstract away / do behind the scenes. Given it's not difficult for someone the customer does themselves (e.g [pusher tutorial on doing it](https://blog.pusher.com/reduce-websocket-connections-with-shared-workers/)), I'd have thought it's better to tell people to do that, so that they're creating the worker themselves, the semantics are more obvious / explicit, they can do other stuff in the same worker, etc.

**Comment by mattheworiordan** [comment]
@SimonWoolf OK, will add to our tutorials list then along with a note that we can add to our JS docs.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/593

**Comment by ccoffey** [comment]
I think this issue needs to be re-opened, I see the following when using `v1.2.30`:

<img width="606" alt="Screenshot 2023-09-01 at 13 43 00" src="https://github.com/ably/ably-js/assets/456400/3e39cd8e-65cc-4001-967f-34bc224a1a64">

I see this in `node_modules/ably/build/ably-commonjs.js`:

<img width="651" alt="Screenshot 2023-09-01 at 13 53 20" src="https://github.com/ably/ably-js/assets/456400/aa1bab9f-2f90-40d2-918d-84cf4ee9c7d7">

Upgrading to `v1.2.43` (latest) does not fix the problem however downgrading to `v1.1.14` as mentioned in the above comment https://github.com/ably/ably-js/pull/593#issuecomment-505446157 does make the error go away.

**Comment by owenpearson** [comment]
Hey @ccoffey, since 1.2.10 we've provided a separate bundle for use in webworkers, you can access it like this:
```ts
import * as Ably from 'ably/build/ably-webworker.min';
```
Please give it a try and let us know if you run into any issues

**Comment by ccoffey** [comment]
@owenpearson I should have read the docs more closely. Thank you so much, this is working perfectly!
