### ISSUE TITLE
'variable data is undeclared' when attempting to use Google Closure Compiler

### ISSUE THREAD

**Issue by ashpr** [ably/ably-js#516]
So I'm trying to build a project of ours using ably and compress it via google closure compiler.

It throws the following error:

```
stdin:136807: ERROR - variable data is undeclared
if (typeof(data) == 'string')
```

I found it's this line here..

https://github.com/ably/ably-js/blob/d5023820185b5d4432770134d41d76a7b4ff9cfb/common/lib/types/message.js#L67

I think 'data' is meant to be 'this.data'.. if this could be changed that would be terrific.

**Comment by funkyboy** [comment]
Thanks @ashpr for reporting this.
We also are using the closure compiler to build our [minified version](https://cdn.ably.io/lib/ably.min-1.js)

Just curious, which version are you using? Here's ours: https://github.com/ably/ably-js/blob/master/package.json#L26

**Comment by ashpr** [comment]
Here's the version I'm using bundled with the closure plugin for Webpack
https://github.com/roman01la/webpack-closure-compiler/blob/master/package.json#L27

So I'm two released versions ahead.

I did find this in the patch notes for v20180319

`Stricter "strictMissingProperty" checks.`

See here: https://github.com/google/closure-compiler/wiki/Releases

I suspect that might have something to do with it

**Comment by funkyboy** [comment]
@ashpr I just tried with your version and it still works. It's not related to the version number but to the [compilation_level](https://developers.google.com/closure/compiler/docs/compilation_levels).

We are using [SIMPLE_OPTIMIZATIONS](https://github.com/ably/ably-js/blob/master/Gruntfile.js#L82) and I am guessing you are using `ADVANCED_OPTIMIZATIONS`. Correct?

**Comment by SimonWoolf** [comment]
@funkyboy this is a bit of a moot point, the line ashpr pointed out is clearly wrong and needs to be fixed regardless

**Comment by funkyboy** [comment]
@SimonWoolf sure. The reason I am asking is that I don't get _only_ that error when I take up a notch the optimization level.

```
>>
>> browser/static/ably.js:5023: ERROR - variable data is undeclared
>>                      if (typeof(data) == 'string')
>>                                 ^^^^
>>
>> browser/static/ably.js:8464: ERROR - variable Buffer is undeclared
>>              toBase64 = function(str) { return (new Buffer(str, 'ascii')).toString('base64'); };
>>                                                     ^^^^^^
>>
>> browser/static/ably.js:11503: ERROR - variable exports is undeclared
>> if (typeof exports === "object" && exports) {
>>            ^^^^^^^
>>
>> browser/static/ably.js:11515: ERROR - variable define is undeclared
>> if (typeof define === "function" && define.amd) {
>>            ^^^^^^
>>
>> 4 error(s), 10 warning(s)
>> FAILED to run command for target: ably.js
Warning: Task "closureCompiler:ably.js" failed. Use --force to continue.

Aborted due to warnings.
ably-js>
```

**Comment by ashpr** [comment]
@funkyboy  You are correct. I only get that error in advanced builds.

Nothing else comes up I'm afraid. I have an extern for the exports variable but nothing for the define and Buffer variables so i'm not sure why they are not being flagged.

The GCC NPM repo does come pre-loaded with nodejs externs that may be automatically injected but I can't find any kind of logging to confirm.

**Comment by funkyboy** [comment]
@ashpr Good. [This change](https://github.com/ably/ably-js/pull/517/files#diff-da763f0daf85654e40970bc4867e316cR67) has been merged and will be included in the next release.

**Comment by ashpr** [comment]
Thank you @funkyboy . Much appreciated!
