### ISSUE TITLE
Agree on handling of JSON value types

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#52]
Creating this issue to cover the discussion at https://github.com/ably/ably-js/pull/51

Probably better if we continue the discussion here as an issue

**Comment by paddybyers** [comment]
Copying my comment from there:

OK, you're right, the RFC is explicit: "JSON text is a serialized object or array"

http://www.ietf.org/rfc/rfc4627.txt

By contrast, the ECMA spec permits any text that satisfies the grammar for a JSON value (which does include primitives):

http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf

So I agree remove support for primitives.

**Comment by mattheworiordan** [comment]
Ok, so do we explicitly reject data that is not a supported type, or allow it but then let the developer deal with the possible crash on the other end.  I think we should explicitly reject unsupported types so that we can guarantee type portability between all client libraries.

**Comment by paddybyers** [comment]
Yes, on balance I think it should be rejected.

**Comment by paddybyers** [comment]
.. but then there is the issue of how we claim to police the supplied values. For example, NaN can't be represented in JSON - so do we check for those as well?

**Comment by mattheworiordan** [comment]
Nope, I think it is acceptable that we support String, Binary (ByteArray), and JSON Array / Objects.  If you have a value in there that the native serialiser accepts, such as NaN becoming `null` then I think that is acceptable and something the developer should be able to figure out themselves given we say we support JSON.

**Comment by paddybyers** [comment]
ok, agreed

**Comment by mattheworiordan** [comment]
Please see https://github.com/ably/ably-ruby/pull/48 where I have implemented this
