### ISSUE TITLE
No warning or error when publishing undefined name & undefined message data

### ISSUE THREAD

**Issue by JoHuang** [ably/ably-js#523]
SDK should throw warning or error, or log in console when publishing undefined name & message data. It really publish it and results empty messages received by subscriber.

**Comment by SimonWoolf** [comment]
Hi. This is working as expected, I'm afraid -- either message name or message data can be omitted/null, which will result in a message being published without that field. It follows that both can be emitted. This is useful e.g. for usecases where there will only ever be one type of event on a channel, so just the fact of a message conveys the required information, without wasting data.
