### ISSUE TITLE
Signature of RealtimePresence.subscribe in ably.d.ts does not match docs

### ISSUE THREAD

**Issue by Damienmarble** [ably/ably-js#531]
[The Realtime Presence docs](https://www.ably.io/documentation/realtime/presence#subscribe) state that the `subscribe` method can be called three ways: with a callback, with a string action and a callback and with an array of string actions and an callback.

However, the definition for this method in `ably.d.ts` does not support the third usecase:

    subscribe: (presenceOrCallback: PresenceAction | messageCallback<PresenceMessage>, listener?: messageCallback<PresenceMessage>) => void;

**Comment by funkyboy** [comment]
You are correct @Damienmarble. Thanks for reporting this.

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/commit/b16d020d1d7ffe048485d665de129456c0d89bf9 . (Sorry for the delay, this is a trivial enough fix it should have been done as soon as you reported the bug)
