### ISSUE TITLE
Ensure request method accepts UPDATE, PATCH & DELETE verbs

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#533]
This will be hard to test sadly without mocking or sending requests to a non-realtime server, but we should do our best to confirm request support these verbs.

We also need to decide how we'll handle this in browsers that don't support these verbs.  Perhaps raise an exception?

See https://github.com/ably/docs/pull/493

**Comment by SimonWoolf** [comment]
dup of https://github.com/ably/ably-js/issues/347
