### ISSUE TITLE
Problem compiling Typescript depending on Ably library

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-js#535]
> During the development of our app we received a warning for Typescript application: "WARNING in ./node_modules/ably/nodejs/rest.js
> 7:9-16 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
> 
> WARNING in ./node_modules/ably/nodejs/realtime.js
> 7:9-16 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted"

See https://github.com/ably/ably-js/blob/master/nodejs/realtime.js#L7

This is a result of the way that, in the Ably nodejs library, the sources are compiled together into a single context. We might have to migrate to using conventional `require()`s to construct the nodejs library.

Related: https://github.com/ably/ably-js/issues/477

**Comment by mattheworiordan** [comment]
@SimonWoolf @paddybyers do we think this is going to be resolveable without a significant overhaul?

**Comment by SimonWoolf** [comment]
This particular instance was determined to be a consequence of https://github.com/ably/ably-js/issues/509 (the typescript 2.9.1 bug); the solution was to upgrade to version of typescript which fixes that bug.

**Comment by amites** [comment]
this also affects Typescript 2.9.2 (latest version in 2.x series)

upgrading to Typescript 3.1.x solves it but that won't always be an issue

**Comment by SimonWoolf** [comment]
> upgrading to Typescript 3.1.x solves it but that won't always be an option

@amites While Microsoft hasn't cut a typescript 2.9.x release that incorporates the fix to this bug, they have merged it into the release-2.9 branch, so someone stuck on 2.9.x can reference `git://github.com/Microsoft/TypeScript.git#release-2.9` directly to get a 2.9 version that includes the fix. Please see https://docs.npmjs.com/files/package.json#git-urls-as-dependencies for more information on how to do this.
