### ISSUE TITLE
msg-pack dependency is throwing an error

### ISSUE THREAD

**Issue by Srushtika** [ably/ably-js#538]
I tried testing [RunKit](https://runkit.com) to use it as a possible alternative to host our demos, however, I was shown the following error:

<img width="1094" alt="screen shot 2018-09-05 at 12 40 41 1" src="https://user-images.githubusercontent.com/5900152/45202494-d436cd80-b296-11e8-84c3-8d0c4a7a4f8b.png">

When contacted their support, they said the following:
<img width="1145" alt="screen shot 2018-09-06 at 14 00 32" src="https://user-images.githubusercontent.com/5900152/45202512-e153bc80-b296-11e8-9cb4-34cb505bf376.png">

Any idea of what can be done now and/or why this is happening?

**Comment by mattheworiordan** [comment]
I think the pressing question here, IMHO, is why are we still using a fork?  Can we not get that problem resolved.

**Comment by SimonWoolf** [comment]
> I think the pressing question here, IMHO, is why are we still using a fork? Can we not get that problem resolved.

The version of [the msgpack lib we use that's on npm](https://www.npmjs.com/package/msgpack-js) hasn't had a release in 5 years and is missing several modern msgpack features we use.

We can either search for and switch to a more modern js msgpack library (I'm sure there are good ones out there), or upload our fork to npm.

I'd probably prefer the latter if only because guaranteed not to break things / introduce new bugs, so less opportunity for distractions

**Comment by mattheworiordan** [comment]
> I'd probably prefer the latter if only because guaranteed not to break things / introduce new bugs, so less opportunity for distractions

Agreed.  But then perhaps add an issue to fix this later?

**Comment by SimonWoolf** [comment]
Our fork uploaded to https://www.npmjs.com/package/@ably/msgpack-js ; ably-js updated to use it by https://github.com/ably/ably-js/commit/81b70ebe872e815ab6c607a279df075ada2d1e2c . Existing issue to reconsider other js msgpack libs at https://github.com/ably/realtime/issues/735 .

Note that the branch of our `msgpack-js` fork uploaded to npm is the `npm` branch, which has the name altered to `@ably/msgpack-js` to avoid name conflicts. The master branch is still using the old name, to avoid the name change causing issues from existing versions of ably-js pulling the master branch of ably-forks/msgpack-js .
