### ISSUE TITLE
Possible proxy method enhancements

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#54]
We discussed having a shortcut method to access channels with the form

```
var client = new AblyRealtime(key);
var channel = client.channel('test');
```

Also, if we have a `close` method on the AblyRealtime client, should we not add a `connect` as well.  There is an argument that connect is implicit, however this is not always the case.

If we do add this,  we should do the same for Java & Ruby

**Comment by mattheworiordan** [comment]
In the Ruby library, access to the following attributes from the `AblyRealtime` / `AblyRest` object is provided:

* auth (given auth is configured when the client is initialised, I think it's fair to provide access from the cleint)
* clientId (we discussed previously potentially assigning the clientId automatically if connecting with a token with an embedded clientId, so it makes sense to make this public)
* restClient (allows a developer to access REST client library features if they so wish)

**Comment by mattheworiordan** [comment]
Actually, looking at the implementation for Java & JS, `restClient` is not applicable for those client libraries.

**Comment by mattheworiordan** [comment]
We will add `connect` only

**Comment by SimonWoolf** [comment]
`realtime#connect` was added in 37a5ff0d
