### ISSUE TITLE
Support for Flutter

### ISSUE THREAD

**Issue by swingywc** [ably/ably-js#549]
I would like to ask if there is any solution or package to support using Ably service in Flutter application? Appreciate for any helps.

**Comment by SimonWoolf** [comment]
Hi. You have two options for using Ably with Flutter:

1. write a thin wrapper around our ably-ios and ably-java clients
2. use a dart MQTT client (I believe some exist) with our MQTT adapter, see https://www.ably.io/adapters

In future for support queries, or if you have any followup questions, please raise a support ticket at https://www.ably.io/support or use our live chat, and you'll get a prompt respose; ably-js github issues are specifically for tracking bugs in ably-js. Thanks!
