### ISSUE TITLE
Better error message for an invalid token from the authUrl or callback

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#56]
When the authUrl requests a token from a URL that returns a token string instead of JSON, yet the client thinks it is JSON, a very unhelpful error message is shown:

```
Ably: EventEmitter.emit(): Unexpected listener exception: SyntaxError: Unexpected token L; stack = SyntaxError: Unexpected token L
```

**Comment by paddybyers** [comment]
This is resolved: https://github.com/ably/ably-js/commit/93b658b

**Comment by mattheworiordan** [comment]
Thanks.  Moving forwards, I'll try and create a JSBin for each of these issues so that we can test the fixes as well.

**Comment by paddybyers** [comment]
There is a test: https://github.com/ably/realtime/commit/b7ef95d

**Comment by paddybyers** [comment]
Can we close this?
