### ISSUE TITLE
How to kick/delete member in the presence channel by clientId?

### ISSUE THREAD

**Issue by thadeu** [ably/ably-js#573]

**Comment by SimonWoolf** [comment]
You can't. You can see who else is present in a presence channels, but the presence feature doesn't let you control a present client.

Assuming you're using token auth, your auth server can deny them a token when the client tries to renew it. You could trigger a reauth (or just a close()) immediately by sending them a message, if you've written code for that client to respond to such messages. 

In future for support queries, please raise a support ticket at https://www.ably.io/support or use our live chat. ably-js github issues are specifically for tracking bugs in ably-js, which this is not. Thanks!
