### ISSUE TITLE
After an ATM placement constraint failover, a listener is not registered

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#586]
Browser: Safari Version 12.1 (14607.1.40.1.4), Mac OSX
Ably JS lib: 1.1.7

Tested with Chrome, and this does not happen.

Some information is obfuscated from this issue as it is private.   See https://github.com/ably/infrastructure/pull/1928 for the JSBin used to test this.

When the primary endpoint for a test atm-test-[realtime|rest].ably.io is pointing to a failover cluster, which is in turn responding with 50x-type placement constraint, I have observed a registered subscribe listener on a channel no longer working.  I assume this is due to some behaviour when we fail over that results in a lost listener somehow.

Here is the 50x placement constraint confirmed from the https://atm-test-rest.ably.io/comet/connect?key=rm6Rtg.KNT2Dw%3[OBFUSCATED]&stream=false&heartbeats=true&v=1.1&lib=js-web-1.1.7&rnd=5301703477014148 request.

![screenshot_2019-04-02_03-45-24_pm](https://user-images.githubusercontent.com/43789/55412159-d0360a00-555e-11e9-8ff2-9d09b16b602c.png)

Then when it connects to the failover:

wss://atm-test-a-fallback.ably-realtime.com/?key=rm6Rtg.KNT2Dw:[OBFUSCATED]&upgrade=[OBFUSCATED]&format=json&heartbeats=true&v=1.1&lib=js-web-1.1.7, it connects OK, and the frames for published messages are received:

![screenshot_2019-04-02_03-50-44_pm](https://user-images.githubusercontent.com/43789/55412306-19865980-555f-11e9-8604-159e74f02167.png)

Yet no messages are received from the registered listener:

![screenshot_2019-04-02_03-51-17_pm](https://user-images.githubusercontent.com/43789/55412374-33c03780-555f-11e9-9300-5cba8d52841f.png)

**Comment by SimonWoolf** [comment]
(Closing as Matt subsequently identified this as an jsbin bug, not an ably-js bug)
