### ISSUE TITLE
Promise-based channel.presence.get() returns the wrong type

### ISSUE THREAD

**Issue by CliftonH** [ably/ably-js#599]
I am initializing a realtime client in the following way in order to use the promise-based realtime API:

```
import { Realtime, Types } from 'ably-js';

const realtimeClient = Realtime.Promise({ …config });
```

…then getting a channel's occupancy…

```
const channel = realtimeClient.channels.get('channelId');
channel.presence.get().then((response: PaginatedResult<PresenceMessage>) => {
    /**
     * here I'm expecting response to be a `PaginatedResult<PresenceMessage>` type
     * but instead I see it's a `PresenceMessage[]` type
     */
});
```

It looks like the type definition for the `PresencePromise` [here](https://github.com/ably/ably-js/blob/master/ably.d.ts#L469) is inaccurate.

**Comment by SimonWoolf** [comment]
Good spot, thanks. Fixed by 0493c570891a4befe24c3e88f4a1817ebe11f78a . Will do a release soon

**Comment by SimonWoolf** [comment]
released as 1.1.15

**Comment by mattheworiordan** [comment]
Thanks @cliftonh. Btw we were talking about presence over REST on the call so I assumed that’s where the type issue was. Sorry I looked in the wrong place!

**Comment by CliftonH** [comment]
Thanks for the quick fix, your team is on the ball!
