### ISSUE TITLE
Suggestion: Improving the logs

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#60]
When working with the node library I find it hard, when working with lots of concurrent connections, to scan through the logs and determine which log entries are worth investigating or not.

I have a few small suggestions that I think could help - I assume most of these would apply to the browser library as well:
- Include the log level and a simple timestamp (perhaps just hh:mm:ss.uuu), so for example `20:03:01.001 Ably [INFO] Whatever`
- Where we show undefined, why not simply leave this as empty as it's just more noise.  Here are some examples where undefined does not add anything:

```
Ably: ConnectionManager.enactStateChange: setting new state: connecting; reason = undefined
Ably: NodeCometTransport.tryConnect(): viable transport NodeCometTransport; uri=https://local-rest.ably.io:443/comet/; isConnected=false; format=undefined; stream=true
Ably: ConnectionManager.activateTransport(): transport = NodeCometTransport; uri=https://local-rest.ably.io:443/comet/; isConnected=true; format=undefined; stream=true; connectionKey = YKrCnDuL8JKkaHow; connectionSerial = -1
Ably: ConnectionManager.enactStateChange: setting new state: connected; reason = undefined
Ably: RealtimeChannel.setAttached: activating channel; name = mn5fzeqjipidaemi; message flags = undefined
Ably: RealtimeChannel.setAttached: activating channel; name = vepsgh66k0il766r; message flags = undefined
Ably: Transport.onClose(): err = undefined
```

**Comment by SimonWoolf** [comment]
Re timestamps etc., I use a custom logHandler for that -
```
logHandler = (msg) => {
    var time = new Date();
    console.log(`${time.getHours()}:${time.getMinutes()}:${time.getSeconds()}.${time.getMilliseconds()}`, msg);
```
Not sure we should be adding them in the library - I mean, one of the points of allowing custom logHandlers is to let people add timestamps etc. themselves in whatever format they want, right?
