### ISSUE TITLE
Typescript connection.once inconsistency

### ISSUE THREAD

**Issue by lopezbertoni** [ably/ably-js#609]
Hi,

Using ably js v 1.1.18

When I want to use the Promise based API and found that in the connection.once method the compiler doesn't distinguish between the Callback based and the Promise based.

`
      const connectedPromise = this.ablyClient.connection.once('connected');
      connectedPromise.then(x => console.log('Hey'));
`

The error is: Property 'then' does not exist on type 'void'

The workaround is to do add a casting to any:

`
      const connectedPromise: any = this.ablyClient.connection.once('connected');
      connectedPromise.then(x => console.log('Hey'));
`

Looking at ably.d.ts

`
		once(eventOrCallback: EventType | CallbackType, callback?: CallbackType): void;
		once(event: EventType): Promise<ResultType>;
`

There's really no way to tell the difference between the two methods since the callback in the first one is optional.

**Comment by SimonWoolf** [comment]
Fair comment. Mind trying the typings in https://github.com/ably/ably-js/pull/610/ and letting me know if that fixes your issue?

**Comment by lopezbertoni** [comment]
@SimonWoolf Thanks for the quick update. 
Just tried the typings in #610 and they worked like a charm.

Thanks!

**Comment by SimonWoolf** [comment]
Typings fix released in 1.1.19; apologies for the delay

**Comment by lopezbertoni** [comment]
Thanks!
