### ISSUE TITLE
Remove develop branch

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#624]
We are modifying all repositories to just have a `master` branch, removing `develop`, inline with our updated development flow / branching strategy (internally documented for now but [will be added to docs soon](https://github.com/ably/docs/issues/577)).

This might involve:
- Updating references to `develop` branch in this repository
- Reconfiguring CI systems that rely upon `develop`

**Comment by SimonWoolf** [comment]
done. (no reference updates or ci reconfig necessary; travis & jenkins were already configured to build `master` since we never really actually switched away from `master` in this repo...)
