### ISSUE TITLE
Avoid message bundling, conforming to updated RTL6d

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#629]
See [RTL6d](https://docs.ably.io/client-lib-development-guide/features/#RTL6d), as amended by this [docs PR](https://github.com/ably/docs/pull/788#issuecomment-581490475).

There may be no work to do if this client library already doesn't bundle messages, however I've not got time to investigate that right now so am creating the issue so that investigation can take place followed by remediation if required.

**Comment by SimonWoolf** [comment]
Already fixed by https://github.com/ably/ably-js/pull/623
