### ISSUE TITLE
core-js@<3 deprecated warning on npm install

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#639]
On `npm install` I'm seeing:

```
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

Possibly a simple fix I would want to first find out if there's a reason we've not upgraded.

If I'm understanding the output I'm getting my my local tooling correctly (I'm just getting started with npm) then it looks like this dependency is coming in via [ably-forks/karma](https://github.com/ably-forks/karma):

```
ably-js % npm ls core-js
ably@1.1.24 /Users/quintin/code/ably-js
└─┬ karma@0.13.22 (github:ably-forks/karma#4e2d5d8b0242e037a319ef33d3c2504280cde6f9)
  └── core-js@2.6.11 
```

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-307) by [Unito](https://www.unito.io/learn-more)

**Comment by SimonWoolf** [comment]
yup, so only used for testing, not actually part of the library as used by customers

**Comment by owenpearson** [comment]
Closing as this no longer occurs (probably resolved by [this commit](https://github.com/ably/ably-js/pull/892/commits/015ea9c4af443da5385dcf59cf61f399390de4f3))
