### ISSUE TITLE
ably-js does not adhere to spec for logging attributes

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#642]
See the [Ably SDK IDL](https://docs.ably.io/client-lib-development-guide/features/#idl), specifically `TO3b` and `TO3c`.

Ably JS does not support attributes:

* `logLevel`
* `logHandler`

I propose we introduce those attributes, and remove `log` in a 2.0 release.

**Comment by lawrence-forooghian** [comment]
Closed in #1216.
