### ISSUE TITLE
Replace NodeUnit

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#645]
It's been deprecated for nearly two years (at the time of writing).

Replacement options seem abundant and include [Jasmine](https://jasmine.github.io/), [AVA](https://github.com/avajs/ava), [Tape](https://github.com/substack/tape) and [Mocha](https://mochajs.org/) with possible outriders and related offerings like [Jest](https://jestjs.io/), [Puppeteer](https://github.com/puppeteer/puppeteer) and [QUnit](https://qunitjs.com/) also being worth considering as part of the mix.

**Comment by Matt-Esch** [comment]
I'm a big fan of tape because it promotes the idea of running individual tests rather than inverting control through some external test runner. When I include a library in my code I'm looking to be able to `node test/feature.js` to test any given feature.
