### ISSUE TITLE
Mock Ably

### ISSUE THREAD

**Issue by ndastur** [ably/ably-js#654]
Hi Guys
I'm wondering if it's possible to Mock Ably for my own tests. I.e. do things like intentionally have channel.publish(...) fail so that I can unit test the failure code?
Thanks

**Comment by mattheworiordan** [comment]
> do things like intentionally have channel.publish(...) fail so that I can unit test the failure code?

Publish with an invalid key perhaps?

**Comment by ndastur** [comment]
Sure. But there are a number of published error conditions. Some are worth a retry others not, so wanted to build that logic and start with some tests for that

**Comment by SimonWoolf** [comment]
Ultimately it's javascript, you can mock out method to return whatever you like and the library can't stop you 🙂
`channel.publish = (name, data, cb) => cb({message: 'error message', code: 40160, statusCode: 401});` etc

**Comment by ndastur** [comment]
Thanks @SimonWoolf . Yeap I guess that is the case. Probably the simplest. Thanks
