### ISSUE TITLE
Loading "closureTools.js" tasks...ERROR >> SyntaxError: Unexpected token ... in Travis CI

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#660]
See [this build output](https://travis-ci.org/github/ably/ably-js/jobs/695892754#L489).

It may be innocuous and unrelated to current CI instabilities, but it certainly doesn't look good.

It seems we adopted [grunt-closure-tools](https://www.npmjs.com/package/grunt-closure-tools), which appears to be some kind of a wrapper, [a couple of years ago](https://github.com/ably/ably-js/commit/32e59c5f49284655b50ddc80869185f37865be8e). It's not been updated for three years.

**Comment by QuintinWillison** [comment]
Only affects configs for Node.js 6 (older runtime).

**Comment by owenpearson** [comment]
Closing this issue as it appears to now be resolved.
