### ISSUE TITLE
Bad test: no_connection_lifecycle in failure.test.js

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#661]
It looks like expecting:
`suspended > connecting > suspending`

but actually seeing:
`suspended > connecting > disconnected`

after the initial:
`connecting > disconnected` (x3)

[Observed in CI](https://travis-ci.org/github/ably/ably-js/jobs/695892753#L1834):

```
✖ no_connection_lifecycle
Assertion Message: connection state for comet was connecting,disconnected,connecting,disconnected,connecting,disconnected,suspended,connecting,disconnected, expected connecting,disconnected,connecting,disconnected,connecting,disconnected,suspended,connecting,suspended
AssertionError:
[
  'connecting',   'disconnected',
  'connecting',   'disconnected',
  'connecting',   'disconnected',
  'suspended',    'connecting',
  'disconnected', 'closing',
  'closed'
]
deepEqual
[
  'connecting',
  'disconnected',
  'connecting',
  'disconnected',
  'connecting',
  'disconnected',
  'suspended',
  'connecting',
  'suspended'
]
    at Object.deepEqual (/home/travis/build/ably/ably-js/node_modules/nodeunit/lib/types.js:83:39)
    at Timeout._onTimeout (/home/travis/build/ably/ably-js/spec/realtime/failure.test.js:144:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
7:5:54.447 Ably: Channel state for channel "::": failed; reason: [ErrorInfo: Invalid channel id (::). (See https://help.ably.io/error/40010 for help.); statusCode=400; code=40010]
```

This could either be behaviour in the library implementation that has changed and now causes this test to fail or the test is making too many assumptions.

**Comment by QuintinWillison** [comment]
That's for latest Node (14) but we also [observe it in CI](https://travis-ci.org/github/ably/ably-js/jobs/695892751#L1728) for Node 10.

**Comment by lmars** [comment]
@owenpearson I recall you mentioning this test failure (which seems to consistently fail in CI), is it something you've managed to fix with the ongoing NodeUnit migration?
