### ISSUE TITLE
Ably does not appear in CodePen Pen Settings External Scripts Search CDNjs

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#670]
I recognise that this is part of a bigger story that we need to tackle soon around how this client library is distributed and made available to consumers, however I wanted to capture this particular use case as I think it's a no brainer for us (especially given key competitors to Ably all **do** appear in this list).

![Screenshot 2020-06-27 at 10 09 39](https://user-images.githubusercontent.com/8318344/85918939-f67c4f80-b85e-11ea-8980-1224c0c397d8.png)

To add a little bit of context, I'm spending this weekend working on a personal project which is using [React](https://github.com/facebook/react). It was the (rather marvellous) [documentation](https://reactjs.org/docs/getting-started.html) for React that got me navigating to [CodePen](https://codepen.io/) and poking around.

CodePen is a great example of an environment which has an exceptionally low barrier to entry, so a good opportunity to welcome developers in to experience Ably with just one click of a drop down.

I recognise we have our own JSBin implementation, but we also need to ensure we're visible and available on popular, trusted websites like CodePen.

**Comment by fliptopbox** [comment]
:clap: hey @QuintinWillison so good to hear someone else cheering for CodePen. I am a huge fan, and yeah we need to have Ably on that preset list! ATM I am adding the CDN link. If you have anything to share, please tag me.
https://codepen.io/fliptopbox

I would love some feedback or comments how to make this a better tool, so ... 
https://codepen.io/fliptopbox/pen/dyGzogY
(this is my very first interaction with the Ably product, so it is a bit rough)

Another phenomenal online tool is https://codesandbox.io/ (basically VSCode online)

It is better than CodePen (by a long shot), but as you so rightly pointed out CodePen has ... "exceptionally low barrier to entry", "developer community" a very active passion and general happiness and great excitement, oh yeah and some stunning pens to gawk at :D

**Comment by fliptopbox** [comment]
@kennethkalmer @QuintinWillison not sure who this should go to, anyway I wrote to CodePen ....

Hi Bruce,

Thanks for writing in!

Our external resources search is powered by the CDNjs API. You can submit new libraries to CDNjs through their GitHub repo at: https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md


—
Marie
CodePen · Documentation

**Comment by fliptopbox** [comment]
Also I think that we should remind ourselves that version 1.2 is now out :D 
So I think the publicly visibly DevRel stuff might do with a revisit or update?
Especially the awesome ones, the well deserved Ably "bragware" :D

**Comment by QuintinWillison** [comment]
Thanks @fliptopbox.
I might just get dangerous and have a go at submitting that myself. 😀 
(well, assuming the way we package at the moment is compatible)

**Comment by fliptopbox** [comment]
@QuintinWillison great stuff! please ping me (or share on Slack) so I can watch CodePen, to see when it lands.
I think this might also be worth sharing with our content team, get them to do a little bit of blog love to let the world know we are on CDNjs too. Some shameless trumpet blowing :D

Are you thinking of submitting all versions?
Out of curiosity does Ably have a "**current**" version on CDN (like an alias to the latest stable release)?

**Comment by owenpearson** [comment]
Closing this issue as Ably is now available on CDNjs (https://cdnjs.com/libraries/ably)
