### ISSUE TITLE
Couldn't find package "@ably/msgpack-js@^0.3.3" 

### ISSUE THREAD

**Issue by devdemi** [ably/ably-js#677]
Since today we've started to get the error message during `yarn install`:
> error Couldn't find package "@ably/msgpack-js@^0.3.3" required by "ably@^1.1.24" on the "npm" registry.

I tried to find this package on npm registry site https://www.npmjs.com/package/@ably/msgpack-js and page returns:
![image](https://user-images.githubusercontent.com/890372/89512693-40504200-d7dc-11ea-97b5-7aaa61d71766.png)

Is it npm's temporary problem? Or did someone drop the package from npm?

**Comment by SimonWoolf** [comment]
ESOCKETTIMEDOUT from npm is an npm issue. See npm service status at https://status.npmjs.org/ . If the package had been removed you would get a 4xx status code (probably 404 or 410), not a TCP timeout
