### ISSUE TITLE
Migrate code base to typescript

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#686]
Using typescript with strict type-checking will allow us to enforce better type safety in the project and will allow us to emit type definition files as part of the compile process rather than having to maintain them ourselves.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-319) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
I think the ts-node should allow transpilation of typescript along with ES6 code to browser compliant es5 code. Maybe it internally uses a build tool ( like babel ).

**Comment by owenpearson** [comment]
@sacOO7 That makes sense to me. I don't think I've ever used Typescript as a transpiler (I'm used to working in React projects where Babel is necessary to transform JSX anyway) but if we can get by without depending on Babel at all then I'm all for it 👍

**Comment by sacOO7** [comment]
Yes, we might not have to rely on babel. 
Btw, let me know once the team is up for discussion regarding the transition to typescript. I would like to share some of my views ( maybe I can post it async over chat). Typescript is a very widely discussed topic among the community and I know some of the folks who recommend and don't recommend it ( All depends on the project context and requirement haha)

Personally, I would always go with +1 for typescript. It works like charm in single-threaded env. like browser ( rare source map issues happen sometimes

**Comment by jimmywarting** [comment]
please don't migrate to typescript
