### ISSUE TITLE
Lib currently does not allow developers to specify a custom realtimeHost without also specifying a custom restHost

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#688]
[Link to internal discussion](https://ably-real-time.slack.com/archives/C017C5EPYG0/p1602054291005000)

> so there's plenty of small things (eg the implicit assumption that no-one would ever provide a realtimeHost without also providing a restHost) that technically don't quite match the logic required by the spec, but stick around because they don't actually cause any problems (there's really no reason anyone would set a custom realtimeHost without also setting a custom restHost), so no-one ever bothers to fix them.

**Comment by lmars** [comment]
Copying the comment I made in https://github.com/ably/ably-js/pull/682#discussion_r502061214:

> the split between restHost and realtimeHost is actually now obsolete because they always point at the same endpoint for a given environment. We'll be deprecating them in the spec in the near future.

I'd be tempted to close this as a won't fix.

**Comment by sacOO7** [comment]
@owenpearson can you check if https://github.com/ably/ably-js/pull/689 fix it. I didn't get much time to look at the PR. But, I think it should, because it's spec-compliant.
