### ISSUE TITLE
Various functions require a callback with (err, result) but docs imply should work with just (result)

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#69]
There're several functions (eg presence.get, rest.time) which take a callback which takes two arguments, `err` and the result. When given a callback of one argument, that argument is the error. But the readme & documentation refer to calling them with one argument (ie as `channel.presence.get(function(presence){...})`, eg [here](https://github.com/ably/ably-js#presence-on-a-channel-1)), which currently doesn't work.

Not sure if you intended the one-arg form to work and it's a bug that it doesn't, or if the documentation just needs updating

**Comment by paddybyers** [comment]
It's always (err, result), so it looks like a documentation issue.

**Comment by mattheworiordan** [comment]
I will update the docs on this, so I am closing.  However, @SimonWoolf if you see documentation issues in this repo itself then please reopen and point to the areas where we need to fix it
