### ISSUE TITLE
NPM module 'request' is deprecated

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#701]
See deprecation announcement [here](https://github.com/request/request/issues/3142) and a discussion around recommended alternatives [here](https://github.com/request/request/issues/3143).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-600) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Go for axios : )

**Comment by owenpearson** [comment]
Commenting here so I don't forget; it looks like [got](https://www.npmjs.com/package/got) is currently the only widely used high level HTTP client for NodeJS with support for HTTP/2.

If axios/axios#1175 or node-fetch/node-fetch#372 become resolved then they might be worth looking in to as well.

**Comment by jimmywarting** [comment]
I think you should go with node-fetch cuz then your frontend wouldn't need any extra large lib, beside Deno also has built in fetch

**Comment by jimmywarting** [comment]
besides axios don't work in web workers, axios is built around xhr (not fetch)
so by using axios then it would not work in web workers
