### ISSUE TITLE
ably-js 1.2.5 causes error in react-native

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#714]
The reported error is: `initFn is not a function` inside connectionManager.js.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-649) by [Unito](https://www.unito.io/learn-more)

**Comment by rakhahidayat** [comment]
have you finished to fix this ?

**Comment by owenpearson** [comment]
Hi @rakhahidayat, sorry I haven't fixed this yet but I released version 1.1.2 of `ably-js-react-native` which limits the ably-js version to 1.2.4 so you can use this as a workaround until a proper fix is available.

**Comment by rakhahidayat** [comment]
i've been used ably-js-react-native 1.1.2 but the error still same about initFn is not a function inside connectionManager.js, do you have any project that successfully build RN with ably-js-react-native ?

**Comment by owenpearson** [comment]
Hi @rakhahidayat that's very strange; `initFn` isn't even a thing in ably 1.2.4. Have you run `npm install` since you changed ably-js-react-native to 1.1.2? You can you check the version fields in `node_modules/ably/package.json` and `node_modules/ably-react-native/package.json` to see if you have the correct version installed.

**Comment by owenpearson** [comment]
Closing this out as it has been fixed in the 1.2.7 release.
