### ISSUE TITLE
authCallback bug, test coverage & additional type support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#72]
authCallback currently has no test coverage in the library, we need to add some.

Additionally, we need to add support for the callback to return:

* a token string
* a TokenDetails object
* a TokenRequest object

Based on the docs at https://github.com/ably/ably-js/blob/1c8dd8f35d50eb488d8cde4fa4b3510d21ceb470/common/lib/client/auth.js#L155-L156, I assume only a TokenRequest is supported.

See http://www.rubydoc.info/gems/ably/0.8.2/Ably%2FAuth%3Ainitialize as an example (under auth_callback),.

In our spec as well, we specify `When authCallback option is set, it will execute the callback and will expect either a token string, a TokenDetails object or a TokenRequest object which will in turn be used to request a token from Ably.`

**Comment by mattheworiordan** [comment]
I also don't think `authCallback` works when providing it with a valid signed TokenRequest.

See https://jsbin.ably.io/anadag/3/edit.  The error is:

```javascript
Ably: Auth.requestToken(): token request signing call returned error; err = {"keyName":"xVLyHw.koPkRA","timestamp":1437742607739,"nonce":"3114621597342193","mac":"O33fBmGloowPfOt7PKFpfZ5pspAna3ievCJCF6/qnB8="}
ably.min.js:formatted:1826 Ably: ConnectionManager.connectImpl(): Connection attempt failed with error; err = [c; statusCode=401; code=40170]
```

**Comment by paddybyers** [comment]
@SimonWoolf : are you ok to have a look at this please?

**Comment by SimonWoolf** [comment]
All three methods are supported already, see https://github.com/ably/ably-js/blob/1c8dd8f35d50eb488d8cde4fa4b3510d21ceb470/common/lib/client/auth.js#L280-L288 . PR #80 adds a quick test for each and updates the docstring. Re second comment, see https://github.com/ably/ably-js/issues/73#issuecomment-125998243
