### ISSUE TITLE
Browser directory is empty (1.2.7)

### ISSUE THREAD

**Issue by pjamrozowicz** [ably/ably-js#727]
The latest version of Ably (1.2.7) seems to be broken.

After installing the package with bower, the `Ably/browser` directory is empty.
Both `package.json` and `bower.json` point to it (`./browser/static/ably-node.js`) so it seems that the distributed files are missing something.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-674) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
Thanks for the report, @pjamrozowicz ... we'll take a look.

**Comment by owenpearson** [comment]
Hi @pjamrozowicz, thanks for reporting this to us, I'm sorry you're experiencing this issue. The reason this is broken is that we took the decision to remove built distribution files from our Git repository and bower depends on these files being available on GitHub whenever you install.

As a temporary workaround you can copy the files directly from the CDN into the your `bower_components/Ably/browser/static` directory. If you're looking specifically for the NodeJS compatible version it's available from [CDNJS](https://cdnjs.cloudflare.com/ajax/libs/ably/1.2.7/ably-node.js). Of course, version 1.2.6 and below will still work as expected. I hope this helps.

With regards to a long term solution, I can see that bower has been deprecated for a few years now so we would like to understand what your reasons are for using bower over other package managers such as NPM or Yarn?

**Comment by pjamrozowicz** [comment]
@owenpearson Thank you for the workaround solutions! Please feel free to close this issue.

About bower, yes, yes, it's definitely deprecated for quite some time already, sadly a legacy project depends on it, so I need to make it work for the time being 😉
