### ISSUE TITLE
"ably/promises" fails with `Cannot find module './nodejs/index'`

### ISSUE THREAD

**Issue by kazk** [ably/ably-js#729]
At least with v1.2.7, importing `ably/promises` fails with `Cannot find module './nodejs/index'` because it does not include `nodejs/` directory.

To reproduce, install the latest `ably`.

```text
❯ tree --dirsfirst
.
├── browser
│   └── static
│       ├── ably-commonjs.js
│       ├── ably-commonjs.noencryption.js
│       ├── ably.js
│       ├── ably.min.js
│       ├── ably-nativescript.js
│       ├── ably-node.js
│       ├── ably.noencryption.js
│       ├── ably.noencryption.min.js
│       └── ably-reactnative.js
├── resources
│   ├── Browserstack-logo@2x.png
│   └── typescript-demo.gif
├── ably.d.ts
├── callbacks.d.ts
├── callbacks.js
├── CHANGELOG.md
├── LICENSE
├── package.json
├── promises.d.ts
├── promises.js
└── README.md
```

```text
❯ jq .version package.json
"1.2.7"
```

```text
❯ cat promises.js | head -n 10
"use strict";
function promisifyOptions(options) {
  if(typeof options == 'string') {
    options = (options.indexOf(':') == -1) ? {token: options} : {key: options};
  }
  options.promises = true;
  return options;
}

var Ably = require('./nodejs/index');
```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-676) by [Unito](https://www.unito.io/learn-more)

**Comment by owenpearson** [comment]
Hi, @kazk, thanks for reporting this to us. As a temporary workaround you can change the require  call on that line to`require('./browser/static/ably-node.js')` and it should work as expected. I'll be releasing a new patch version later on today as a more stable long-term solution.
