### ISSUE TITLE
attaching and detaching events are not emitted

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#74]
See https://jsbin.ably.io/iluxiz/1/edit

I would expect attaching and detaching events to be logged

**Comment by paddybyers** [comment]
@SimonWoolf are you ok to have a look at this please?

I'm pretty sure this will do the job: https://github.com/ably/ably-js/tree/emit-attaching

but we need test coverage as well.

**Comment by SimonWoolf** [comment]
@paddybyers Added a [spec](https://github.com/ably/ably-js/commit/f6066c5d96c56eaba5639de3b984f7ef73603a71) and a [minor tweak](https://github.com/ably/ably-js/commit/d7ca716a44694a186085adfa7acbc4a83facb8e3) (removing a redundant detach event to make the spec pass) to that branch
