### ISSUE TITLE
Library apparently broken in webworkers

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#751]
I believe this will be a regression from the webpack migration (v1.2.6) and the solution is to create a new webpack target which builds specifically for webworkers.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-846) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
See https://github.com/ably/ably-js/pull/756 for the PR
