### ISSUE TITLE
Source map warning in chrome and webkit when using CDN

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#773]
Since adding source maps to the library in 1.2.10 browsers will automatically try to get the source maps from the CDN. We either need to host the source maps and all the source code on the CDN or make it so that we only distribute files through the CDN without the `//# sourceMappingURL=ably.min.js.map` directive at the bottom of the file.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4385) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
(should also look to remove this directive from 1.2.10 on the CDN)

**Comment by mattheworiordan** [comment]
This is a duplicate #191. @owenpearson I won't close this as this is synced with Jira.  Can you please consolidate issues? 

I saw this problem again today.  We should just serve the sourcemaps, that's better for end users, and easily done in the publishing tools.

**Comment by owenpearson** [comment]
I'll close this one anyway since I only opened this to track the dev tools error we were getting when I added source maps for all the bundles. I definitely intend to upload the sourcemaps to the CDN in the near future, we intend to move all of the deployment code from infrastructure in to this repo and make a CD workflow so will probably deal with this alongside that work.

**Comment by alamaral** [comment]
I'm still consistently seeing this issue in my product.  Here is the only place the cdn is referenced and it has a version:

    <script src="https://cdn.ably.io/lib/ably.min-1.js"></script>

One problem may be that ably.min-1.js still has the reference to //# sourceMappingURL=ably.min.js.map as the last line, and that might be what's failing.  However, I tried the ably.min-1.2.js file and that reference is gone, but the error still occurs with 1.2.

I can find the map file for the -1 version: https://cdn.ably.io/lib/ably.min-1.js.map, and the -1.2 version: https://cdn.ably.io/lib/ably.min-1.2.js.map but it looks like something is still incorrectly referencing the unversioned map file.
Also, there is a file https://cdn.ably.io/lib/ably.min-1.1.js available, but no https://cdn.ably.io/lib/ably.min-1.1.js.map (or the permissions aren't correct as it returns an access denied error).

**Comment by owenpearson** [comment]
Hi @alamaral, thanks for reporting this. I'll reopen the issue and we'll look into it with priority.

**Comment by VeskeR** [comment]
Closing this as stale and longer repdoducible: file returned by https://cdn.ably.com/lib/ably.min-1.js.map does not have `//# sourceMappingURL=ably.min.js.map` directive
