### ISSUE TITLE
Improve security standards

### ISSUE THREAD

**Issue by Matt-Esch** [ably/ably-js#778]
I would like to recommend the following to help maintain high security standards

  - Consider using the security eslint plugin to help lint for potential security issues. This errs toward a warn heavy development cycle where you should expect a number of warns to be allowable by default. https://github.com/nodesecurity/eslint-plugin-security
  
  - Address the vulnerable node_modules systematically in some way. Running `npm audit --production` raises 1 moderate vulnerability. There are a number of dev deps with vulnerabilities. I would suggest that we upgrade all vulnerable modules regardless. If we add a check for this to the test suite, tests should fail if new vulnerabilities are discovered.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1058) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Thanks, @Matt-Esch - all sounds great.

@owenpearson, this (re `npm audit`) sounds like a quick win:

> If we add a check for this to the test suite, tests should fail if new vulnerabilities are discovered.
