### ISSUE TITLE
Error when closing a connection

### ISSUE THREAD

**Issue by PierBover** [ably/ably-js#786]
I'm trying to close the connection on my Node application but whenever I try to do it I get this error:

```
ConnectionManager.failQueuedMessages(): failing 1 queued messages, err = [ErrorInfo: Connection closed; statusCode=400; code=80017; see https://help.ably.io/error/80017 ]
```

Not sure if I'm missing something or this is a bug. I'm on `"ably": "^1.2.13"` installed just an hour ago.

According to [the docs](https://knowledge.ably.com/error-code-80017-connection-already-closed) the error means the connection is already closed, which isn't true because the connection state returns `connected` before trying to close it. I can also see the connection active in the dashboard.

I've tried both `ably.close()` and `ably.connection.close()` with the same result.

The connection does close, as `ably.connection.status` returns `closed` after closing it, but it's just weird to receive that error.

For now I'm just ignoring the error so that it doesn't break my application which is ugly...

```
try {
  ably.connection.close();	
} catch (error) {
  console.log(error);
}
```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1134) by [Unito](https://www.unito.io)

**Comment by owenpearson** [comment]
Hi @PierBover, thanks for reporting this to us,

The error message you are seeing is normal if you have a message that is awaiting response from Ably when you call `ably.close`. This most likely means the library is waiting for acknowledgement that a publish or presence message has been successful. The best way to prevent this is to ensure that all publish/presence messages are completed before calling `ably.close` (if you are using promises this means waiting for the promise to resolve, if you are using callbacks this means waiting for the callback to execute).

Here are some examples to demonstrate what I mean...

Here we publish a message once the library is connected but immediately close the connection. If you run this with your API key you should get the same error message.
```js
const Ably = require('ably');

const realtime = new Ably.Realtime.Promise('XXXXXXXXXXXXX:XXXXXXXXXXXXXXXX');
const channel = realtime.channels.get('my_channel');

realtime.connection.on('connected', () => {
  channel.publish('event', 'data');
  realtime.close()
});
```

Here we do exactly the same but only close the connection after the publish is completed (here I'm using `Promise.then` but you can also use `await` inside an async function). This time you shouldn't see any error.
```js
const Ably = require('ably');

const realtime = new Ably.Realtime.Promise('XXXXXXXXXXXXX:XXXXXXXXXXXXXXXX');
const channel = realtime.channels.get('my_channel');

realtime.connection.on('connected', () => {
  channel.publish('event', 'data').then(() => {
    realtime.close();
  });
});
```

I hope this helps, please let me know if you need me to clarify anything or if you have any further questions.

**Comment by PierBover** [comment]
Thanks for your answer @owenpearson . Awaiting the for the messages to be published solved the issue.

Although I must say the error is pretty confusing. If the issue is that there are pending messages before closing, that's what it should say and not:

> Error code: 80017 - Connection already closed
> This error will usually occur if you're attempting to close a connection you've already closed. Make sure you're not accidentally calling a function which contains close multiple times.

https://knowledge.ably.com/error-code-80017-connection-already-closed

**Comment by owenpearson** [comment]
@PierBover You're absolutely right, I didn't notice that before. I'll see to it that we get a new help page set up for this error to make it less confusing, thanks.
