### ISSUE TITLE
Continuous Delivery via GitHub workflow

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-js#805]
I think we should model something on what we do in `ably-asset-tracking-android`'s [publish workflow](https://github.com/ably/ably-asset-tracking-android/blob/main/.github/workflows/publish.yml).

The only possible reason we may wish not do do it that way is that there's a chance the publish workflow will fail, and in which case we then end up with a Git tag that's been pushed optimistically to indicate that we've done a release when there may actually be subsequent commits required to the `main` branch in order to fix it up into a state where it's _actually, really_ able to do a release (e.g. [to npm](https://www.npmjs.com/package/ably)).

Therefore, perhaps we should be refactoring our general release process (across all SDKs) so that the tag is not pushed to GitHub until we know it definitely has (or can, in the case of [ably-go](https://github.com/ably/ably-go) where the release _is_ the tag) be released. 

Relates to https://github.com/ably/ably-js/issues/551.

Also see GitHub's blog post (23 September 2021): [Announcing npm’s new access token format](https://github.blog/2021-09-23-announcing-npms-new-access-token-format/)

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1263) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
@QuintinWillison you mentioned in the stand up we should reach descriptions before closing tickets. We have gone through a few people now who don't actually understand what is being asked off here. after reading the description I am not sure either. 

Could you add an acceptance criteria please so it is clear for who ever picks this up

**Comment by owenpearson** [comment]
Closing in favour of #893
