### ISSUE TITLE
Ably-js does not call error callback when channel attach fails when using comet transport

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js#81]
With websocket transport, the attach callback is called with err = ` {"statusCode":400,"code":40010,"message":"Invalid channel id ()"}`

With xhr, the callback is never called, though the error is logged to the console: `"Ably: CometTransport.sendItems(): on complete: err = {"statusCode":400,"code":40010,"message":"Invalid channel id ()","serverId":"frontend.17d9.sandbox-eu-central-1-A.i-aaf1c864"}"`

Example: `channelattachempty` test with `transports: ['xhr']`

**Comment by mattheworiordan** [comment]
Rerun this test when new transport upgrade changes are deployed

**Comment by SimonWoolf** [comment]
Confirm fixed by upgrade changes.
