### ISSUE TITLE
Incorrect type for `errorCallback`

### ISSUE THREAD

**Issue by aboodman** [ably/ably-js#826]
The `errorCallback` parameter to `publish` is documented to receive `(err: Ably.Types.ErrorInfo | undefined)`. However, the client library is actually passing me `null` in the success case.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1281) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Thanks for reporting this, @aboodman - we'll take a look. It might help the team if you could let us know whether you're using the latest version of the SDK ([1.2.4](https://github.com/ably/ably-js/releases/tag/1.2.14)) and perhaps provide us some detail around your runtime context (browser, Node, w/ React, etc..).
