### ISSUE TITLE
ErrorInfo does not extend Error

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#842]
This will improve mocha output (mocha complains if `done` is invoked on a non-error) and will give ErrorInfos call stacks which may help with debugging.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4428) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment]
Closing as `ErrorInfo` extending `Error` was implemented in https://github.com/ably/ably-js/pull/1129
