### ISSUE TITLE
TypeScript: Investigate alternative build toolchains

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#856]
After migrating the library source code to TypeScript the bundle size has increased by about 10% when using the standard `ts-loader` setup with webpack. Hopefully we can ship it without such a big increase so we need to investigate whether we can mitigate this by using babel typescript preset, alternative minifiers, etc.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1357) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
Closing as this is something we will not progress
