### ISSUE TITLE
Hard coded transport to work around bugs need to be removed

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#86]
See https://github.com/ably/ably-js/commit/c6b28e844e8313905c51e515e8487771b9c8b0ea#diff-1d0cfc8abf35d1dc70704d4bcff8bf85R854 for an example.

We need to review the entire library to see where this has been done and ensure we don't lock into a transport unless the transport is relevant to the test.

**Comment by SimonWoolf** [comment]
Blocked by: https://github.com/ably/ably-js/issues/27 , and upgrade issues

**Comment by SimonWoolf** [comment]
@me to retest whether most of these can be removed post-upgrade

(not the limits tests as need precise connection nums)

**Comment by SimonWoolf** [comment]
Fixed by https://github.com/ably/ably-js/pull/127
