### ISSUE TITLE
Bundle size increases with 2mb when bringing in ably-node library

### ISSUE THREAD

**Issue by kristohberg** [ably/ably-js#869]
I've noticed that when I bring in the "browser/static/ably-node" into a node project the total bundle size increases with approx 2mb. The project is bundled using esbuild with the tree shaking feature turned on. The 2mb extra is about 25% of our total bundle size. This has lead us to do our own http requests against you api which is far from optimal. 

Do you have ideas of how this can be solved? 

thanks!

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1443) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Hi @kristohberg 👋 - can you explain a little bit more about your runtime context? While I'm pretty sure there's little we can do to help regarding the impact on your bundle size, at least in the short term, I am intrigued as to _why_ this is causing you issues?

Have you identified a bug in our library or the way it's being packaged?

I am also interested to understand what you mean when you say:

> This has lead us to do our own http requests against you api

**Comment by owenpearson** [comment]
Hi @kristohberg, I've just had a look in to this and can't see any reason why your bundle should increase by this much. I tried bundling a node script with esbuild which contains only `require('Ably')` and the total bundle size comes out as 311.5kb with the `--minify` option (and 712.0kb without) which sounds about right to me. I'd need to know a bit more about your build config to be able to figure out why your bundle size is so much bigger.

**Comment by kristohberg** [comment]
@QuintinWillison sorry for the late reply, but it seems like @owenpearson is onto something. We do not use require but rather the recommended _import * as Ably from "ably"_.  

@owenpearson would you care to share the repo where you tested it out?  As we are working close source so I am not able to share ours. 

But there is definitively something that I am missing.  
Thank you for helping me debug this!

**Comment by owenpearson** [comment]
@kristohberg I tried the same with the ES6 import statement and still get the same result.

You can reproduce this locally by running these commands in a new directory:
1. `npm i esbuild ably`
2. `echo "import * as Ably from 'ably';" > index.js`
3. `npx esbuild index.js --platform=node --bundle --minify --outfile=bundle.js`

When I run this I get the following output:
```
  bundle.js  312.1kb

⚡ Done in 48ms
 ```

I'd suggest trying those steps using your existing esbuild configuration instead of step 3 as a potential next step.

**Comment by owenpearson** [comment]
Closing as stale
