### ISSUE TITLE
Export library types outside the `Types` namespace

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#909]
* Using the `Types` namespace is idiosyncratic and generally not what other libraries do.
* Ideally in v2 of the library we would move the types over completely, but for now we should export types from outside that namespace while keeping the namespace there for compat.
* See [internal slack thread](https://ably-real-time.slack.com/archives/C017C5EPYG0/p1637318700006800) for some discussion.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1640) by [Unito](https://www.unito.io)

**Comment by lawrence-forooghian** [comment]
@owenpearson I'm not sure what the "for now" in your description means — was this issue originally written with v1 in mind? Given that this issue is now for v2, would you mind clarifying whether or not we want to remove the `Types` namespace completely?

**Comment by owenpearson** [comment]
Yeah I'd say remove it completely 👍

**Comment by lawrence-forooghian** [comment]
Resolved by https://github.com/ably/ably-js/pull/1518.
