### ISSUE TITLE
Question: How do you publish a message with an explicit clientId

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#92]
I know there is a separate issue to implicitly attach a `clientId` to messages implicitly based on the authenticated connection, however looking at [the definition of the publish method](https://github.com/ably/ably-js/blob/ca15aac772cc161f7ef55a404e6071611f11aa87/common/lib/client/realtimechannel.js#L51-L77), I can't see any obvious way to include a clientId.

I would expect `publish({ name: name, data: data, clientId: clientId })` to work, but I think https://github.com/ably/ably-js/blob/ca15aac772cc161f7ef55a404e6071611f11aa87/common/lib/client/realtimechannel.js#L71 prevents that from working.

@SimonWoolf assuming I have read this correctly, we may need to add this functionality with some test coverage.

**Comment by paddybyers** [comment]
`publish({ name: name, data: data, clientId: clientId })` is intended to work. Won't that take this branch?

https://github.com/ably/ably-js/blob/ca15aac772cc161f7ef55a404e6071611f11aa87/common/lib/client/realtimechannel.js#L67

**Comment by mattheworiordan** [comment]
Good point, so only https://github.com/ably/ably-js/blob/ca15aac772cc161f7ef55a404e6071611f11aa87/common/lib/client/realtimechannel.js#L71 needs to be fixed yes as it explicitly discards `clientId`?

**Comment by paddybyers** [comment]
> needs to be fixed yes as it explicitly discards clientId?

I think maybe you're misreading it. That branch is handling the case where `name` and `data` are given as separate args, and I don't think it's extensible to support also `clientId` in that form; there may in future be any number of other members of a `Message` that we might want to support. It's simply a convenience for passing `name` and `data`.

**Comment by mattheworiordan** [comment]
I am misreading it, sorry :|
