### ISSUE TITLE
Refactor lib entry points to avoid use of webpack aliases

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-js#922]
- Currently we use webpack aliases to inject platform specific code at build time
- This causes a lot of problems for us because it means that the source code itself isn't a working typescript project. For example:
   - Unit tests are very hard to set up because we need to mock all of these aliases.
   - Debugging the library by setting break points in the source code doesn't work at all.
- What I would propose is to refactor the common code to export functions which take the platform specific configuration as an argument and return Rest and Realtime classes. Then we create platform specific entry points which call these functions with the relevant platform configurations.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1650) by [Unito](https://www.unito.io)

**Comment by Peter-Maguire** [comment]
Closed by #982
