### ISSUE TITLE
Listen when client enter and exit

### ISSUE THREAD

**Issue by jinglescode** [ably/ably-js#926]
Is there a subscribe API to listen for when a client enters (`channel.presence.enter()`) and exit?

Or are we supposed to call `channel.presence.get` at a fixed interval to see who is still connected?
```
channel.presence.get(function (err, presenceSet) {
  presenceSet;
});
```

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1663) by [Unito](https://www.unito.io)

**Comment by Peter-Maguire** [comment]
You can subscribe to presences with:

```js
        channel.presence.subscribe("enter", enterEvent);
        channel.presence.subscribe("leave", leaveEvent);
```

**Comment by jinglescode** [comment]
perfect!
this should be included in readme https://github.com/ably/ably-js
