### ISSUE TITLE
Push Activation State Machine for Web

### ISSUE THREAD

**Issue by Peter-Maguire** [ably/ably-js#932]
The activation state machine needs to store information about the device and registration state, for web this should be designed as (or to be used within) a WebWorker

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-1672) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
Hey everyone - pleased to say that **'Push notification support for web browser in ably-js lib'** and **'React Native support for Push Notifications'** are in development and should be released over the next 6-8 weeks. These are duplicate issues so I will close them.

cc @owenpearson

**Comment by moAlobaidi** [comment]
> Hey everyone - pleased to say that **'Push notification support for web browser in ably-js lib'** and **'React Native support for Push Notifications'** are in development and should be released over the next 6-8 weeks. These are duplicate issues so I will close them.
> 
> 
> 
> cc @owenpearson 

Was Push Notification support released for React Native?
