### ISSUE TITLE
Push channels

### ISSUE THREAD

**Issue by Peter-Maguire** [ably/ably-js#933]
RestChannel and RealtimeChannel need to have push interfaces

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1673) by [Unito](https://www.unito.io)

**Comment by jamienewcomb** [comment]
Hey everyone - pleased to say that **'Push notification support for web browser in ably-js lib'** and **'React Native support for Push Notifications'** are in development and should be released over the next 6-8 weeks. These are duplicate issues so I will close them.

cc @owenpearson
