### ISSUE TITLE
Version 1.2.18 onwards containing console logs

### ISSUE THREAD

**Issue by WillPoulson** [ably/ably-js#965]
Hi,

After updating to 1.2.20 of your package I started to receive lots of console logs of "random" numbers.
Using chrome debug tools I tracked it down to your package, I've attached a screenshot of where the stack trace got to.

![Screenshot 2022-04-22 at 08 38 26](https://user-images.githubusercontent.com/12980659/164633167-5a2f1723-c290-449d-99ab-5d2f87a41e36.png)

I don't think these logs should be here as they're currently flooding my console. I'm downgrading for now.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1797) by [Unito](https://www.unito.io)

**Comment by WillPoulson** [comment]
Looks like this was introduced in version `1.2.18`. Downgrading to `1.2.17` for now removes the console log flood.

**Comment by paddybyers** [comment]
Thanks for reporting this. We'll update asap.

**Comment by owenpearson** [comment]
@WillPoulson Thanks for reporting, you're right that those log statements shouldn't be there. They'll be removed in the next release. Sorry for the inconvenience.
