### ISSUE TITLE
How to shut down Ably when no valid token can be provided?

### ISSUE THREAD

**Issue by JCB-K** [ably/ably-js#990]
Hi! I have a use case that I'm unsure of how to handle with the Ably SDK. We use the `authCallback` method passed to the SDK to fetch a new token whenever the old one expires. In certain cases we are not able to provide a new token because the resource connected to the Ably connection does not exist any more - any messages that a client would send via Ably can be safely ignored at this point.

When this happens the token endpoint returns a 404, and Ably will keep retrying this call indefinitely. Can I somehow return something that instructs the SDK that there's no need to retry, and to go into a disconnected state?

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1931) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
If the token endpoint responds with 403, Ably will close the connection and not retry.
